### ISSUE TITLE
Disable mason-lsp "K" hover_doc

### ISSUE THREAD

**Issue by speri203** [AstroNvim/astrocommunity#100]
I would like to use lspsaga for my LSP functionality like hover_doc and peek_definition. I am trying to override the default "Shift K" functionality but I am unable to unmap the key properly. My python.lua is based on the Python community pack found on this github so was hoping I could get help related to this here. My python.lua looks like this 

```
local utils = require "astrocommunity.utils"
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      -- Ensure that opts.ensure_installed exists and is a table or string "all".
      if not opts.ensure_installed then
        opts.ensure_installed = {}
      elseif opts.ensure_installed == "all" then
        return
      end
      -- Add the "python" and "toml" language to opts.ensure_installed.
      utils.list_insert_unique(opts.ensure_installed, { "python", "toml" })
    end,
  },
  {
    "williamboman/mason-lspconfig.nvim",
    opts = function(_, opts)
      -- Ensure that opts.ensure_installed exists and is a table.
      if not opts.ensure_installed then opts.ensure_installed = {} end
      -- Add pyright lsp to opts.ensure_installed using table.insert.
      utils.list_insert_unique(opts.ensure_installed, {})
    end,
  },
  {
    "jay-babu/mason-null-ls.nvim",
    opts = function(_, opts)
      -- Ensure that opts.ensure_installed exists and is a table.
      if not opts.ensure_installed then opts.ensure_installed = {} end
      -- Add to opts.ensure_installed using vim.list_extend.
      utils.list_insert_unique(opts.ensure_installed, { "isort", "blue" })
    end,
  },
  {
    "jay-babu/mason-nvim-dap.nvim",
    opts = function(_, opts)
      -- Ensure that opts.ensure_installed exists and is a table.
      if not opts.ensure_installed then opts.ensure_installed = {} end
      -- Add to opts.ensure_installed using table.insert.
      utils.list_insert_unique(opts.ensure_installed, "python")
    end,
  },
  {
    "linux-cultist/venv-selector.nvim",
    opts = {},
    keys = { { "<leader>lv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv" } },
  },
}
```

And the mappings.lua to make the functionality I want work looks like this:
  ```
  ["K"] = { ":Lspsaga hover_doc<cr>", desc = "Lspsaga hover documentation" },
    ["<S-K>"] = { ":Lspsaga hover_doc<cr>", desc = "Lspsaga hover documentation" },

```

I have also tried setting prior to the above lines but the default lsp hover_doc still pops up.
`    ["K"] = false ,`

The current functionality looks like this:
![Screenshot 2023-03-27 at 10 22 14 PM](https://user-images.githubusercontent.com/36865599/228011243-e334f9f5-2f74-4bf9-a063-976475e8bf77.png)

Whereas if I call LSPsaga manually the output looks like this
![Screenshot 2023-03-27 at 10 22 37 PM](https://user-images.githubusercontent.com/36865599/228011326-ba78434e-1a6c-4421-b478-ac610014f765.png)

**Comment by ZackGlenn** [comment]
You need to unmap `K` in your lsp mappings specifically. If you're using the example user config it's in `user/init.lua` and you should have something like this in the `lsp` table

```lua
mappings = {
  n = {
    K = false
  }
}
```

**Comment by Uzaaft** [comment]
Closing this. Please re-open if this is still an issue. Or visit the discord. :)
