### ISSUE TITLE
Overseer open display on the wrong side with error

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#1023]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

kitty

### Describe the bug

The window of Overseer display on the left side instead of the bottom side, and with 
this error:
```
Failed to run `config` for overseer.nvim

...hare/AstroNvim4/lazy/overseer.nvim/lua/overseer/init.lua:278: attempt to index field 'on_config' (a nil value)

# stacktrace:
  - /overseer.nvim/lua/overseer/init.lua:278 _in_ **enable_dap**
  - /overseer.nvim/lua/overseer/init.lua:303 _in_ **setup**
  - /astrocommunity/lua/astrocommunity/code-runner/compiler-nvim/init.lua:17 _in_ **config**
  ```

### Steps to Reproduce

Apply command:
:OverseerToggle

### Expected behavior

Display the window on the bottom, as before (usual).

### Screenshots

![Capture d’écran du 2024-06-03 09-07-18](https://github.com/AstroNvim/astrocommunity/assets/5823264/e6f27ae5-61bc-4403-acec-648fef7c7cae)

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
  { import = "astrocommunity.code-runner/overseer-nvim" },

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Uzaaft** [comment]
You're mistaken.  It's not opening on the wrong side, it's working correctly

**Comment by Uzaaft** [comment]
i'm not sure what to tell you. take a look at the overseer.nvim config, opening on the left is how it works OOB. 

Taking a look at the error.

**Comment by mehalter** [comment]
@Uzaaft you are confusing `:OverseerToggle` and `:OverseerOpen`. The toggle should display it on the bottom. My guess is execution is getting stopped early and messed up because of whatever that error is

**Comment by mehalter** [comment]
Also I cannot replicate the issue with the provided minimal configuration. It looks like it was not properly set up and tested as it's not adding overseer at all

**Comment by MrMic** [comment]
```
nvim -u repro.lua 
``` 
works fine.

**Comment by mehalter** [comment]
yeah, that works fine because that's the file I made, but `:OverseerToggle` shows no command....

**Comment by mehalter** [comment]
so I cannot reproduce the bug given that configuration

**Comment by mehalter** [comment]
>  I can replicate the bug with the minimal `repro.lua` provided below

This requirement (which you checked) is added to the checklist for a reason 😄

**Comment by MrMic** [comment]
Do you need temporary access to my config repo?

**Comment by mehalter** [comment]
No, I would like you to make a minimal reproducing configuration based on the template above to recreate the bug with as few changes as necessary. This helps us weed out if the issue is on our end or something in your configuration. Edit the file in your original message, import overseer, see if the problem exists. If it doesn't then you should do some more research to figure out what you may have in your configuration that is breaking things. We as maintainers do not have the time to go through each person's hundreds of lines of personal configuration to identify bugs, sorry!

**Comment by mehalter** [comment]
Also in the future, when doing the checklist we provide as a requirement to open an issue, please pay attention to those and do not check off things that have not been done. Until it has been done then an issue isn't investigated enough to be opened.

**Comment by mehalter** [comment]
We also need clear steps to reproduce the error. For example, Step 1: `nvim` (open neovim), Step 2: `:OverseerToggle` (see error). You should test this step by step process _exactly_ given a fresh installation of the `repro.lua` that you provide so that we can actually reproduce whatever bug you are claming. The idea of the issue template is for us as maintainers to actually get to the bug and be able to debug it. These steps could include filetypes/language servers/other packs that are required to replicate the bug/example files if they are used to recreate the bug/etc.

Hopefully this is clear! Let me know if you have any questions about this 😄

**Comment by Uzaaft** [comment]
> @Uzaaft you are confusing `:OverseerToggle` and `:OverseerOpen`. The toggle should display it on the bottom. My guess is execution is getting stopped early and messed up because of whatever that error is

Am I....?

**Comment by mehalter** [comment]
Ok,if you are able  to replicate it reliably then definitely respond back here. For now we can leave it open just in case anyone else runs into it and can provide information

**Comment by mehalter** [comment]
Please update the minimal `repro.lua` in your original message to help aid this and futureproof the issue

**Comment by MrMic** [comment]
> Please update the minimal `repro.lua` in your original message to help aid this and futureproof the issue

Done.

**Comment by MrMic** [comment]
After update 
```
:OverseerToggle
```
open as expected at the bottom (even if it is a bit small...)
But I still get the error 🤔

**Comment by mehalter** [comment]
Nice! Good luck resolving that last bit!

**Comment by Uzaaft** [comment]
> After update
> 
> ```
> :OverseerToggle
> ```
> 
> open as expected at the bottom (even if it is a bit small...) But I still get the error 🤔

added in a commit from like 1 hour ago 😂😂 So I was right all along.

**Comment by MrMic** [comment]
See the issue with the creator of Overseer and it comes from 
nvim-dap that seems too old. I will try to fix that alone.
