### ISSUE TITLE
Transparent.nvim doesn;t turn heirline transparent

### ISSUE THREAD

**Issue by Zedai00** [AstroNvim/astrocommunity#1028]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

ArchLinux 6.9.1

### Terminal/GUI

kitty

### Describe the bug

Downloading transaparent.nvim doesn't turn statusbars transparent and folds also

### Steps to Reproduce

1. Import astrocommunity.colors.transparent-nvim
2. See Everything is not transparent especially statusbars and fold

### Expected behavior

Everything should be transparent

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/33319711/927ae03b-8a5c-446e-b63e-1340f17d92a8)

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Uzaaft** [comment]
This is more of an limitation in the plugin that it is a bug.

**Comment by Zedai00** [comment]
It turns transparent on astrodark theme but not on others such as tokyonight

**Comment by Uzaaft** [comment]
You should take that up with the plugin maintainer @Zedai00.

**Comment by Uzaaft** [comment]
We just provide a plugin spec. If the plugin is jank and doesn't work with all themes that's something you should take up with the plugin maintainer.
