### ISSUE TITLE
bash pack uses wrong bin for shellcheck on Apple ARM

### ISSUE THREAD

**Issue by 20k-ultra** [AstroNvim/astrocommunity#103]
When using the bash pack and opening a shell script, I see the following error in my lsp logs:

```
[ERROR][2023-03-28 11:46:08] ...lsp/handlers.lua:485	"15:46:08.627 ERROR ⛔️ Error while linting: Error: ShellCheck: failed with code undefined: Error: spawn Unknown system error -86\nout:\n\nerr:\n"
```

after finding https://github.com/koalaman/shellcheck/issues/2680 I have concluded that the error 86 is because the shellcheck version used is not built for ARM.

Interestingly, when I install shellcheck via brew, I can run it so I think this pack is just downloading the wrong binary or something ?

**Comment by mehalter** [comment]
This is unrelated to AstroCommunity and should be brought up in either [Mason.nvim](https://github.com/williamboman/mason.nvim) or [mason-null-ls.nvim](https://github.com/jayp0521/mason-null-ls.nvim). Whichever is causing this.

**Comment by 20k-ultra** [comment]
yup, it seems like shellcheck doesn't ship a binary for apple silicon https://github.com/koalaman/shellcheck/issues/2714.

Once that is resolved, https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/index/shellcheck/init.lua needs to be updated to pull the right arch.

**Comment by utkarshgupta137** [comment]
@20k-ultra Do you have rosetta setup? I'm able to open a shell script without any issues on M1 Pro.

**Comment by 20k-ultra** [comment]
No, I resolved the issue for now by adding the following to my config:

```
{ "williamboman/mason.nvim", opts = { PATH = "append" } },
``` 

This uses my system installed shellcheck. I did this because the shellcheck version from brew works. I'm week 1 on apple silicon so didn't know about Rosetta. I could try if that works too but it will be a workaround to the real issue I mentioned above.

**Comment by utkarshgupta137** [comment]
> No, I resolved the issue for now by adding the following to my config:
> 
> ```
> { "williamboman/mason.nvim", opts = { PATH = "append" } },
> ```
> 
> This uses my system installed shellcheck. I did this because the shellcheck version from brew works. I'm week 1 on apple silicon so didn't know about Rosetta. I could try if that works too but it will be a workaround to the real issue I mentioned above.

You'll probably need rosetta for a few tools, follow this: https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/

**Comment by luxus** [comment]
i can compile most of the binaries with darwin-nix, i changed the path to append of the mason binaries so it prefers the system binaries
