### ISSUE TITLE
Go pack have inccorect config

### ISSUE THREAD

**Issue by nfort** [AstroNvim/astrocommunity#1044]
### Describe the bug

Inccorect config

### Steps to Reproduce

1. Try command :GoRun
2. Get some errors

### Expected behavior

Run command

### Additional Context

i create issue https://github.com/ray-x/go.nvim/issues/474 and after research determine problem with
https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/go/init.lua
```
  {
    "ray-x/go.nvim",
    dependencies = {
      "ray-x/guihua.lua",
      "neovim/nvim-lspconfig",
      "nvim-treesitter/nvim-treesitter",
    },
    opts = {
      disable_defaults = true,
      diagnostic = false,
    },
    event = { "CmdlineEnter" },
    ft = { "go", "gomod" },
    -- Prevents Neovim from freezing on plugin installation/update.
    -- See: <https://github.com/ray-x/go.nvim/issues/433>
    build = function() require("go.install").update_all() end,
  },
```
it fixed config after change to
```
  {
    "ray-x/go.nvim",
    dependencies = {
      "ray-x/guihua.lua",
      "neovim/nvim-lspconfig",
      "nvim-treesitter/nvim-treesitter",
    },
    opts = {
      disable_defaults = true,
      diagnostic = false,
    },
    event = { "CmdlineEnter" },
    ft = { "go", "gomod" },
    -- Prevents Neovim from freezing on plugin installation/update.
    -- See: <https://github.com/ray-x/go.nvim/issues/433>
    build = function() require("go.install").update_all() end,
  },
```

**Comment by Uzaaft** [comment]
There is no difference between those two

**Comment by Uzaaft** [comment]
@nfort
Please fill out the issue template when providing an bug report, including what the error is, and the minimal configuration. Closing this since it wasn't provided.

**Comment by dontmindmexdd** [comment]
I've encountered this issue too, but I can elaborate further.

Right now, `disable_defaults` is being set to true, which purges all setting tables of go.nvim. The [documentation](https://github.com/ray-x/go.nvim?tab=readme-ov-file#configuration) states that if `disable_defaults` is set, you should manually configure all the settings. This manual configuration is not being done, which in turn causes go.nvim to error out on config. Overriding the `disable_defaults` flag to false fixes the issue for me.

<img width="845" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/26008526/ab105031-3a54-4147-8963-22237d2ac851">

**Comment by Uzaaft** [comment]
Honestly at this point, I'm more eager to just purge go.nvim
