### ISSUE TITLE
Add plugin vim-doge

### ISSUE THREAD

**Issue by SdKay** [AstroNvim/astrocommunity#1048]
### Is your feature related to a problem?

[vim-doge](https://github.com/kkoomen/vim-doge) is a vim documentation tool, have some difficulty to transfer its config to Astrovim. I also notice there is a demo for [neogen](https://github.com/danymat/neogen), I try change base on that but not working.

### Describe the new feature

Add a config demo for that?

**Comment by SdKay** [comment]
> There's no concept of config demo, its just plugin specs.

My misunderstanding🤣...Thanks for the excellent work. 

I have a advice: Add more config example and docs for transfering vim-based or neovim-based config to Astrovim config. 
Since Astrovim is an work out of the box, there maybe many nvim(or even vim) beginners choose Astrovim(like me) . When they google some solutions, most of results is based on vimrc or nvim config. So its often difficult for us to use them in the Astrovim config(based on lua).

**Comment by Uzaaft** [comment]
Thats to big of a scope for us to take on.
