### ISSUE TITLE
Add a spring-boot pack

### ISSUE THREAD

**Issue by Uzaaft** [AstroNvim/astrocommunity#1064]
### Describe the new feature

Right now, the current java pack doesn't support spring-boot. 
We should add this functionality in a seperate pack. 
https://github.com/JavaHello/spring-boot.nvim/tree/main is a candidate plugin.

**Comment by mehalter** [comment]
This is superceded by #1062

**Comment by nithin-mk** [comment]
Should this be reopened, as nvim-java is now a separate plugin?

**Comment by nithin-mk** [comment]
@mehalter Currently I have the Java pack installed. As per spring-boot.nvim's [README](https://github.com/JavaHello/spring-boot.nvim/blob/main/README_en.md), I've put
```lua
  {
    "JavaHello/spring-boot.nvim",
    ft = "java",
    dependencies = {
      "mfussenegger/nvim-jdtls",
    },
  }
```
in `~/.config/nvim/lua/plugins/user.lua`. After that I put
```lua
require('spring_boot').setup({})

local jdtls_config = {
  bundles = {}
}
-- Add spring-boot jdtls extension jar files
vim.list_extend(jdtls_config.bundles, require("spring_boot").java_extensions())
```
in `polish.lua`, but that didn't work. Any idea about where to add these lines?
