### ISSUE TITLE
Add rust crates completion in Cargo.toml

### ISSUE THREAD

**Issue by serzhiio** [AstroNvim/astrocommunity#1072]
### Describe the new feature

**Crate name completion**
Crate names in dependencies can be completed from searches on crates.io. 
This has to be enabled separately:

```
require("crates").setup {
    ...
    completion = {
        crates = {
            enabled = true -- disabled by default
            max_results = 8 -- The maximum number of search results to display
            min_chars = 3 -- The minimum number of charaters to type before completions begin appearing
        }
    }
}
```

[Link](https://github.com/Saecki/crates.nvim/wiki/Documentation-unstable#crate-name-completion)

**Comment by Uzaaft** [comment]
Feel free to open a PR @serzhiio

**Comment by Uzaaft** [comment]
@serzhiio I'd appreciate it if, in the future you also open a PR for small issues like this which you could've easily fixed. You know, to give back to the community :)

**Comment by serzhiio** [comment]
> @serzhiio I'd appreciate it if, in the future you also open a PR for small issues like this which you could've easily fixed. You know, to give back to the community :)

I was not sure about such small update PR bc it could be done using config override.

@mehalter many thx!

**Comment by mehalter** [comment]
if someone in the community doesn't like it, then they can open up a PR to change it
