### ISSUE TITLE
Why does noice-nvim require Tree-sitter with bash/markdown/etc?

### ISSUE THREAD

**Issue by Cretezy** [AstroNvim/astrocommunity#109]
Referring to https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/utility/noice-nvim/noice-nvim.lua#L3-L12 (perm: https://github.com/AstroNvim/astrocommunity/blob/2005cf25dd0281c4ee50f31ffc7e016c16670c48/lua/astrocommunity/utility/noice-nvim/noice-nvim.lua#L3-L12)

I see that it does use Tree-sitter for Markdown apparently (L19), but why is the other languages there?

**Comment by luxus** [comment]
u can get that information on the noice repo.

**Comment by Cretezy** [comment]
My bad, totally missed that part.
