### ISSUE TITLE
AstroNvim is broken after update today

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#1106]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

kitty

### Describe the bug

```
Failed to run `config` for astrocore

vim/keymap.lua:0: invalid key: name

# stacktrace:
  - vim/keymap.lua:0 _in_ **set**
  - /astrocore/lua/astrocore/init.lua:320 _in_ **set_mappings**
  - /astrocore/lua/astrocore/init.lua:409 _in_ **setup**
  - /AstroNvim/lua/astronvim/plugins/lspconfig.lua:19 _in_ **init**
  - lua/lazy_setup.lua:1
  - init.lua:18
```

### Steps to Reproduce

Just press as always:
<leader>pa

### Expected behavior

Update & Upgrade

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Uzaaft** [comment]
Can't reproduce with the minimal configuration provided.

**Comment by MrMic** [comment]
Compelled to roll back to a previous commit.
Every time there is an update/upgrade there is 
issues...
Do not be astonished if people switch to Helix or VS Code, 
because even if they update/upgrade, everything is working after 
that!

**Comment by Uzaaft** [comment]
@MrMic
1. Next time, please provide a repro.lua that works.
2. The bug should be fixed now, if my assumption that your bug is due to a change in which-key.
3. Please write better issues, so that we can help you more efficiently.
