### ISSUE TITLE
[transparent-nvim] Current recipe can not make tabline and statusline transparent.

### ISSUE THREAD

**Issue by mantle2048** [AstroNvim/astrocommunity#1124]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0 release

### Operating system/version

WSL2 Ubuntu20.04

### Terminal/GUI

Windows Terminal

### Describe the bug

 Current recipe can not make tabline and statusline transparent.

![image](https://github.com/user-attachments/assets/475207d5-ca35-4035-9f63-07fd69db74e1)

### Steps to Reproduce

Just use the default config of transparent-nvim provided in astrocommunity.
```lua
  { import = "astrocommunity.color.transparent-nvim"}
```

### Expected behavior

The tabline and statusline should be transparent.

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
  { import = "astrocommunity.color.transparent-nvim"},

}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
It can you should just configuration that yourself in your own user configuration. It doesn't always make sense in the statusline/tabline to make it transparent because of how separators are actually rendered as inverse characters. So it would be up to you to opt into something like that in your user configuration.
