### ISSUE TITLE
Laravel & Blade pack work but have issues

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#1126]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

kitty

### Describe the bug

- LARAVEL: Some completion & definition are missing (parse not the entire project? ).
- BLADE: Color syntax is missing => need to do: set filetype=html

### Steps to Reproduce

Start AstroNvim in a Laravel project

### Expected behavior

- Completion work like in VS Code
- Blade color syntax do not work

### Screenshots

![Capture d’écran du 2024-07-24 20-51-51](https://github.com/user-attachments/assets/2fb22d3b-cbca-4eb3-9b3b-c5962b7642de)
![Capture d’écran du 2024-07-24 20-49-35](https://github.com/user-attachments/assets/758fd828-0274-4650-adc4-01744ac303d5)
![Capture d’écran du 2024-07-24 20-57-05](https://github.com/user-attachments/assets/4d4a066b-1e08-47cd-9730-876fd6f80589)

### Additional Context

Otherwise, all seems to work as expected.

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by ALameLlama** [comment]
For blade syntax highlighting to work you'll need to manually create the tree sitter query files.

See the notes on https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/laravel

**Comment by ALameLlama** [comment]
I'm sorry the link in the notes is wrong, this should point to https://github.com/EmranMR/tree-sitter-blade/discussions/19#discussion-5400675

You'll need to manually add the query files

**Comment by MrMic** [comment]
And for the completion in Laravel, that is not correct?

**Comment by ALameLlama** [comment]
@MrMic how do you mean? The tree sitter queries are just for syntax highlighting. They shouldn't effect anything else.

**Comment by MrMic** [comment]
@ALameLlama  I know but my first issue was about completion (see the first 2 screenshots above).
And that is not fixed. The first screenshot is what VS Code provides (and it is OK) and the second 
is what AstroNvim shows (NOK).

**Comment by ALameLlama** [comment]
@MrMic I believe for Laravel methods like this [laravel ide helper](https://github.com/barryvdh/laravel-ide-helper) is what power this, try installing this and running `php artisan ide-helper:generate`.

If it's still complaining try to see if it does the same thing for `redirect(route('hello'))` or to_route('hello') since both of these should give the same result.

I'm not at my PC atm but I'll see if I get the same thing and see if there is something we can do it fix it on our side.

**Comment by ALameLlama** [comment]
I ended up having the same issue but the two other suggestions I gave don't show the same error.
![image](https://github.com/user-attachments/assets/588bf4fe-6b1a-462c-82cf-4741023e3105)

I also installed vs code with PHP Intelephense as the LSP and ran into the same issue where it wasn't detecting redirect()->route() as an option
![Code_bNWj4S4Ez2](https://github.com/user-attachments/assets/30400811-0c3a-4ce1-a4be-16c72248cca1)

I assume you'll have some extra plugin within VS code that is doing something extra to get this to work. When I put together the pack, I tried to find every nvim plugin I could to make things as close to PHPStorm/VS code but it's not perfect. if you find other plugins that make the Laravel experience better within nvim. I'm more than happy to look into it

**Comment by ALameLlama** [comment]
@MrMic Actually, the issue is with PHP Actor the LSP and it's because the redirect global function has a dynamic return type `* @return ($to is null ? \Illuminate\Routing\Redirector : \Illuminate\Http\RedirectResponse)`

This was fixed recently in PHP Actor itself https://github.com/phpactor/phpactor/issues/2700 and merged 4 days ago. They haven't done a release but once they do and you update it, the issue will be solved.

For now, if you want to keep that syntax doing `redirect(null)->route('something')` will work

**Comment by MrMic** [comment]
Thanks a lot, @ALameLlama  for the time you take to troubleshoot this.
I will wait for the update on the PHP Actor. I can work with VS Code in the 
meantime.
Maybe It will be worth not to close this issue too quickly... It may interests other Devs?

BTW, my VS Code has these laravel extensions installed:
- Laravel Blade Snippets
- Laravel Snippets
- Laravel Artisan
- Laravel Extra Intellisense (seems better than intellisense)
- Laravel Blade Formatter
- Laravel Blade Spacer
- Laravel Blade

And so far, all works like a charm 😁
