### ISSUE TITLE
cord-nvim's build script fails on windows

### ISSUE THREAD

**Issue by Std-Enigma** [AstroNvim/astrocommunity#1136]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0 release

### Operating system/version

Windows 11

### Terminal/GUI

neovide

### Describe the bug

This is error is probably caused by the fact that `/` paths aren't valid on windows cmd

### Steps to Reproduce

1. Open neovim on (wnidows)
2. run `:Lazy build cord.nvim`

### Expected behavior

Successful build.

### Additional Context

Here is the error:
```
[cord.nvim] Could not find the compiled dynamic library at: %LOCALAPPDATA%/nvim-data/lazy/cord.nvim/cord.dll. Please re-run the build script
```

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = vim.fn.stdpath "data" .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity", { import = "astrocommunity.media.cord-nvim" } },
}
```

**Comment by Uzaaft** [comment]
Do you get any output that shows you that the build command is failing?

**Comment by Uzaaft** [comment]
Your error message could be interpreted as  rust not being available, since the lib isn't available.

**Comment by Std-Enigma** [comment]
that would make sense but just checked the [cord.nvim](https://github.com/vyfor/cord.nvim) repo and it mentioned in the note the path should differ on windows machine I'll open a PR

**Comment by Uzaaft** [comment]
It doesn't say should. It says "you MAY need to use a backslash as the path seperator".
We should first make sure the issue is not your setup or missing requirements, before we do changes.

**Comment by Std-Enigma** [comment]
okay let me test a few things

**Comment by Std-Enigma** [comment]
`'.' is not recognized as an internal or external command, operable program or batch file.`
This is the error lazy showed as the build status, i dug a little bit further this script should generate two files which are `cord.dll.exp`and `cord.dll.lib` but when the path is specified as `./build` in plugin spec i get this error but when specified like `.\\build` this isn't the case

**Comment by Uzaaft** [comment]
Nice. I'd appreciate it if you included that into the initial bug report next time. :)
