### ISSUE TITLE
[multiple-cursors] <Leader>c clashes with 'Close buffer'

### ISSUE THREAD

**Issue by lorcap** [AstroNvim/astrocommunity#1138]
`<Leader>c` at [init.lua:25](https://github.com/AstroNvim/astrocommunity/blob/8661208c7b9a06551be04d104c5bdfd37031b19f/lua/astrocommunity/editing-support/multiple-cursors-nvim/init.lua#L25) conflicts with command 'Close buffer' (see [AstroNvim mappings](https://docs.astronvim.com/mappings)). I'd suggest `<Leader>m`.

**Comment by Uzaaft** [comment]
@lorcap  Next time please open a PR if you have a suggestion.
