### ISSUE TITLE
rust-tools hover action key bindings?

### ISSUE THREAD

**Issue by rohitisinhk** [AstroNvim/astrocommunity#114]
Where do we define the keybinding for rust-tool's hover actions?

local rt = require("rust-tools")
rt.setup({
  server = {
    on_attach = function(_, bufnr)
      -- Hover actions
      vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
      -- Code action groups
      vim.keymap.set("n", "<Leader>a", rt.code_action_group.code_action_group, { buffer = bufnr })
    end,
  },
})

**Comment by rohitisinhk** [comment]
This seem to have done the trick. Is there an easier way?


lua/user/lsp (c680ab3) [!] via 
❯ bat on_attach.lua
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: on_attach.lua
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ local rt = require("rust-tools")
   2   │
   3   │
   4   │ return function(client, bufnr)
   5   │       -- Hover actions
   6   │       vim.keymap.set("n", "<C-space>", rt.hover_actions.hover_actions, { buffer = bufnr })
   7   │       -- Code action groups
   8   │       vim.keymap.set("n", "<Leader>r", rt.code_action_group.code_action_group, { buffer = bufnr })
   9   │ end
───────┴────────────────────────────────

**Comment by Uzaaft** [comment]
Closing this. Please re-open if this is still an issue. Or visit the discord. :)
