### ISSUE TITLE
From the today update I got error with typescript files

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#1145]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

kitty

### Describe the bug

Error when open a .ts file
![Capture d’écran du 2024-08-07 09-43-38](https://github.com/user-attachments/assets/123e5875-dbea-4dd6-8c1e-4460b2c5196b)

### Steps to Reproduce

Open .ts file inside a project

### Expected behavior

no error as yesterday...

### Screenshots

see above

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Uzaaft** [comment]
There hasn't been an update for the last 24 hours. 

Not sure what this come from. Could be an issue upstream.

**Comment by Uzaaft** [comment]
Seems to work fine for me now. @MrMic

**Comment by MrMic** [comment]
Yep, for me too now.
What has been done?

**Comment by Uzaaft** [comment]
Don't know. Bug wasn't on our side.

**Comment by Uzaaft** [comment]
Just a heads up for when the issue arises next time. This wasn't the proper place to raise the issue. Treesitter would've been better.
