### ISSUE TITLE
molten-nvim does not work at all 😥

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#1170]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

kitty

### Describe the bug

The base command `:MoltenInit` is not found ...

The `molten-nvim`  in repo.lua does not work
![Capture d’écran du 2024-08-20 20-24-57](https://github.com/user-attachments/assets/3584c247-23a1-4ed8-8de0-bc8b7eb8a531)

The installation report bug:
![Capture d’écran du 2024-08-20 20-29-22](https://github.com/user-attachments/assets/5a5dfcad-5b1d-49f8-9999-b3d93b610bd7)

### Steps to Reproduce

Installation and normal use as explained in the original GitHub repo 
of molten

### Expected behavior

Initialize a python kernel before use.

`:checkhealth` is OK:

![Capture d’écran du 2024-08-20 20-34-58](https://github.com/user-attachments/assets/c1171074-b212-40ca-ac8e-ca7f184543bd)

### Screenshots

![Capture d’écran du 2024-08-20 20-32-03](https://github.com/user-attachments/assets/a95309be-6950-42a8-961b-880cd093aa23)

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	-- stylua: ignore
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
		lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
	{ "AstroNvim/AstroNvim", import = "astronvim.plugins" },
	{
		"AstroNvim/astrocommunity",
		{ import = "astrocommunity.code-runner.molten-nvim" },
	},

	-- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Uzaaft** [comment]
Issue with you setup. Read the molten docs. Not a bug.

**Comment by Uzaaft** [comment]
And read the error message as well.

**Comment by mehalter** [comment]
this was a bug in the plugin on AstroCommunity. Resolved in latest commit (bad @Uzaaft)

**Comment by MrMic** [comment]
I concur, it works now.
