### ISSUE TITLE
AstroNvim is broken as of today's update

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#1182]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

kitty

### Describe the bug

Start the app and get this notification!

![Capture d’écran du 2024-08-31 14-22-57](https://github.com/user-attachments/assets/038ac428-fe8f-40fa-81dc-de23cdd34d7e)

### Steps to Reproduce

see above and screenshot

### Expected behavior

normal start

### Screenshots

![Capture d’écran du 2024-08-31 14-22-57](https://github.com/user-attachments/assets/70c1a00a-2863-4d32-a2ed-f6fa4f3c56fa)

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Std-Enigma** [comment]
Do you have any custom key mappings for notify.nvim?

**Comment by MrMic** [comment]
No.

![Capture d’écran du 2024-09-01 11-07-16](https://github.com/user-attachments/assets/039d1b79-a944-4703-9c87-946d46268e5c)

**Comment by Std-Enigma** [comment]
I can't reproduce this issue

**Comment by MrMic** [comment]
It is the update of yesterday.
Roll back!

**Comment by MrMic** [comment]
Latest update of the error:
- May be with Astrocore 1.8.0?

![Capture d’écran du 2024-09-01 19-54-53](https://github.com/user-attachments/assets/71478ae7-eeae-489e-963c-780f7328f4b8)

**Comment by MrMic** [comment]
Clean all  ~/.local/{state,share} and ~/.cahce directories but still 
got the issue, which prevent me to use AstroNvim at all!  😥

![Capture d’écran du 2024-09-02 20-26-04](https://github.com/user-attachments/assets/d9c94863-9c7d-4d26-86aa-de9c4398650a)

Tha last Astrocore update seems to have break something...

**Comment by ALameLlama** [comment]
I can't recreate this using the minimal configuration.

**Comment by MrMic** [comment]
Because the update of Astrocore has broken a plugin integration...

**Comment by MrMic** [comment]
I was compelled to reinstall all... Damn!
