### ISSUE TITLE
sql pack error

### ISSUE THREAD

**Issue by jaycoolslm** [AstroNvim/astrocommunity#1197]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0

### Operating system/version

macOS 13.5

### Terminal/GUI

ITerm2

### Describe the bug

Trying to install `sql` community pack with 

  { import = "astrocommunity.pack.sql" },

[mason-lspconfig.nvim] failed to install sqls. Installation logs are available in :Mason and :MasonLog
[ERROR Sat  7 Sep 07:49:48 2024] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=sqls) error=spawn: go failed with exit code - and signal -. go is not executable

### Steps to Reproduce

add  { import = "astrocommunity.pack.sql" },
to community 

### Expected behavior

All sql deps should install correctly

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },
  { import = "astrocommunity.pack.sql" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Uzaaft** [comment]
You need go installed to install the lsp

**Comment by jaycoolslm** [comment]
Yup, this resolved it. thanks @Uzaaft
