### ISSUE TITLE
clear chatgpt chat history

### ISSUE THREAD

**Issue by jaycoolslm** [AstroNvim/astrocommunity#1201]
### Is your feature related to a problem?

Unable to clear ChatGPT plugin chat history

### Describe the new feature

How am I able to clear the chatgtpt plugin history 

### Additional context

[spacebar] + G + c

**Comment by Uzaaft** [comment]
I'm not sure if this is something we can do, since the plugin doesnt seem to support this @jaycoolslm

**Comment by Uzaaft** [comment]
Please open a PR upstream.
