### ISSUE TITLE
neotest should respect when icons_enabled is false

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/astrocommunity#1207]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

doesn't matter

### Operating system/version

does not matter

### Terminal/GUI

does not matter

### Describe the bug

[neotest](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/test/neotest/init.lua) forces icons but the user may have chosen to [disable them](https://docs.astronvim.com/recipes/icons/#disable-icons)

### Steps to Reproduce

use the community pack

### Expected behavior

pack should respect the higher level `icon_enabled` boolean linked above.

### Minimal configuration

```Lua
-- not required
```

**Comment by Uzaaft** [comment]
Minimal configuration is required. Please fill it in @windowsrefund

**Comment by Uzaaft** [comment]
We require a minimal configuration. You'll have to fill it in.

**Comment by Uzaaft** [comment]
We're literally asking you to do the bare minimum.

**Comment by windowsrefund** [comment]
and I am LITERALLY (I know you kids love to use this word to overly sensationalize your communications) telling you the information provided is enough to act on. TBH, I don't care if this gets fixed or not. Feel free to close it.

**Comment by windowsrefund** [comment]
literally! :+1:

**Comment by luxus** [comment]
https://github.com/AstroNvim/astrocommunity/blob/283ca3c0b1b06216860475834501628482e7c3c5/lua/astrocommunity/icon/mini-icons/init.lua#L3-L5
a check like this could fix the issue
