### ISSUE TITLE
Leap cursor visibility workaround makes cursor invisible on nvim 0.10+

### ISSUE THREAD

**Issue by expipiplus1** [AstroNvim/astrocommunity#1219]
https://github.com/AstroNvim/astrocommunity/blob/f4a19c410fdcf778d44a8b9ece55e529df7a0274/lua/astrocommunity/motion/leap-nvim/init.lua#L9-L25

These should be conditional on nvim < 0.10

**Comment by ctretyak** [comment]
I can approve. Disabling this repairs nvim 0.10 cursor on searching with labels

**Comment by Uzaaft** [comment]
Feel free to open a PR.
