### ISSUE TITLE
Haskell Dependency Deprecated

### ISSUE THREAD

**Issue by lcpichette** [AstroNvim/astrocommunity#1229]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.1

### Operating system/version

macOS 15.1

### Terminal/GUI

Wezterm

### Describe the bug

Haskell is reporting that lua@5.1 is required for one of the Haskell plugins that the haskell community package leverages.

However, it seems that I'm unable to downgrade to 5.1 via homebrew. This is likely for a good reason.
```
 brew install lua@5.1
Error: lua@5.1 has been disabled because it is deprecated upstream! It was disabled on 2024-02-16.
```

I'm not sure of the specifics, but thought I'd at least bring this to light so that those who know more can determine if this is worth paying any note to.

### Steps to Reproduce

1. Install lua via brew
2. Install luarocks via brew
3. Add the luarocks plugin https://github.com/vhyrro/luarocks.nvim
4. Install Astronvim
5. Add the haskell plugin

### Expected behavior

After step 5, Mason should install necessary LSPs, formatters, etc. for Haskell. 

However, this is the step that fails, and it reports that the haskell packages require lua 5.1.

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },
  { "AstroNvim/haskell" },
  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by luxus** [comment]
should this not report upstream?

**Comment by Uzaaft** [comment]
The `repro.lua` is invalid.
