### ISSUE TITLE
use okuuva/auto-save.nvim instead of Pocco81/auto-save.nvim

### ISSUE THREAD

**Issue by srghma** [AstroNvim/astrocommunity#1233]
### Is your feature related to a problem?

not maintained

https://github.com/AstroNvim/astrocommunity/blob/c87c236dce71107637d2fc30e9dcc116d5d60097/lua/astrocommunity/editing-support/auto-save-nvim/init.lua#L2

### Describe the new feature

https://github.com/okuuva/auto-save.nvim is more maintained

### Additional context

use https://github.com/okuuva/auto-save.nvim?tab=readme-ov-file#%EF%B8%8F--events--callbacks 

instead of before_saving, after_saving?

but I cannot test - dont use formatters and `save on insertLeave`

my config is 

```
  {
    "okuuva/auto-save.nvim",
    event = { "User AstroFile", "InsertEnter" },
    opts = {
      trigger_events = { -- See :h events
        immediate_save = { 'BufLeave', 'TabLeave', 'FocusLost', 'VimLeavePre' }, -- vim events that trigger an immediate save
        -- defer_save = { "InsertLeave", "TextChanged" }, -- vim events that trigger a deferred save (saves after `debounce_delay`)
        defer_save = { }, -- vim events that trigger a deferred save (saves after `debounce_delay`)
        cancel_defered_save = { "InsertEnter" }, -- vim events that cancel a pending deferred save
      },
    },
  },
```

**Comment by ALameLlama** [comment]
I just had a quick test, and I don't think the current callback stuff even works. I have lua enabled with auto formatting, I created a bunch of extra spaces and let it autosave and it will remove the extra spaces. If I manually disable auto formatting for my buffer and then do the same thing, it will keep the spaces.

Are we happy with me just updating the repo and removing the callback stuff? or should I look into why this might be happening?

**Comment by ALameLlama** [comment]
Figured it out it's because we're looking at autoformat_enabled while it should be autoformat
