### ISSUE TITLE
Julia pack, unicode autocompletion doesn't remove initial backslash

### ISSUE THREAD

**Issue by emgi13** [AstroNvim/astrocommunity#1236]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Ubuntu WSL2

### Terminal/GUI

Windows Terminal

### Describe the bug

When trying to autocomplete a symbol like `\in` to `∈`,  the autocomplete turns it into `\∈` instead, and the backslash isn't compatible with Julia and has to be manually removed

### Steps to Reproduce

- Launch nvim with repro.lua
- open a file with .jl ext
- type `\` to trigger autocomplete
- type `in` or `neq` for the relevant symbol
- press enter to accept

### Expected behavior

`\in` should turn to `∈` but instead turns to `\∈`
`\neq` should turn to `≠` but instead turns to `\≠`

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	-- stylua: ignore
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable",
		lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
	{ "AstroNvim/AstroNvim", import = "astronvim.plugins" },
	{ "AstroNvim/astrocommunity" },
	{ import = "astrocommunity.pack.julia" },

	-- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Uzaaft** [comment]
pinging  @mehalter in case you can fix this.
