### ISSUE TITLE
nvchad-ui seems broken

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#1247]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

kitty

### Describe the bug

Installation of the pack:
```
- nvchad-ui
```
 report issue(s)

![Capture d’écran du 2024-10-18 08-41-14](https://github.com/user-attachments/assets/ad1f0f62-adfe-4581-ab76-5442a90a1bb7)

### Steps to Reproduce

see above

### Expected behavior

no issue at installation

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by Uzaaft** [comment]
Have you followed their docs?

**Comment by MrMic** [comment]
The package does not mention any tweaks or tunes to make...
Moreover, the shortcut `<leader>bb` does not anymore too, just saying...

**Comment by Uzaaft** [comment]
nvchad-ui docs mentions that you need to add in a config file.

**Comment by Uzaaft** [comment]
Got to ask, are your packages up to date?

**Comment by MrMic** [comment]
yes! update twice per day (morning & evening...)

**Comment by mehalter** [comment]
`repro.lua` does not reproduce the bug. Please follow the provided issue instructions when opening an issue please. If you update the issue body I can reopen this :)

**Comment by mehalter** [comment]
Tested with the following and it does not replicate the error:

```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
	{ "AstroNvim/AstroNvim", import = "astronvim.plugins" },
	{ "AstroNvim/astrocommunity" },
	{ import = "astrocommunity.pack.nvchad-ui" },

	-- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

Also `nvconfig` is _not_ the configuration file. That is a module in NvChad/ui. It is not expected for the user to make that file (even if they are using NvChad. The way the pack works is that the `opts` table for `NvChad/ui` is the same as the `nvchadrc` file which is the nvchad configuration file

**Comment by MrMic** [comment]
@mehalter I have no issue too with your repro.lua but when I delete the pack in 
my `community.lua` file and enable it again, I got an error! (see image).

![Capture d’écran du 2024-10-19 18-42-41](https://github.com/user-attachments/assets/bef58fbf-2f82-4126-b557-ef11f8c41108)

Am I supposed to create a `nvchadrc` file and if so, where?  Or am I supposed  to tune
the `opts` in `"NvChad/ui"` by appending to it?

**Comment by mehalter** [comment]
The error you just shared has nothing to do with nvchadrc. You don't need to make the file. You can adjust the `opts` as you desire 

The error you just shared is clearly a bug in NvChad/ui's code. It is improperly error handling buffer processing. It's completely unrelated to the pack. It's because the lazy window closes itself and NvChad just isn't handling that case properly

**Comment by MrMic** [comment]
@mehalter Do you know where is gone the menu for "Buffer"? I was using 
it with `<Leader>b, ' which has disappeared! And when I try to create it with 
nvchad/ui and tabufline, it is not created. But with `<Leader>X` it appears...
Any explanations will be appreciated.

**Comment by MrMic** [comment]
Ok, got that. But even though the buffer has disappeared I cannot write 
it again with the shortcut `<Leader>b`. It is not displayed. Is it rewritten by 
another plugin or implementation? Something seems to prevent me to use 
this shortcut. And I do not find what...

**Comment by mehalter** [comment]
I don't know what you mean or what that message is saying, sorry. Can you clarify

**Comment by MrMic** [comment]
I am trying to affect the "Buffer" menu as it was with `<Leader>b` but it 
does not work. Nothing appears! but with `<Leader>X` it does.
What prevents me from using the "Buffer" menu which was initially 
trigger with `<Leader>b`.

**Comment by mehalter** [comment]
Are you saying that the `<Leader>b` menu is gone when you enable the NvChad ui pack?

**Comment by MrMic** [comment]
YES!!! 😅 You have understood.

**Comment by mehalter** [comment]
Ok, so what I said before is that that menu is a bunch of functionality implemented specifically by AstroNvim for their tabline. It has been removed as you are no longer using our tabline. It's up to the tabline plugin you are using to add those features

**Comment by MrMic** [comment]
OK, but why can't I use `<Leader>b` to create a menu. It is is available after all...
On the contrary it is possible with `<Leader>X`

**Comment by mehalter** [comment]
You can build a new menu in your configuration

**Comment by MrMic** [comment]
Yes, as I told you I created it with `<Leader>X` but why is it not
appearing when I use `<Leader>b` ?

**Comment by mehalter** [comment]
You must be making a mistake. I'm sorry you are having troubles. I would highly recommend checking out the AstroNvim discord server as the is a great community of years who can help you learn configuration
