### ISSUE TITLE
Disabled formating with enabled autosave plugin 

### ISSUE THREAD

**Issue by wert2all** [AstroNvim/astrocommunity#1262]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.2

### Operating system/version

arch

### Terminal/GUI

kitty

### Describe the bug

caused by #511 

Formating buffer does not work (disabled ) if `"astrocommunity.pack.angular"` and `"astrocommunity.editing-support.auto-save-nvim"` is enabled (maybe on go pack too)

### Steps to Reproduce

1. install pure astro nvim
2. enable `astrocommunity.pack.angular` end `astrocommunity.editing-support.auto-save-nvim` on `community.lua` file
3. open some template file of angular project and try to insert something like new empty lines
4. go to normal move
5. format bugger does not executed automatically

### Expected behavior

buffer should be forma

**Comment by ALameLlama** [comment]
I won't be at a computer for the next few days to test this, but the way I understood these auto save hooks is It'll disable formatting during any auto save and then restore the settings. So if you want to format it, you'll need to manually save or use `:format`

**Comment by wert2all** [comment]
> So if you want to format it, you'll need to manually save or use :format

weird behavior as for me - or autosave or autoformat :) 
Nvim should autoformat and autosave at same time for my opinion.

I check it again:

1. open html document
2. `:w`

:white_check_mark: format and save

1. open html document
2. switch to i-mode
3. add some spaces
4. back to `normal`

:x: no format 

1. open html document
2. `:w`
3. :white_check_mark: format and save
4. switch to i-mode
5. add some spaces
6. back to `normal`
7. :x: no format

**Comment by ALameLlama** [comment]
I believe we added this to prevent it from formatting the code unexpectedly, e.g, you leave insert mode to copy and paste or try to select something in visual mode and than it formats in the middle you trying to do something else moving the code around

If you really want to avoid using these hooks it might be easier to either install the plugin directly 
```
return {
  "okuuva/auto-save.nvim",
  event = { "User AstroFile", "InsertEnter" },
  opts = {},
}
```
or disable the auto commands doing something like
```
  { import = "astrocommunity.editing-support.auto-save-nvim" },
  {
    "AstroNvim/astrocore",
    opts = {
      autocmds = {
        autoformat_toggle = {},
      },
    },
  },
```

**Comment by ALameLlama** [comment]
when testing this, I also noticed that the buffer setting wasn't getting restored correctly. so if you went into insert mode, did something, went to normal mode and then `:w` it wouldn't format even if you had it enabled before. but I think this is a different issue then what you are describing

https://github.com/AstroNvim/astrocommunity/pull/1265

**Comment by wert2all** [comment]
> I believe we added this to prevent it from formatting the code unexpectedly, e.g, you leave insert mode to copy and paste or try to select something in visual mode and than it formats in the middle you trying to do something else moving the code around

make sense...

ps. #1265 will fix this issue as for me, closing

**Comment by xino1010** [comment]
Hi there!

I have this configuration on my AstroNvim.

File `~/.config/nvim/lua/plugins/auto-save.lua`.

```javascript
return {
  {
    "okuuva/auto-save.nvim",
    -- version = '^1.0.0', -- see https://devhints.io/semver, alternatively use '*' to use the latest tagged release
    cmd = "ASToggle", -- optional for lazy loading on command
    event = { "InsertLeave", "TextChanged" }, -- optional for lazy loading on trigger events
    opts = {
      -- your config goes here
      -- or just leave it empty :)
      trigger_events = {
        defer_save = { "InsertLeave", "TextChanged", "TextChangedI" },
      },
      debounce_delay = 2500,
    },
  },
}
```

File `~/.config/nvim/lua/community.lua`

```javascript
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
  -- import/override with your plugins folder
  ...
  { import = "astrocommunity.editing-support.auto-save-nvim" },
}
```

It works perfectly (save without leaving the editor after 2500ms) but I noticed the file is not formatted automatically, I need to execute `:w` or `leader lf` myself.

is it feasible to get what i want?

Thank you

**Comment by ALameLlama** [comment]
https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/editing-support/auto-save-nvim/init.lua#L8-L45

We have this logic here to disable formatting with autosave to prevent it from shifting while you're using it, I believe you can disable the auto command like  I showed in the second example https://github.com/AstroNvim/astrocommunity/issues/1262#issuecomment-2466548640

**Comment by xino1010** [comment]
Does not work, file is saved after 2500ms but not formatted

```javascript
return {
  {
    "okuuva/auto-save.nvim",
    -- version = '^1.0.0', -- see https://devhints.io/semver, alternatively use '*' to use the latest tagged release
    cmd = "ASToggle", -- optional for lazy loading on command
    event = { "InsertLeave", "TextChanged" }, -- optional for lazy loading on trigger events
    opts = {
      -- your config goes here
      -- or just leave it empty :)
      trigger_events = {
        defer_save = { "InsertLeave", "TextChanged", "TextChangedI" },
      },
      debounce_delay = 2500,
      autocmds = {
        autoformat_toggle = {},
      },
    },
  },
}
```

**Comment by ALameLlama** [comment]
the autocmd is on Astrocore and not on the plugin directly.
```
 {
    "AstroNvim/astrocore",
    opts = {
      autocmds = {
        autoformat_toggle = {},
      },
    },
  },
  ```

**Comment by xino1010** [comment]
This is exactly I was looking for, many thanks!

**Comment by xino1010** [comment]
@ALameLlama sorry to come back again regarding this question.

i'm using [auto-save](https://github.com/okuuva/auto-save.nvim) that save the files after a delay and immediately astrocore formats the code, could it be possible to execute autoformat_toggle as well with a delay?

summary: delay in auto-save and delay in autoformat_toggle.

```js
return {
  {
    "okuuva/auto-save.nvim",
    -- version = '^1.0.0', -- see https://devhints.io/semver, alternatively use '*' to use the latest tagged release
    cmd = "ASToggle", -- optional for lazy loading on command
    event = { "InsertLeave", "TextChanged" }, -- optional for lazy loading on trigger events
    opts = {
      -- your config goes here
      -- or just leave it empty :)
      trigger_events = {
        defer_save = { "InsertLeave", "TextChanged", "TextChangedI" },
      },
      debounce_delay = 3000,
   },
  },
}

{
    "AstroNvim/astrocore",
    opts = {
      autocmds = {
       -- Add delay here
        autoformat_toggle = {},
      },
    },
  }

**Comment by ALameLlama** [comment]
If I'm understanding you correctly, you want to have the debounce save and then another debounce on the format afterwards?

This is the [autocmd](https://github.com/AstroNvim/AstroNvim/blob/9417da143b971e65b159089c3de5a0ee37edb1fd/lua/astronvim/plugins/_astrolsp_autocmds.lua#L61-L76) that handles the format, in the plugin [autocmd](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/editing-support/auto-save-nvim/init.lua#L10-L44) we just toggle this on/off.

but since it's listening too BufWritePre, I don't think this is the best idea to add some sort of debounce logic without causing other weird effects.

The only think that comes to mind would be to disable [BufWritePre autocmd](https://github.com/AstroNvim/AstroNvim/blob/9417da143b971e65b159089c3de5a0ee37edb1fd/lua/astronvim/plugins/_astrolsp_autocmds.lua#L61-L76) and then create your own [AutoSaveWritePost](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/editing-support/auto-save-nvim/init.lua#L32-L44) event from the plugin with your own debounce logic similar to how we have an event to re-enable the auto format setting but instead fire off the format command https://neovim.io/doc/user/lsp.html#vim.lsp.buf.format()
