### ISSUE TITLE
blink-cmp crashed 

### ISSUE THREAD

**Issue by nicholasxjy** [AstroNvim/astrocommunity#1263]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.0 release

### Operating system/version

macOS 11.5

### Terminal/GUI

wezterm

### Describe the bug

hi,  it seems lazydev.nvim was locked by v1.8.0 and this version not support blink-cmp yet
It crashed when using the new blink-cmp plugin

### Steps to Reproduce

```lua
{  
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.completion.blink-cmp" },
  { import = "astrocommunity.neovim-lua-development.lazydev-nvim" },
}
```

### Expected behavior

blink-cmp should not crash

### Screenshots

<img width="2489" alt="SCR-20241108-tigk" src="https://github.com/user-attachments/assets/e41f55fd-71a2-4530-82a3-b749624b82ad">

### Additional Context

It'll work if we update it forcely

```lua
{
    "folke/lazydev.nvim",
    version = false,
}
```

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
{  
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.completion.blink-cmp" },
  { import = "astrocommunity.neovim-lua-development.lazydev-nvim" },
}
```

**Comment by Uzaaft** [comment]
You can unpin lazydev.nvim.

**Comment by Uzaaft** [comment]
This is not a bug in astro. We cant guarantee that plugins are compatible with each other.
