### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by danielerosa** [AstroNvim/astrocommunity#1276]
### Is your feature related to a problem?

Yes, I cannot figure out how to setup custom format options in "astrolsp.lua"

### Describe the new feature

I would like to format my python files on save using: `black --line-length 79` and `isort --multi-line 3 --profile black`

**Comment by Uzaaft** [comment]
@danielerosa are you using the community pack?

**Comment by danielerosa** [comment]
```
❯ grep -ri community *
lazy-lock.json:  "astrocommunity": { "branch": "main", "commit": "6166e840d19b0f6665c8e02c76cba500fa4179b0" },
lua/community.lua:-- AstroCommunity: import any community modules here
lua/community.lua:  "AstroNvim/astrocommunity",
lua/community.lua:  { import = "astrocommunity.pack.lua" },
lua/lazy_setup.lua:  { import = "community" },
```

**Comment by Uzaaft** [comment]
that was not very helpful @danielerosa .

Use the community back to get format on save with black. This is a user error, but a bug.

**Comment by Uzaaft** [comment]
@danielerosa These issues are not for general help. Use either the discord or the discussions.

**Comment by danielerosa** [comment]
Ty. I put it here because you provide no example of a custom format command but you say it's possible. I though you wanted to improve your documentation.

**Comment by Uzaaft** [comment]
> Ty. I put it here because you provide no example of a custom format command but you say it's possible. I though you wanted to improve your documentation.

Thats the documentation of astronvim you are talking about. 
https://docs.astronvim.com/

**Comment by danielerosa** [comment]
Either there is an example and you point me to it or I am also able to find the ballpark docs.

**Comment by Uzaaft** [comment]
https://docs.astronvim.com/recipes/advanced_lsp
