### ISSUE TITLE
[Neo-tree WARN] Error rendering component icon: .../astrocommunity/lua/astrocommunity/pack/ansible/init.lua:7: couldn't parse regex: Vim:E55: Unmatched )

### ISSUE THREAD

**Issue by wert2all** [AstroNvim/astrocommunity#1283]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.2

### Operating system/version

opensuse

### Terminal/GUI

kitty

### Describe the bug

Warning on open neotree window
Caused by #1280

### Steps to Reproduce

1. Open neotree window

### Expected behavior

no warnings

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by hit0ri** [comment]
I think an extra `\\` in front of `vars` introduced in commit c5e7f6a76e7addf90f3b08d37eef2feb88557267 is causing this

**Comment by wert2all** [comment]
> I think an extra `\\` in front of [`vars`](https://github.com/AstroNvim/astrocommunity/blob/c5e7f6a76e7addf90f3b08d37eef2feb88557267/lua/astrocommunity/pack/ansible/init.lua#L7) introduced in commit [c5e7f6a](https://github.com/AstroNvim/astrocommunity/commit/c5e7f6a76e7addf90f3b08d37eef2feb88557267) is causing this

 looks like you're right

**Comment by YouSysAdmin** [comment]
Same else problem

Please tell me how to pin the version, add a "version" or/and "commit," it isn't helpful, it always gets the latest commit from the main branch

**Comment by wert2all** [comment]
@YouSysAdmin  just relax and wait for #1284 merge :)

**Comment by YouSysAdmin** [comment]
@wert2all this is for the future, version pinning in the community.lua config doesn't work for me.
So I'm wondering where I don't understand something or if it is just a feature :)

**Comment by wert2all** [comment]
> @wert2all this is for the future, version pinning in the community.lua config doesn't work for me. So I'm wondering where I don't understand something or if it is just a feature :)

i have no clue. You could remove `import ...` from `community.lua` and will add a new plugin with #1284 content ( https://github.com/AstroNvim/astrocommunity/blob/cf7a7ae0e92bf09f5f7d710113fcad794d3e3b77/lua/astrocommunity/pack/ansible/init.lua)

ps. якщо у вас не вийде, то можете мені написати в діскорді astriNvim'а.

**Comment by AlePini** [comment]
> Same else problem
> 
> Please tell me how to pin a version, add a "version" or/and "commit," it isn't helpful, it always gets the latest commit from the main branch

@YouSysAdmin I found a way to pin the plugin version, but not the single pack. Since `astrocommunity` is a plugin, you can follow the documentation at [lazy.folke.io](https://lazy.folke.io/spec) and edit `community.lua` like this:

```lua
@type LazySpec
return {
  {
    "AstroNvim/astrocommunity",
    commit = "cf7a7ae0e92bf09f5f7d710113fcad794d3e3b77"
  },
  { import = "astrocommunity.pack.ansible" }
}
```

**Comment by YouSysAdmin** [comment]
Hi @AlePini @wert2all
Thnx, it's work
I realized my mistake, I forgot about the bracket

```
return {
  {
    "AstroNvim/astrocommunity",
    commit = "cf7a7ae0e92bf09f5f7d710113fcad794d3e3b77"
  { import = "astrocommunity.pack.ansible" }
}
```

**Comment by JuliusLongmind** [comment]
Hi!

If I use the following syntax the error is gone:

`local path_regex = vim.regex "ansible\\|group_vars\\|handlers\\|host_vars\\|playbooks\\|roles\\|\\vars\\|tasks"`
