### ISSUE TITLE
'astrocommunity.pack.ansible' leaving defunct 'ansible-lint' processes

### ISSUE THREAD

**Issue by dutrajulio** [AstroNvim/astrocommunity#1286]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

Archlinux

### Terminal/GUI

alacritty

### Describe the bug

Each opened Ansible YAML file results in one or more 'ansible-lint' defunct processes.

### Steps to Reproduce

1. Open an Ansible YAML file
2. Watch to 'ansible-lint' processes
3. Wait and see some of these processes turns into 'defunct' ones

### Expected behavior

After "check" the Ansible YAML files, the 'ansible-lint' processes needs to terminate correctly without turn into 'defunct' processes.

### Screenshots

![Screenshot From 2024-12-12 13-09-06](https://github.com/user-attachments/assets/2f3d81e0-1a24-4664-a1ec-5078ee7e2996)

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity", import = "astrocommunity.pack.ansible" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by mehalter** [comment]
This would be a bug in [none-ls](https://github.com/nvimtools/none-ls.nvim) since they are the ones who manage the `ansible-lint` process
