### ISSUE TITLE
Update copilotchat-nvim to version 3

### ISSUE THREAD

**Issue by azdanov** [AstroNvim/astrocommunity#1291]
### Is your feature related to a problem?

At the moment the copilotchat-nvim is at version 2: https://github.com/AstroNvim/astrocommunity/blob/f401d9b0b5a4e019c5d32f3d4932136a4ca30505/lua/astrocommunity/editing-support/copilotchat-nvim/init.lua#L4

### Describe the new feature

It would be nice to update it to version 3, since it adds many additional features and improvements.

**Comment by ALameLlama** [comment]
I'll see what they've changed
