### ISSUE TITLE
location of config file

### ISSUE THREAD

**Issue by mvolkmann** [AstroNvim/astrocommunity#134]
The setup instructions say "Add the following to your plugins configuration, either in your user/init.lua file or in a file in user/plugins/ folder such as user/plugins/community.lua." I'm somewhat new to AstroNvim. It is not clear to me where the `user` directory belongs. Should it be in `~/.config/nvim` or `~/.config/nvim/lua` or `~/.config/nvim/lua/plugins`?

**Comment by luxus** [comment]
i would recommend to read the readme
https://astronvim.com/Configuration/manage_user_config
