### ISSUE TITLE
Add tabnine

### ISSUE THREAD

**Issue by proline** [AstroNvim/astrocommunity#137]
### Is your feature related to a problem?

The good point with Astrovim is you can have a full ide easily but if you don't know to much of lua, it is too difficult to implement it. 

### Describe the new feature

Tabnine is a useful tool to develop

**Comment by mehalter** [comment]
@proline this is out of the scope of what should be included in the base installation of AstroNvim. I have transfered this request to Astrocommunity and marked it as help wanted so a community member can maybe add it to the community repository. You can also join the AstroNvim Discord and ask questions there as many users are using things like Tabnine.

**Comment by luxus** [comment]
looks like not much interest.. i will close it for now, people can make a new issue or commenting here and we can reopen it.

**Comment by KyleKing** [comment]
FWIW, I think something like this might be all you need to add to `user.lua`:

```lua
  {
    "codota/tabnine-nvim",
    config = function()
      require("tabnine").setup {
        disable_auto_comment = true,
        accept_keymap = "<Tab>",
        debounce_ms = 300,
        suggestion_color = { gui = "#808080", cterm = 244 },
      }
    end,
  },
```

**Comment by mehalter** [comment]
Cool thanks for the recommendation @KyleKing ! I made a PR for this. Next time, it would be awesome if you wanted to contribute a PR to the community repo since this is only led and developed by users.

**Comment by KyleKing** [comment]
Turns out that my configuration didn't actually work 😓. The official TabNine plugin is still in alpha (https://www.tabnine.com/install/neovim), so it might be too early to make it part of the repo

There is an alternative one that I'm testing out: https://github.com/tzachar/cmp-tabnine

I would be happy to open a PR once I get a better handle on the configuration!

**Comment by mehalter** [comment]
That's alright! Still good to have any and all plugins installable through AstroCommunity :)

**Comment by mehalter** [comment]
If you are curious @KyleKing I updated the PR with a working version and bound the accept key to `<C-e>` to not conflict with `nvim-cmp`

**Comment by mehalter** [comment]
Also when you get a good configuration for `cmp-tabnine` that would also be great to contribute to AstroCommunity as well :)

**Comment by KyleKing** [comment]
Thanks!

I'm not getting completions with the AstroCommunity plugin, but login seems to work. I'll followup after work

I made progress, but couldn't get `TabNine` to be recognized by `cmp` when configuring `cmp-tabnine` like this. I'm not sure what was missing, but I'll leave this here in case it helps someone else:

```lua
{
  -- https://github.com/tzachar/cmp-tabnine#setup
  "tzachar/cmp-tabnine",
  event = "UIEnter", -- Should be InsertEnter
  build = "./install.sh",
  dependencies = "hrsh7th/nvim-cmp",
  config = function()
    local tabnine = require "cmp_tabnine.config"
    tabnine:setup {
      -- max_lines = 1000,
      -- max_num_results = 20,
      -- sort = true,
      -- run_on_every_keystroke = true,
      -- snippet_placeholder = "..",
      show_prediction_strength = true,
    }
  end,
},
-- Add more sources from: https://astronvim.com/Recipes/cmp#add-more-sources
{
  "hrsh7th/nvim-cmp",
  dependencies = {
    "tzachar/cmp-tabnine",
  },
  -- override the options table that is used in the `require("cmp").setup()` call
  opts = function(_, opts)
    local cmp = require "cmp"
    opts.sources = cmp.config.sources {
      { name = "TabNine", priority = 1001 },
    }
    return opts
  end,
},
```
