### ISSUE TITLE
Include endwise plugin for treesitter

### ISSUE THREAD

**Issue by goetzc** [AstroNvim/astrocommunity#155]
This plugin is useful to add the closing word in different languages, such as Lua or Ruby.

Check the repository for a video and more information:
https://github.com/RRethy/nvim-treesitter-endwise

You can try it using:
```lua
return {
  {
    "RRethy/nvim-treesitter-endwise",
    event = "VeryLazy",
    config = function()
      require('nvim-treesitter.configs').setup {
        endwise = {
          enable = true
        }
      }
    end
  }
}
```

**Comment by Uzaaft** [comment]
Feel free to open up a PR. :) This is a community driven repo, so if its anything you use that you might think that the community needs then feel free to open a PR with that feature.
