### ISSUE TITLE
Update README files for packs

### ISSUE THREAD

**Issue by sjcobb2022** [AstroNvim/astrocommunity#183]
Recently there have been a few issues regarding caveats with certain packs. Notably #179 and #101.

I think that it would be a good idea to require / request more documentation and examples in the README when adding packs.

This is just a suggestion and isn't necessary, but it may help newer users.

**Comment by luxus** [comment]
yeah we had a lot of ideas in the same directions, but this means rewriting the guidelines and extending all existing readmes.

**Comment by luxus** [comment]
with some of the new functions we have now we can cover many cases
