### ISSUE TITLE
Update colorscheme readme

### ISSUE THREAD

**Issue by dsisnero** [AstroNvim/astrocommunity#188]
I added some colorschemes in my community.lua file and they are installed but none show up when I telescope colorschemes or
run :colorschemes and tab through them.  Do they need to call setup or anything?

**Comment by TheSast** [comment]
Unfortunately you can't go through them with telescope because they are not loaded yet.
If you really wish to have this ability you can load the colorschemes non-lazily `{ 'guy/theme.nvim', lazy = false }` but that would increase your startup-time.

**Comment by Uzaaft** [comment]
I’m just going to go ahead and close this. Please read the lazy docs to see how you should add colorschemes.
