### ISSUE TITLE
astrocommunity.pack.python not working as intended with venv

### ISSUE THREAD

**Issue by Balssh** [AstroNvim/astrocommunity#196]
Hi, I've been playing around with configuring Astrovim and since I'm still learning nvim/lua I wanted to use the python pack provided by astrocommunity. However, even though I activated the VirtualEnv in the shell before launching neovim, LSP still throws some erroneous "unable to import module" messages. As you can see in the screenshot below:
- my venv is named Thesis and it's picked up by nvim (bottom right corner)
- lsp still throws that import error
![image](https://github.com/AstroNvim/astrocommunity/assets/82440615/d9baf0d8-6aee-4f5c-84f4-ce7b4b267bbd)

Anyone had the same problem/could provide me some help? It's quite annoying seeing those messages there when they shouldn't be there.

**Comment by Souravpakhira** [comment]
Even im facing same issue and also virtual env plugin is also not working

**Comment by Balssh** [comment]
> Even im facing same issue and also virtual env plugin is also not working

Which plugin are you referring to? Also what's interesting is that I'm pretty sure the problem is something from the AstroVim configs because I had use LazyVim the past weeks and it didn't happen.

**Comment by Souravpakhira** [comment]
> > Even im facing same issue and also virtual env plugin is also not working
> 
> Which plugin are you referring to? Also what's interesting is that I'm pretty sure the problem is something from the AstroVim configs because I had use LazyVim the past weeks and it didn't happen.

[venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim) this one which come in python pack

**Comment by jdix531** [comment]
I am using pyenv with pyenv-virtualenv plugin. I use base AstroNvim (nothing community related) and I am having this issue as well. Not sure if it tracks with more-vanilla neovim/venv usage though I suspect not just because I don't see a bunch of other issues around the web.

**Comment by Balssh** [comment]
> > > Even im facing same issue and also virtual env plugin is also not working
> > 
> > 
> > Which plugin are you referring to? Also what's interesting is that I'm pretty sure the problem is something from the AstroVim configs because I had use LazyVim the past weeks and it didn't happen.
> 
> [venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim) this one which come in python pack

Yeah this one doesn't seem to work either as I try to use the default mapping (<leader>lv) and nothing happens.

> I am using pyenv with pyenv-virtualenv plugin. I use base AstroNvim (nothing community related) and I am having this issue as well. Not sure if it tracks with more-vanilla neovim/venv usage though I suspect not just because I don't see a bunch of other issues around the web.

I suspect it's either something from AstroNvim or as you said from the virtualenv plugin because as I said, on LazyVim it was working fine.

**Comment by Souravpakhira** [comment]
> > > > Even im facing same issue and also virtual env plugin is also not working
> > > 
> > > 
> > > Which plugin are you referring to? Also what's interesting is that I'm pretty sure the problem is something from the AstroVim configs because I had use LazyVim the past weeks and it didn't happen.
> > 
> > 
> > [venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim) this one which come in python pack
> 
> Yeah this one doesn't seem to work either as I try to use the default mapping (lv) and nothing happens.
> 
> > I am using pyenv with pyenv-virtualenv plugin. I use base AstroNvim (nothing community related) and I am having this issue as well. Not sure if it tracks with more-vanilla neovim/venv usage though I suspect not just because I don't see a bunch of other issues around the web.
> 
> I suspect it's either something from AstroNvim or as you said from the virtualenv plugin because as I said, on LazyVim it was working fine.

How did you setup you statusline like nvchad. Also i did you configure your statusline to show the virtual env at the bottom?

**Comment by Souravpakhira** [comment]
> > > > Even im facing same issue and also virtual env plugin is also not working
> > > 
> > > 
> > > Which plugin are you referring to? Also what's interesting is that I'm pretty sure the problem is something from the AstroVim configs because I had use LazyVim the past weeks and it didn't happen.
> > 
> > 
> > [venv-selector.nvim](https://github.com/linux-cultist/venv-selector.nvim) this one which come in python pack
> 
> Yeah this one doesn't seem to work either as I try to use the default mapping (lv) and nothing happens.
> 
> > I am using pyenv with pyenv-virtualenv plugin. I use base AstroNvim (nothing community related) and I am having this issue as well. Not sure if it tracks with more-vanilla neovim/venv usage though I suspect not just because I don't see a bunch of other issues around the web.
> 
> I suspect it's either something from AstroNvim or as you said from the virtualenv plugin because as I said, on LazyVim it was working fine.

I think i have found the quick solution just install pylint in your virtual env it should solve the issue for pylint errors.

**Comment by Balssh** [comment]
Yeah, seems like installing pylint in the venv solved those errors. Still, I think this should be addressed in the AstroNvim config.

**Comment by luxus** [comment]
> Yeah, seems like installing pylint in the venv solved those errors. Still, I think this should be addressed in the AstroNvim config.

if you think so.. make a PR, if your need help just start one
