### ISSUE TITLE
Bug(pack): community pack python VenvSelect not working

### ISSUE THREAD

**Issue by Souravpakhira** [AstroNvim/astrocommunity#199]
Pressing <leader>lv doesn't open any popup.

**Comment by Souravpakhira** [comment]
[https://discord.com/channels/939594913560031363/1106654027334287521/1106859907023650846](url)

**Comment by Balssh** [comment]
Hi, found the fix: after installing the community python pack, go to your /plugins/user.lua (for example) and set the following code:
```
  {
    "linux-cultist/venv-selector.nvim",
    opts = {
      fd_binary_name = "fdfind",
    },
  },
```
The error is due to the fd binary being named fdfing on debian like distros (like Ubuntu). More info here: https://github.com/linux-cultist/venv-selector.nvim/issues/6

**Comment by Souravpakhira** [comment]
> 

Still not working for me Do i need to install something like fdfind or some?

**Comment by Souravpakhira** [comment]
But I still notice one issue is that if I select any virtual env from the popup window it doesn't activate the virtual env to the buffer because it still throws me the linting errors

**Comment by Balssh** [comment]
You have to resource the file with :e.

**Comment by luxus** [comment]
maybe we could add this information to the readme? what you guys think?

**Comment by Souravpakhira** [comment]
Yeah we can have it in readme for anyone new can also know about this.

**Comment by Balssh** [comment]
> maybe we could add this information to the readme? what you guys think?
Will open a PR with that soon with that.

**Comment by Souravpakhira** [comment]
> You have to resource the file with :e.

Doesn't solve the issue.
![Screenshot from 2023-05-14 11-51-59](https://github.com/AstroNvim/astrocommunity/assets/28139765/ebc5b964-50ca-4df6-abba-c7684dd8da4e)
This is what happens when entering :e.

**Comment by Balssh** [comment]
For me it's working, maybe you have some other keymap for e? Try closing the buffer and opening it again, this also works for me.

**Comment by Souravpakhira** [comment]
> For me it's working, maybe you have some other keymap for e? Try closing the buffer and opening it again, this also works for me.

Yeah closing and reopening works for me as well its the issue with pylint

**Comment by Balssh** [comment]
> > For me it's working, maybe you have some other keymap for e? Try closing the buffer and opening it again, this also works for me.
> 
> Yeah closing and reopening works for me as well its the issue with pylint

I guess you could add a thing that after a venv is selected to refresh/resource all opened buffers automatically, but I'm still too new to nvim/lua to do such thing 😄

**Comment by Souravpakhira** [comment]
> > > For me it's working, maybe you have some other keymap for e? Try closing the buffer and opening it again, this also works for me.
> > 
> > 
> > Yeah closing and reopening works for me as well its the issue with pylint
> 
> I guess you could add a thing that after a venv is selected to refresh/resource all opened buffers automatically, but I'm still too new to nvim/lua to do such thing smile

Same here im new to neovim and dont know much of things how it works
