### ISSUE TITLE
Add a README to each plugin

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/astrocommunity#20]
The readme should have a link to the plugin repo,a field for a maintainer, and configuration notes

_Originally posted by @luxus in https://github.com/AstroNvim/astrocommunity/issues/16#issuecomment-1440163580_
            

We should have a `README` for each plugin with some basic information about it

**Comment by luxus** [comment]
maybe a well commented demo plugin config with all edge cases explained

**Comment by mehalter** [comment]
Started basic implementation with this commit: https://github.com/AstroNvim/astrocommunity/commit/9aa1362677df75a4d9e559e31f626587021e9577

**Comment by luxus** [comment]
i guess we have a readme everywhere now..

**Comment by mehalter** [comment]
This is incorrect @luxus . The packs do not have READMEs, I thought you said that you would do that for those few on the PR that you closed. I added READMEs to everything else.

**Comment by mehalter** [comment]
This is the last thing before we can tag a 1.0 release of Astrocommunity. I can go ahead and finish that PR for you @luxus since you are starting up your new work position :)

**Comment by mehalter** [comment]
closed with 31a00bf2042ad6f2cae05e8e88dc2d00ad93682c
