### ISSUE TITLE
Satellite should be disabled when entering Zen Mode

### ISSUE THREAD

**Issue by tomKPZ** [AstroNvim/astrocommunity#207]
This issue only occurs when using both `satellite.nvim` and `zen-mode.nvim`.  Entering Zen mode disables most UI except the scrollbar.  I believe this should be toggled in the `on_open` and `on_close` functions here: https://github.com/AstroNvim/astrocommunity/blob/28fbc1e567c6d714ef321ae67d38393c597a7763/lua/astrocommunity/editing-support/zen-mode-nvim/zen-mode-nvim.lua#L24

**Comment by mehalter** [comment]
For cases like this where you are combining different plugins you may have to define your own `on_open` and `on_close` functions to meet your use case

**Comment by tomKPZ** [comment]
Makes sense, but both of those plugins are part of the `astrocommunity` repo, so it'd be nice to be able to enable them both without having to add extra configuration to workaround the conflict.

**Comment by mehalter** [comment]
In that case you can definitely make a new plugin pack that does both of these and handles their interactions

**Comment by tomKPZ** [comment]
I'm not familiar with how plugin packs work.  But wouldn't it duplicate the code for those plugins?  And it would seem to not solve the issue if the plugins are enabled individually without the user knowing they should enable the pack instead.

**Comment by mehalter** [comment]
I haven't tested this, but it should be something along the lines of this is a great way to use the modular approach of community packages to create plugin packs without duplicating code:

```lua
return {
  { import = "astrocommunity.editing-support.zen-mode-nvim" },
  { import = "astrocommunity.scrolling.satellite-nvim" },
  {
    "folke/zen-mode.nvim",
    opts = function(_, opts)
      local old_on_open, old_on_close = opts.on_open, opts.on_close
      opts.on_open = function()
        old_on_open()
        vim.cmd.SatelliteDisable()
      end
      opts.on_close = function()
        old_on_close()
        vim.cmd.SatelliteEnable()
      end
    end,
  },
}
```

**Comment by tomKPZ** [comment]
Thanks, that snippet works in my local config.  It's unfortunate that technical limitations prevent fixing the issue upstream.

**Comment by mehalter** [comment]
@tomKPZ a new feature in Lazy.nvim has been added which allows us to do this :) I have started a new PR that will allow you to delete this snippet from your local configuration.

**Comment by tomKPZ** [comment]
Thanks!  I just updated astrocommunity and removed the snippet from my config and can verify that it's working great!
