### ISSUE TITLE
Typescript pack always to configured to use eslint and prettier

### ISSUE THREAD

**Issue by ksnll** [AstroNvim/astrocommunity#225]
With the current configuration of the typescript pack, every project with a `package.json` in the root, will configure `null-ls` to use `prettier` and `eslint`.
This will show an error to the user for every project that doesn't have one of the two installed and configured.

A better approach would be to check inside the `package.json` if the keys `eslintConfig` and `prettier` are present. 

https://github.com/AstroNvim/astrocommunity/blob/b88a6e68c68b5fc5b780c767d8c0ba8cd360198e/lua/astrocommunity/pack/typescript/typescript.lua#L41-L49

**Comment by Uzaaft** [comment]
I'm not sure of we should begin to parse the package.json files to see if the eslintConfig or prettier keys are present. Any thoughts @owittek ?

**Comment by owittek** [comment]
We'd have to check for performance implications but wouldn't just removing the first check for the `package.json` be sufficient?

**Comment by ksnll** [comment]
Some people might have eslint & prettier configured in their `package.json`, so if we remove the check altogether it would not load for them.
I still think it would be better than the current situation tho, as it would be an easy fix to have prettier/eslint working again (ust create an empty prettierrc/eslintrc), while the current issue is not as  easily solvable

**Comment by Uzaaft** [comment]
@ksnll  I've attempted to add the functionality in #231. 
@mehalter I'm not sure about the pattern we want to have. Should it be:
```
if prettier:
	disable_eslint() 
if eslint:
	disable_prettier()
if both:
	keep_both()
if none:
	keep_both()
```
