### ISSUE TITLE
Can't cover community default config

### ISSUE THREAD

**Issue by duanyuluo** [AstroNvim/astrocommunity#239]
:healthcheck report (https://gist.github.com/duanyuluo/e928d4672f7f31a1a185201e55810184)
1) import trouble-nvim plugin at community.lua

2) modify keymap
<img width="811" alt="Screenshot 2023-05-28 at 17 49 19" src="https://github.com/AstroNvim/astrocommunity/assets/4272707/8b17792f-9682-48be-a60d-2b1d2c051542">

3) these mappings are all work, which-key -> < leader > E

4) PROBLEM: default < leader > x also exist in which-key
<img width="862" alt="Screenshot 2023-05-28 at 17 55 10" src="https://github.com/AstroNvim/astrocommunity/assets/4272707/aa56eabb-c269-4389-ab9d-4dbe14cfb0de">

How to cover default config (eg, keymap) in astrocommunity?

**Comment by luxus** [comment]
in this case just remove the import of trouble-nvim and it should work

**Comment by duanyuluo** [comment]
> 

Thanks very much. That's work!
