### ISSUE TITLE
Rust debug error...

### ISSUE THREAD

**Issue by duanyuluo** [AstroNvim/astrocommunity#240]
:checkhealth report : https://gist.github.com/duanyuluo/e928d4672f7f31a1a185201e55810184

1) import pack.rust in community

2) add "codelldb" in mason.lua
<img width="500" alt="Screenshot 2023-05-28 at 18 24 21" src="https://github.com/AstroNvim/astrocommunity/assets/4272707/eb6817ac-0dea-4f8e-ad23-651bf9a93bcd">

3) codelldb, rust-tool & rust-analyizer are all installed and worked finely.
<img width="374" alt="Screenshot 2023-05-28 at 18 25 16" src="https://github.com/AstroNvim/astrocommunity/assets/4272707/74be54c4-6dba-4992-8116-bbd50b09fd2c">

4) with cmd "rust hover action" to start debug ... that's error...
<img width="974" alt="Screenshot 2023-05-28 at 18 21 34" src="https://github.com/AstroNvim/astrocommunity/assets/4272707/77027e70-e0fb-4d1e-9932-39f10b4777af">

Do I need to config Dap provider and configuration by myself? ( I have try it, but it's so complex...)

**Comment by luxus** [comment]
u will break a lot of stuff if you add lsps like that. the code you post in the picture will overwrite everything.
btw please use codeblocks instead of screenshots
and codellb is already provided by the rust pack.. but maybe ur code is overwriting it.
remove the code from the first screenshot

**Comment by duanyuluo** [comment]
> u will break a lot of stuff if you add lsps like that. the code you post in the picture will overwrite everything. btw please use codeblocks instead of screenshots and codellb is already provided by the rust pack.. but maybe ur code is overwriting it. remove the code from the first screenshot

I have remove other lsp server and dap config. But this question is still exist.
I can debug rust project by F5 F9, but this issue happen while I use :RustHoverAction -> debug, or :RustDebugable .

BTW, this issue is maybe same with https://github.com/simrat39/rust-tools.nvim/issues/244
My lua is so poor... I can't research and debug astronvim's source codes...

thanks a lot @luxus

**Comment by luxus** [comment]
Please remove the code from the first screenshot

**Comment by luxus** [comment]
@Uzaaft any idea?

**Comment by duanyuluo** [comment]
I have remove it. https://github.com/duanyuluo/dotfile/blob/master/nvim/plugins/mason.lua
but this issue still exist...

**Comment by duanyuluo** [comment]
I only remain three pack: go rust python. (ruff_lsp could not install)

**Comment by Uzaaft** [comment]
rust debugging works fine for me currently.
Are you sure that it's not rustrust-cfg.lua that fucks up things at your end?

**Comment by duanyuluo** [comment]
WTF, I just create rust-cfg.lua after #239 for cover default keymaps. after remove this file, everything is OK. Thank @Uzaaft 
But, default keymaps have confict... How can I modify Rust-Tool's default keymaps?

**Comment by duanyuluo** [comment]
I will close this issue now. let me known how to modify rust-tool default mapping without disturbing debug :)
Thank a lot @Uzaaft

**Comment by duanyuluo** [comment]
<img width="607" alt="Screenshot 2023-05-29 at 00 52 39" src="https://github.com/AstroNvim/astrocommunity/assets/4272707/cbaa1eb6-7074-4893-83c4-1f3e09762b8a">

**Comment by Uzaaft** [comment]
I believe the keys table in lazy.nvim allows you to do that.
