### ISSUE TITLE
Markmap installation via mason

### ISSUE THREAD

**Issue by jay-babu** [AstroNvim/astrocommunity#244]
Can't mason just be used to manage the installation of this?

_Originally posted by @jay-babu in https://github.com/AstroNvim/astrocommunity/pull/229#issuecomment-1567535449_

**Comment by jay-babu** [comment]
I understand that, but we can add it. It's pretty simple

**Comment by jay-babu** [comment]
https://github.com/mason-org/mason-registry/pull/1780/files

**Comment by luxus** [comment]
so we can close it again? :D
