### ISSUE TITLE
Dropbar error

### ISSUE THREAD

**Issue by duanyuluo** [AstroNvim/astrocommunity#250]
:checkhealth https://gist.github.com/duanyuluo/e928d4672f7f31a1a185201e55810184

error info
<img width="385" alt="Screenshot 2023-06-02 at 09 47 45" src="https://github.com/AstroNvim/astrocommunity/assets/4272707/70249ea8-1ee8-43d0-b88d-ab0d603aea7a">

dropbar.nvim requires at least nvim 0.10 ?!

**Comment by mehalter** [comment]
Yup, dropbar requires the current Neovim 0.10 nightly

**Comment by duanyuluo** [comment]
> Yup, dropbar requires the current Neovim 0.10 nightly

OMG, Thanks @mehalter
