### ISSUE TITLE
Using Lua language pack and traversing astroNvim configuration too slow 

### ISSUE THREAD

**Issue by shivanthzen** [AstroNvim/astrocommunity#251]
The astronvim configuration with userConfiguration slows down when I open a file in the configuration. It seems it is indexing every file in the index and libraries. The LSP status bar on the right behaves weird with multiple status being show. on top of another until the right hand side of screen is full

**Comment by Hugo-CASTELL** [comment]
Can you provide more context (what is your configuration) and add screenshots to this issue ?

**Comment by Uzaaft** [comment]
@shivanthzen We'll need a Minimal reproducable config before we can troubleshoot the issue.

**Comment by Uzaaft** [comment]
I'm going ahead and closing this one. @shivanthzen  Feel free to reopen when you've provided us with more context and a minimal reproducable config.
