### ISSUE TITLE
gruvbox.nvim readme is outdated on italic

### ISSUE THREAD

**Issue by oneslash** [AstroNvim/astrocommunity#273]
Please refer to the new: https://github.com/ellisonleao/gruvbox.nvim/issues/220

**Comment by Uzaaft** [comment]
@oneslash  Feel free to open a PR. :)

**Comment by oneslash** [comment]
Ah,Will do later today or tomorrow.

(I was lazy)

**Comment by Uzaaft** [comment]
> Ah,Will do later today or tomorrow.
> 
> (I was lazy)

Looking forward to it! 👀
I'm going ahead and assigning you to this issue then

**Comment by oneslash** [comment]
@Uzaaft done!
