### ISSUE TITLE
Typescript  pack results in runtime error

### ISSUE THREAD

**Issue by samtay** [AstroNvim/astrocommunity#278]
This was working, but all of a sudden (presumably after some update of packages) now when I open TS files I just see this:
```
Failed to run `config` for typescript.nvim

/home/sam/.config/nvim/lua/astronvim/utils/lsp.lua:387: attempt to index field 'document_config' (a nil value)

# stacktrace:
  - ~/.config/nvim/lua/astronvim/utils/lsp.lua:387 _in_ **config**
  - /astrocommunity/lua/astrocommunity/pack/typescript/typescript.lua:115 _in_ **values**
  - /usr/share/nvim/runtime/filetype.lua:22
  - /usr/share/nvim/runtime/filetype.lua:21
  ```

and the LSP fails to start.

This is just using a vanilla config: `{ import = "astrocommunity.pack.typescript" },`

**Comment by samtay** [comment]
This is caused by some conflict in the `typescript` and `dart` packs. A minimal reproducible example is to take a fresh astrovim config from https://github.com/AstroNvim/user_example and change `plugins/community.lua` to:
```lua
return {
  -- Add the community repository of plugin specifications
  "AstroNvim/astrocommunity",
  -- example of imporing a plugin, comment out to use it or add your own
  -- available plugins can be found at https://github.com/AstroNvim/astrocommunity

  -- { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.pack.dart" },
}
```

**Comment by Uzaaft** [comment]
I can't reproduce locally. Got both pack's enabled in my config

**Comment by Uzaaft** [comment]
Nor do I get the issue when using the Minimal rep. example from your post. 
Have you updated all packages, including all mason stuff?

**Comment by samtay** [comment]
Wow, that is bizarre. Yes, I'm up to date on everything. And when I used the minimal example I cleaned and synced the plugins and pakages. I'm on arch linux, don't know what else would be relevant :shrug:

**Comment by Uzaaft** [comment]
Let me test on arch

**Comment by Uzaaft** [comment]
Managed to recreate in Arch

**Comment by Uzaaft** [comment]
Managed to Get this issue on Mac now

**Comment by Uzaaft** [comment]
This seems to be an issue with `typescript.nvim` based upon my chat with mehalter in #dev in discord

**Comment by Uzaaft** [comment]
Actually, it's the other way around. flutter-tools seems to affect the lsp setup. 🤣

**Comment by mehalter** [comment]
Nah, neither of the plugins are broken. The dart pack is very broken here

**Comment by Uzaaft** [comment]
hey I was trying to live report your findings 🤣 The log here is just an transcription
