### ISSUE TITLE
Status bar randomly disappearing with andymass/vim-matchup

### ISSUE THREAD

**Issue by saumyajyoti** [AstroNvim/astrocommunity#279]
The status bar gets disabled at some lines when match-up highlights some code lines.

**Comment by saumyajyoti** [comment]
This can be fixed by below addition:

 init = function()
    vim.g.matchup_matchparen_offscreen = { method = "popup" }
  end,

**Comment by saumyajyoti** [comment]
The above change can be added in matchup lua file

**Comment by Uzaaft** [comment]
@saumyajyoti  Do you have some docs to back up your fix?

**Comment by saumyajyoti** [comment]
I think this is expected behavior for matchup. The default settings is replacing the status-bar. Please refer https://github.com/andymass/vim-matchup#c3-display-matches-off-screen

**Comment by jay-babu** [comment]
should this be added to the default?

**Comment by jay-babu** [comment]
https://github.com/AstroNvim/astrocommunity/pull/331
