### ISSUE TITLE
Issues with copilot.lua

### ISSUE THREAD

**Issue by Miyuki0010** [AstroNvim/astrocommunity#287]
I originally wanted to use it, but due to the lack of my subscription to that service, I want to get rid of it. 
But when I want to delete it from my astrovim config, it always fetches back. I removed it out of my ~/.config/nvim/lua/user, but then it shows up in the package menu in astrovim.
I even tried to delete it in the place where it is stored but same problem, it straight up fetches back and annoys me with subscribing to it.

**Comment by Uzaaft** [comment]
You need to remove the Line where you import it.
