### ISSUE TITLE
pack/rust: Make rust analyzer use its own profile in cargo

### ISSUE THREAD

**Issue by hunger** [AstroNvim/astrocommunity#300]
I found it annoying for a while now that rust-analyzer will cause a `cargo build` to print "Waiting for lock on build directory" and then wait till rust-analyzer is done before doing anything.

This snippet makes rust-analyzer use its own profile instead of `dev`, leaving `cargo` free to build the `debug` profile at any point in time:

```lua
  lsp = {
    config = {
      rust_analyzer = {
        settings = {
          ["rust-analyzer"] = {
            cargo = {
              extraEnv = { CARGO_PROFILE_RUST_ANALYZER_INHERITS = 'dev', },
              extraArgs = { "--profile", "rust-analyzer", },
            },
          },
        },
      },
    },
  },
```

Maybe that could be done by the rust pack? It makes it so much smoother to work with rust in neovim at the expanse of using more disk space for the extra profile in the target folder of your projects.

PS: I hope this is the right way to suggest features for the packs!

**Comment by Uzaaft** [comment]
I like this change. But I believe this is outside the scope of the pack, since it configures the LSP.
@hunger  Could you open a PR to add this in the docs?

**Comment by Uzaaft** [comment]
That's what I meant.
