### ISSUE TITLE
pack/lua: luacheck warns about accesing undefined variable 'vim'

### ISSUE THREAD

**Issue by paxet** [AstroNvim/astrocommunity#302]
Starting with a base config from: https://github.com/AstroNvim/user_example
Set up lua "pluging" from astrocommunity like so:

``` sh
$ cat lua/user/plugins/community.lua
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
}
```
Start nvim and wait for plugins to be installed, and then quit.
Open file `lua/user/init.lua` and use global "vim" variable like

``` lua
  polish = function()
    -- Map 'Q' to force quit without saving files
    vim.cmd "cmap Q qa!"
  end,
```
luacheck will :warning:  you with:

```
accessing undefined variable 'vim'
```

I've seen it can be added to diagnostics -> globals when setting up the lua_ls language server, but don't now how we can achieve it in our "plugin" for lua

**Comment by mehalter** [comment]
@windowsrefund if you are using `~/.config/astronvim` you just want to make sure your luacheck file is in the workspace root of your project. So you probably want to put it in `~/.config/astronvim` and not in the `lua/user` folder

**Comment by windowsrefund** [comment]
This is still not working.
