### ISSUE TITLE
Harpoon keybinds are replacing LSP's one

### ISSUE THREAD

**Issue by bruunoromero** [AstroNvim/astrocommunity#304]
Neovim's lsp uses the tag stack, because of this `<C-t>` jumps back to the previous tag. After the changes of PR #292 it started to remap the `<C-t>` [mapping](https://github.com/AstroNvim/astrocommunity/blob/901fc36da55f92de981fdc135125544c1b690ace/lua/astrocommunity/motion/harpoon/init.lua#L17) to select a mark by it's index.

I'm not sure of a better mapping (`<C-x>`?), but I'd like to discuss about changing it to other one that doesn't interfere with lsp's mappings.

**Comment by mehalter** [comment]
@RayJameson what do you think? I think this does sound like we should change the harpoon matching

**Comment by mehalter** [comment]
@bruunoromero I opened up a PR to fix this by moving the mapping to `<C-x>` and also cleaned up some of the implementation of the harpoon spec in general. Could you try using the `harpoon_fix` branch of AstroCommunity and see if that resolves the problem and also doesn't introduce new ones?

**Comment by bruunoromero** [comment]
Sure! By the end of the day I'll let you know if everything is fine.

**Comment by bruunoromero** [comment]
@mehalter Just passing by to let you know that it's working as expected

**Comment by RayJameson** [comment]
@mehalter Sorry, for some reason I received the notification now, after 3 days...
