### ISSUE TITLE
gitsigns, ale and hlens not working in (scrolling/nvim-scrollbar)

### ISSUE THREAD

**Issue by kachidk** [AstroNvim/astrocommunity#338]
It works only when I manually set it

![image](https://github.com/AstroNvim/astrocommunity/assets/61981167/cc032ae5-3387-4f60-ac1d-6cf1f6a551be)

**Comment by Uzaaft** [comment]
@kachidk Thanks for racing the issue. I'll take a look :)

**Comment by Uzaaft** [comment]
@kachidk #350  Should fix this.
