### ISSUE TITLE
neogit: project moved to neogitorg/neogit

### ISSUE THREAD

**Issue by practicalli-john** [AstroNvim/astrocommunity#354]
The Git / Neogit plugin have moved from https://github.com/TimUntersberger/neogit to https://github.com/NeogitOrg/neogit to support greater community contribution.

Suggest updating https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/git/neogit to use new plugin location

**Comment by practicalli-john** [comment]
I find it appropriate to raise the issue to confirm its a welcome contribution before investing time in a PR, especially when I am very new to a project.

**Comment by mehalter** [comment]
Resolved with #355

**Comment by mehalter** [comment]
Definitely feel free to  contribute pull requests @practicalli-john ! This repository is not maintained by core AstroNvim developers at all and is purely powered by pull requests :) Just make sure to take a look at the contribution guidelines
