### ISSUE TITLE
Add neodev integration for neotest community pack

### ISSUE THREAD

**Issue by krishnakumarg1984** [AstroNvim/astrocommunity#406]
The [neotest README](https://github.com/nvim-neotest/neotest#configuration) says:

>It is highly recommended to use [neodev.nvim](https://github.com/folke/neodev.nvim) to enable type checking for neotest to get type checking, documentation and autocompletion for all API functions.
>
> ```lua
> require("neodev").setup({
>   library = { plugins = { "neotest" }, types = true },
>   ...
> })
> ```

Could we please add this to the astrocommunity's neotest pack [here](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/test/neotest/init.lua)?

**Comment by mehalter** [comment]
Sure! PRs welcome!

**Comment by Uzaaft** [comment]
@krishnakumarg1984 can you test #440

**Comment by krishnakumarg1984** [comment]
Tested and found to be working. Thanks for incorporating this!
