### ISSUE TITLE
error with tailwindcss lsp server and twig file (symfony)

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#412]
Hi,

When I open a html file, everything is OK: tailwindcss lsp is loaded and behaves well.
But for the twig file (*.html.twig"), no tailwindcss lsp server is loaded.

Can you fix that or explain to me how to do that?

Thank you for the reply and congrats on the amazing job you have 
done so far! 👍

Rgds,

**Comment by Uzaaft** [comment]
You'll have to add twig files to the lspconfig.
See https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tailwindcss
