### ISSUE TITLE
Recently vim-matchup break everything!

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#423]
Hi,

After installing vim-matchup, I got many errors that it makes
me impossible to work.

Nothing has been tested?

Disappointing ...

Cdlt,

**Comment by mehalter** [comment]
This is a fairly regular occurrence with `vim-matchup` and `nvim-treesitter` in my experience. The treesitter queries will get updated on one and not the other for languages as changes get propagated and sometimes you just have to wait until that gets situated :/ luckily it's not *all* languages at once it will end up just being one or two that were just recently updated :joy: Sorry this is out of our hands sadly and just falls under "we can only make it as stable as the plugins themselves"
