### ISSUE TITLE
CPP pack: "No specs found for module astrocommunity.pack.cpp"

### ISSUE THREAD

**Issue by Per48edjes** [AstroNvim/astrocommunity#431]
Added to my config in the same way as the other wonderful community packs:

```
...
  { import = "astrocommunity.pack.cpp" },
...
```

Let me know if I'm missing something painfully obvious!

---

**UPDATE**: Was able to get the various components working just by manually adding the configs, so maybe this has something to do with how community packs are resolved?

**Comment by Uzaaft** [comment]
The pack works fine for me. 
Is everything up to date? See of `:messages` prints out some useful info

**Comment by owittek** [comment]
yeah sounds like your local astrocommunity isn't up2date with remote. Try updating your plugins with `<leader>pa`.

**Comment by Per48edjes** [comment]
Y'all are spot on! I thought I did this, but in my haste pulled latest changes to local `astronvim` rather than `astrocommunity`. 🤦🏽‍♂️

My apologies for the trouble.

**Comment by Uzaaft** [comment]
No worries
