### ISSUE TITLE
since upgrading to v3.2.0 I get "No specs found for module"

### ISSUE THREAD

**Issue by mvolkmann** [AstroNvim/astrocommunity#455]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 13.3.1

### Terminal/GUI

Warp

### AstroNvim Health

This is the output of `:checkhealth`, NOT `:checkhealth astronvim` in which everyting is OK.
Note the errors near the end.

==============================================================================
astronvim: require("astronvim.health").check()

AstroNvim ~
- AstroNvim Version: v3.32.0
- Neovim Version: v0.9.0
- OK Using stable Neovim >= 0.8.0
- OK `git` is installed: Used for core functionality such as updater and plugin management
- OK `open` is installed: Used for `gx` mapping for opening files with system opener (Optional)
- OK `lazygit` is installed: Used for mappings to pull up git TUI (Optional)
- OK `node` is installed: Used for mappings to pull up node REPL (Optional)
- OK `gdu` is installed: Used for mappings to pull up disk usage analyzer (Optional)
- OK `btm` is installed: Used for mappings to pull up system monitor (Optional)
- OK `python3` is installed: Used for mappings to pull up python REPL (Optional)

==============================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- OK Git installed
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found
- WARNING {package-info.nvim}: unknown key <requires>
- WARNING {LuaSnip}: overriding <config>
- ERROR Issues were reported when loading your specs:
- ERROR No specs found for module astrocommunity.colorscheme.gruvbox
- ERROR No specs found for module astrocommunity.colorscheme.nightfox
- ERROR No specs found for module astrocommunity.colorscheme.tokyonight
- ERROR No specs found for module astrocommunity.editing-support.treej

### Describe the bug

Since upgraded to V3.2.0 I get the following errors every time I start nvim:

No specs found for module astrocommunity.colorscheme.gruvbox
No specs found for module astrocommunity.colorscheme.nightfox
No specs found for module astrocommunity.colorscheme.tokyonight
No specs found for module astrocommunity.editing-support.treej

### Steps to Reproduce

1. Launch nvim.

### Expected behavior

I don't mind not having those fonts. I just want to eliminate the error messages.

**Comment by mehalter** [comment]
No, this has been fixed in astrocommunity. You need to update your configuration to have the new import locations

**Comment by mehalter** [comment]
In this file: https://github.com/mvolkmann/MyUnixEnv/blob/master/nvim/lua/user/plugins/community.lua

It should be

```lua

return {
  "AstroNvim/astrocommunity",

  { import = "astrocommunity.pack.typescript" },

  {
    import = "astrocommunity.colorscheme.catppuccin",
    enabled = true
  },
  {
    import = "astrocommunity.colorscheme.gruvbox-nvim",
    enabled = true
  },
  {
    import = "astrocommunity.colorscheme.nightfox-nvim",
    enabled = true
  },
  {
    import = "astrocommunity.colorscheme.rose-pine",
    enabled = true
  },
  {
    import = "astrocommunity.colorscheme.tokyonight-nvim",
    enabled = true
  }
}
```

It looks like this file is probably out of date since you also have `treesj`, that one is much simpler, you just have a typo `treej` should be `treesj`

**Comment by mehalter** [comment]
Is the link I sent helpful? That's at least where they were in your `user/` folder 2 months ago 😅

**Comment by mvolkmann** [comment]
Thank you SO MUCH! Your suggested changes fixed my issues.
