### ISSUE TITLE
lsp.inc-rename-nvim not working

### ISSUE THREAD

**Issue by fynnfluegge** [AstroNvim/astrocommunity#463]
`lsp.inc-rename-nvim` is not working with astrocommunity. `vim.lsp.buf.rename()` is called instead.
My workaround is setting the mapping to `<leader>rn`, since using `<leader>lr` does not work.
There is the following lsp_mapping in `.nvim/lua/astronvim/utils/lsp.lua`
![Screenshot 2023-07-19 at 20 20 19](https://github.com/AstroNvim/astrocommunity/assets/16321871/e6b8af73-b1e8-4c1d-9b22-cd8f86bcbd45)
`inc-rename-nvim` does not override that mapping.

I see two possible solutions:
1. map `inc-rename-nvim` to `<leader>rn`
2. disable `vim.lsp.buf.rename()` mapping in the `init.lua` of `inc-rename-nvim`
 
Let me know which solution is better and I will raise PR 🙏

**Comment by Uzaaft** [comment]
Solutions 2 is what seem to fit best with what we're trying to achieve in astrocom.

**Comment by Uzaaft** [comment]
@fynnfluegge Do you have an ETA for the PR?

**Comment by fynnfluegge** [comment]
Not yet, was playing around a bit but was not able yet to disable the `vim.lsp.bug.rename()` lsp mapping. It is enabled on lsp attach in the AstroNvim config. Using a more offensive lazy loading event for `inc-rename` has no effect.

**Comment by fynnfluegge** [comment]
Tried kind of this
```lua
    "smjonas/inc-rename.nvim",
    requires = { "astronvim/astronvim.nvim" },
    opts = function(bufnr)
      local lsp_mappings = require("astronvim.utils").empty_map_table()
      lsp_mappings.n["<leader>lr"] = nil
      local utils = require "astronvim.utils"
      local user_opts = astronvim.user_opts
      utils.set_mappings(user_opts("lsp.mappings", lsp_mappings), { buffer = bufnr })
    end,
    keys = {
      {
        "<leader>lr",
        function()
          require "inc_rename"
          return ":IncRename " .. vim.fn.expand "<cword>"
        end,
        expr = true,
        desc = "IncRename",
      },
    },
```
But this is not called after AstroNvim's `lsp.on_attach`, no idea how to tweak this into the loading chain currently. `<leader>lr` still executes the `textDocument/rename`. Any idea?

**Comment by Uzaaft** [comment]
@fynnfluegge Try adding `event = {"AstroLsp"}`

**Comment by fynnfluegge** [comment]
@Uzaaft that doesn't work it throws `unexpected event` on loading

**Comment by luxus** [comment]
this will be resolveable with astronvim v4

**Comment by Uzaaft** [comment]
Tested with v4, worked perfectly fine

**Comment by fynnfluegge** [comment]
> Tested with v4, worked perfectly fine

Will continue on this then

**Comment by fynnfluegge** [comment]
Hey @Uzaaft could you provide an example how you tested this please? Going to solve this issue now but I also want to remap the following:
```lua
    ["<leader>k"] = {
      function() vim.lsp.buf.hover() end,
      desc = "Hover symbol details",
    },
```
This is also an lsp_mapping and hopefully can be remapped with v4. Overriding this in `mappings.lua` has no effect.

**Comment by Uzaaft** [comment]
1. Are you using v4?
2. The code I used is code for inc-rename-nvim in the main branch

**Comment by fynnfluegge** [comment]
Hm doesn't work for me with `v4` and `inc-rename` from main. Same behaviour as v3.

**Comment by Uzaaft** [comment]
@fynnfluegge Try this:

```lua
{
    "smjonas/inc-rename.nvim",
    opts = {},
  },
  {
    "AstroNvim/astrolsp",
    opts = {
      mappings = {
        n = {
          ["<leader>lr"] = {
            ":IncRename ",
            desc = "IncRename",
          },
        },
      },
    },
  },
```

**Comment by Uzaaft** [comment]
@fynnfluegge  Friendly reminder

**Comment by fynnfluegge** [comment]
Hm doesn't work neither 😕

**Comment by Uzaaft** [comment]
This is my code, works fine for me. Make sure you're on the newest v4 version
```lua
return {
  {
    "smjonas/inc-rename.nvim",
    cmd = "IncRename",
    config = true,
  },
}
```
```lua
{
    "AstroNvim/astrolsp",
    opts = {
      mappings = {
        n = {
          ["<leader>lr"] = {
            ":IncRename ",
            desc = "IncRename",
          },
        },
      },
    },
  },
```

**Comment by mehalter** [comment]
This is resolved in v4. One big thing to note is the language server does need to be _finished_ loading before incremental renaming will show up.
