### ISSUE TITLE
Dart pack is interfering with rust_analyzer from loading.

### ISSUE THREAD

**Issue by vamseekm** [AstroNvim/astrocommunity#468]
I have multiple language packs enabled and suddenly rust_anlyzer isn't loading anymore as long as the dart pack is present. :LspInfo is showing rust_analyzer is loaded and attached to the current rust file buffer.

**Comment by Uzaaft** [comment]
I just tested with the dark pack and rust pack enabled at the same time. No issues here.
Are you sure that RA is not being slow?
What version of RA are you running?

**Comment by vamseekm** [comment]
~/.local/share/nvim/mason/bin/rust-analyzer version seems to be

`rust-analyzer 0.3.1599-standalone (99718d0c8 2023-07-22)`

here is my user config. 

`return {
  plugins = {
    "AstroNvim/astrocommunity",
    -- { import = "astrocommunity.bars-and-lines.vim-illuminate" },
    { import = "astrocommunity.colorscheme.everforest" },
    -- { import = "astrocommunity.colorscheme.tokyonight-nvim" },
    -- { import = "astrocommunity.colorscheme.poimandres-nvim" },
    -- { import = "astrocommunity.diagnostics.trouble-nvim" },
    -- { import = "astrocommunity.lsp.lsp-inlayhints-nvim" },
    -- { import = "astrocommunity.pack.bash" },
    -- { import = "astrocommunity.pack.go" },
    -- { import = "astrocommunity.pack.html-css" },
    -- { import = "astrocommunity.pack.json" },
    -- { import = "astrocommunity.pack.lua" },
    -- { import = "astrocommunity.pack.markdown" },
    -- { import = "astrocommunity.pack.proto" },
    -- { import = "astrocommunity.pack.python" },
    { import = "astrocommunity.pack.rust" },
    -- { import = "astrocommunity.pack.tailwindcss" },
    -- { import = "astrocommunity.pack.typescript" },
    -- { import = "astrocommunity.pack.vue" },
    { import = "astrocommunity.pack.dart" },
    -- { import = "astrocommunity.utility.noice-nvim" },
  },
  colorscheme = "everforest",
}`

**Comment by Uzaaft** [comment]
Oh that might be one of the buggy ones @vamseekm . Try and update RA to the newest version :)

**Comment by vamseekm** [comment]
I think the binary that's being is used is from homebrew so I upgraded that one. And it's getting loaded and lsp things are working fine. But once I enable dart tools and restart the editor rust-analyzer isn't even showing up in the OS process list. It could be a platform-specific (OSX) quirk.

**Comment by Uzaaft** [comment]
I'm also using OSX.
@vamseekm Couldn't it be that RA is just being slow?
I think, it might just be my imagination, but rust + dart pack causes my RA to startup slower

**Comment by vamseekm** [comment]
Previously waited a few minutes more than normal to see if the rust analyser was starting slow. Will check again and confirm if the slow startup is the issue.

**Comment by Uzaaft** [comment]
Managed to recreate this today🤣 Seems like RA is using extra time to setup when flutter + Rust is enabled.

**Comment by Uzaaft** [comment]
@vamseekm  I believe #621 miiiight fix the issue with RA now. Could you test it?

**Comment by Uzaaft** [comment]
Bug is no longer there.
