### ISSUE TITLE
Prettier conflict between markdown and typescript packs

### ISSUE THREAD

**Issue by patrickarmengol** [AstroNvim/astrocommunity#472]
Installing both the markdown and typescript packs means you end up with no prettier formatting for markdown files. This seems to be because the typescript pack adds a [check for a prettier config file in the workspace](https://github.com/AstroNvim/astrocommunity/blob/79ad1468bcef48372d6e1df3e5b331405892e4be/lua/astrocommunity/pack/typescript/init.lua#L60), which wouldn't exist in most cases for markdown.

**Comment by Uzaaft** [comment]
We'll have to think about how we would want to solve this one

**Comment by mehalter** [comment]
This is resolved

**Comment by mehalter** [comment]
https://github.com/AstroNvim/astrocommunity/commit/5c186d976c51f17b868ed97c83694be97df9d73e
