### ISSUE TITLE
Add PHP formatter

### ISSUE THREAD

**Issue by Richie-Z** [AstroNvim/astrocommunity#473]
Since the LSP uses PHPactor, which there isn't a built-in formatter, could the team add a formatter.  Either use [php-cs-fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) or change the LSP using PHPIntelephense. Thanks

**Comment by Uzaaft** [comment]
#476 should solve this. @Richie-Z  Can you verify?

**Comment by Richie-Z** [comment]
> #476 should solve this. @Richie-Z Can you verify?

yup it work, Thanks
