### ISSUE TITLE
onedark-pro theme

### ISSUE THREAD

**Issue by karambaq** [AstroNvim/astrocommunity#480]
<img width="1582" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/14233969/f7d102d1-f6bf-4b6e-a0ee-4def7854fb86">

Statusline and bufferline highlights are missing

**Comment by Uzaaft** [comment]
I'm closing this issue. Please write a more filled out issue and reopen. :) I don't understand what's the issue based upon the very little info + screenshot.
