### ISSUE TITLE
copilot-lua-cmp breaks default cmp <C-n> binding

### ISSUE THREAD

**Issue by kmiasko** [AstroNvim/astrocommunity#497]
I can't select next suggestion from cmp popup when there is copilot suggestion, this is very frustrating.

```
opts.mapping["<C-n>"] = cmp.mapping(function()
  if copilot.is_visible() then copilot.accept_line() end
end)
```

Not always copilot suggestion is that what we want. Consider to not overwrite default cmp / vim behaviour.

**Comment by Uzaaft** [comment]
Feel free to open a PR with a possible fix. :)

**Comment by kmiasko** [comment]
> Feel free to open a PR with a possible fix. :)

It was introduced few days ago in this commit. It should just be reverted.

https://github.com/AstroNvim/astrocommunity/commit/aeecada9c9abaa7961a74528caf637ba7683b2b1

**Comment by fynnfluegge** [comment]
@kmiasko sorry for this, for me it was the other way round, and I had the feeling it is more intuitive to override `<C-n>` for the accept line of copilot.
In AstroNvim the cmp is also mapped to `<C-j>`, `<C-k>`.
<img width="689" alt="Screenshot 2023-08-07 at 09 37 28" src="https://github.com/AstroNvim/astrocommunity/assets/16321871/3eeb669e-6b4d-444d-91cc-da2b04372ded">
However, let's keep the mapping as it is now then 🙂
