### ISSUE TITLE
bug: Typescript (tsx) ending being added when not needed

### ISSUE THREAD

**Issue by jay-babu** [AstroNvim/astrocommunity#517]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

N/A

### Operating system/version

N/A

### Terminal/GUI

alacritty

### Describe the bug

<FaPrint/> should be written but <FaPrint/FaPrint> gets written, which doesn't compile.

### Steps to Reproduce

https://github.com/jay-babu/dotfiles/blob/main/shell/.config/nvim/lua/user/plugins/community.lua#L48

https://github.com/jay-babu/dotfiles/blob/d921e359bd13dae470117d0361849ba0938c134a/shell/.config/nvim/lua/user/lsp/config/tsserver.lua#L14

only two things i see affecting typescript

### Expected behavior

as above

### Screenshots

https://github.com/AstroNvim/astrocommunity/assets/36803168/dbbd7935-c9b3-4f90-8ece-593c10fb6150

**Comment by Uzaaft** [comment]
Are you expecting the result to be:
```html
<FaPrint/>
```
or
```html
<FaPrint>
{children}
</FaPrint>
```

**Comment by Uzaaft** [comment]
Issue with nvim-ts-autotag. 
https://github.com/windwp/nvim-ts-autotag/issues/125
Not an issue with astrocom itself.
@mehalter Would it be appropriate to quick fix this in astrocom, while upstream hasn't fixed the issue?

**Comment by Uzaaft** [comment]
Fix: 
Add to config:
```lua
{"windwp/nvim-ts-autotag",
opts = {
autotag = {
	enable = true,
	enable_rename = true,
	enable_close_on_slash = false,
		}
	}
}
```

**Comment by mehalter** [comment]
Yeah I think it's fine to fix it here and put a Todo comment to remove it later and link to issue

**Comment by Uzaaft** [comment]
Great, I'll add it when I got time. @jay-babu  Feel free to open a PR   if you'd like, I might be busy the next day or so

**Comment by jay-babu** [comment]
i realized this is not in astrocommunity. it should be changed here? https://github.com/AstroNvim/AstroNvim/blob/1910b86d3df873bea4f880f9299dbf66fe1e65fe/lua/plugins/treesitter.lua#L6
