### ISSUE TITLE
Astrocommunity.pack.julia does no create a julia lsp in a newly created file in vim with julia file type.

### ISSUE THREAD

**Issue by divital-coder** [AstroNvim/astrocommunity#520]
Wanted to integrate julia community package by importing it in the community.lua config file, but even after the julia lsp installation being successful, the lsp does not run or give code suggestions while i create a new julia file in astronvim.
Since the "astrocommunity.pack.julia" had requirements for installation of julia to path and being an executable, done that too.
Infact, installed the LanguageServer package with the juli REPL using Pkg.

**Comment by divital-coder** [comment]
Any help would be appreciated 🙂

**Comment by Uzaaft** [comment]
Is the Lsp attached when you open the newly created file?

**Comment by Uzaaft** [comment]
Can't reproduce, works fine for me. :)
