### ISSUE TITLE
DEV plugins

### ISSUE THREAD

**Issue by xsa-dev** [AstroNvim/astrocommunity#522]
### Is your feature related to a problem?

Yes, I didn’t find it in the program (it’s either missing or very difficult)
Hard to manipulate file system and containers

### Describe the new feature

It would help to add to the base package:
- filemanger (like mc)
- docker (like lazydocker)

### Additional context

Thanks, folks!

**Comment by Uzaaft** [comment]
It's not clear what this issue is asking for.
