### ISSUE TITLE
Git-Worktree community plugin

### ISSUE THREAD

**Issue by enthusiva** [AstroNvim/astrocommunity#529]
### Describe the new feature

please add git worktree plugin under git category. https://github.com/ThePrimeagen/git-worktree.nvim

**Comment by Uzaaft** [comment]
Feel free to open a PR. :)

**Comment by Uzaaft** [comment]
Next time, we would appreciate it if you created a PR instead of just filing an issue. :) @enthusiva

**Comment by Uzaaft** [comment]
> Sorry about that. Git-worktree repo has some open issues that prevents it from running along with AstroNvim. I thought astro community can do something about it.

And....you did not give links to that. So I just wasted my time
