### ISSUE TITLE
hardtime-nvim disables arrow keys on neo-tree-popup

### ISSUE THREAD

**Issue by peeeyow** [AstroNvim/astrocommunity#530]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Fedora 38

### Terminal/GUI

kitty

### Describe the bug

Only arrow keys are allowed to move the cursor when renaming things on the `neo-tree-popup` filetypes. hardtime-nvim must be disabled in this filetype just like how the [`neo-tree`](https://github.com/AstroNvim/astrocommunity/blob/1773b89d0c244bc514ba302df7bc91fd0da45e50/lua/astrocommunity/workflow/hardtime-nvim/init.lua#L31C17-L31C17) is included in the `disabled_filetypes`

### Steps to Reproduce

1. Include the following in your config
    ```lua
    {
      "AstroNvim/astrocommunity",
      { import = "astrocommunity.workflow.hardtime-nvim" },
    }
    ```
1. Open `neo-tree`
1. Rename one of the files/directories. A pop up will appear and if you want to move the cursor using `<LEFT>` or `<RIGHT>` keys it will say that the keys are disabled.

### Expected behavior

I must be able to use the my left and right arrow keys in the `neo-tree-popup`.

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/69317890/38221969-cfea-483a-bbd4-bd05db88539e)

**Comment by Uzaaft** [comment]
You might have to add neo-tree as a disabled filetproduksjon, see https://github.com/m4xshen/hardtime.nvim/issues/33

**Comment by peeeyow** [comment]
> You might have to add neo-tree as a disabled filetproduksjon, see [m4xshen/hardtime.nvim#33](https://github.com/m4xshen/hardtime.nvim/issues/33)

It's already present in the current [setup](https://github.com/peeeyow/astrocommunity/blob/1773b89d0c244bc514ba302df7bc91fd0da45e50/lua/astrocommunity/workflow/hardtime-nvim/init.lua#L31). What I want to add is the `neo-tree-popup` filetype (this is different from `neo-tree`). I believe it's logical to add this since the plugin is also disabled in `neo-tree` .

**Comment by Uzaaft** [comment]
Appreciate the PR!
