### ISSUE TITLE
cpp.pack clangd_extensions: BREAKING CHANGE: redo config, make inlay hints manual

### ISSUE THREAD

**Issue by doupongzeng** [AstroNvim/astrocommunity#542]
### Is your feature related to a problem?
[BREAKING CHANGE: redo config, make inlay hints manual](https://github.com/p00f/clangd_extensions.nvim/commit/643fd64f908eaa599469cb0af9a204a0dbd3b7e2)
clangd_extensions make inlay hints manual and old pack.cpp seems to work not well, I use `"<cmd>ClangdToggleInlayHints<cr>"` only to show the current line, I also changed clangd_extensions' config inlay_hints.only_current_line = false, my neovim version is 0.10.0

### Describe the new feature

make config suitable new clangd_extensions, and can Toggle entire file inlay hints

**Comment by Uzaaft** [comment]
I believe mehalter fixed the cpp pack in this commit: https://github.com/AstroNvim/astrocommunity/commit/37126181ce621e4257478881ae21a1b54d2c048b and improved upon it here: 
ba3ea511fbc3fa8113485859681ce5fe3c2d6d4e

**Comment by Uzaaft** [comment]
@doupongzeng  I believe this might be an issue with your local config? I'm pretty sure it isn't because of astrocom

**Comment by doupongzeng** [comment]
> @doupongzeng I believe this might be an issue with your local config? I'm pretty sure it isn't because of astrocom

Thanks, I upgrade my config [user/lsp/config/clangd.lua](https://github.com/doupongzeng/AstroNvim_config/blob/main/lsp/config/clangd.lua)
```
return {
  on_attach = function (_client, bufnr)
    vim.lsp.inlay_hint(bufnr, true)
  end,
}
```
