### ISSUE TITLE
vim tex indentation in \item environments

### ISSUE THREAD

**Issue by isentropic** [AstroNvim/astrocommunity#543]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 release

### Operating system/version

macOS 13.4.1 (c) 

### Terminal/GUI

iTerm

### Describe the bug

I have enable community vimtex installation, but the indentation is very weird when working inside `\item` environments. Possibly related issues:
https://www.reddit.com/r/neovim/comments/zcy4wj/auto_indent_in_latex/
https://github.com/lervag/vimtex/issues/949
https://github.com/lervag/vimtex/issues/2382

### Steps to Reproduce

open '\item' like environment in latex file:
```
\begin{enumerate}
\item Calculate ... (press enter here)
\end{enumerate}
```

### Expected behavior

Indentation should weirdly right align

### Screenshots

<img width="956" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/24591123/d213fd48-0a2e-42fb-b9bb-fa5e87d3e5d9">

**Comment by Uzaaft** [comment]
I believe this is an user error issue, so I’m going ahead and closing it.
@isentropic  do you have any custom code in your config that could be relevant in your config?
