### ISSUE TITLE
Hardtime.nvim not disabled on dressinginput buffer

### ISSUE THREAD

**Issue by peeeyow** [AstroNvim/astrocommunity#548]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Fedora 38

### Terminal/GUI

kitty

### Describe the bug

`Hardtime.nvim`  is active on `dressinginput` popup.

### Steps to Reproduce

1. Using default astronvim keybindings. Go to a symbol that is renameable.
2. Rename it using `<leader>lr`.
3. Move cursor using arrow keys.

### Expected behavior

`Hardtime.nvim` must be disabled for `dressinginput` buffer

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/69317890/e2f59107-a504-48a7-86fe-8cd630154571)

**Comment by Uzaaft** [comment]
Isn't the idea that you should use something like:
`<C-o>**keypress**` combo. Liek if I need to go back one word, it'll be;
`<C-o>b`

**Comment by peeeyow** [comment]
> Isn't the idea that you should use something like: `<C-o>**keypress**` combo. Liek if I need to go back one word, it'll be; `<C-o>b`

The config already disables `hardtime.nvim` on similar filetypes. Just aligning configurations. But yea, you can do that if you want to.

**Comment by Uzaaft** [comment]
I believe it goes against the spirit of `hardtime.nvim` 🤷🏾‍♂️
