### ISSUE TITLE
Java root_dir not found

### ISSUE THREAD

**Issue by zedgamer9128** [AstroNvim/astrocommunity#550]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9,1

### Operating system/version

Windows 11 ArchWSL

### Terminal/GUI

Windows Terminal

### Describe the bug

Opening a java file shows root_dir not found i know i have to create a project but can it be so that we can open a single java file like changing the root_dir option to include *.java so we can get full functionality of jdtls

### Steps to Reproduce

1. Open a java file
2. See the warning

### Expected behavior

To open a java file and get full experience of jdtls with any project dir

**Comment by Uzaaft** [comment]
See the docs of https://github.com/mfussenegger/nvim-jdtls to see what single file support enables(only syntax errors)
