### ISSUE TITLE
Configure neo-test buffers

### ISSUE THREAD

**Issue by pavkam** [AstroNvim/astrocommunity#559]
### Is your feature related to a problem?

The floats/side-buf for `neo-test` can be improved by:
1. preventing the test summary buffer from being replaced by other buffers (when selecting another file from `neo-tree` for example,
2. adding `q` to close the floats to `neo-test` floatsPreventing

### Describe the new feature

I use this code in my config:
```
vim.api.nvim_create_autocmd({ "BufEnter" }, {
  desc = "Prevent test summary buffer from being replaced",
  group = vim.api.nvim_create_augroup("prevent_test_summary_buffer_replace", { clear = true }),
  callback = function(args)
    local new_file_name = vim.fn.resolve(vim.fn.expand "%")
    local current_file_name = vim.fn.resolve(vim.fn.expand "#")

    if current_file_name == "Neotest Summary" and new_file_name ~= current_file_name then
        vim.cmd('b#')
    end
  end,
})

vim.api.nvim_create_autocmd("BufEnter", {
  desc = "Make q close neo-test windows",
  group = vim.api.nvim_create_augroup("neotest_q_close_windows", { clear = true }),
  callback = function(args)
    local file_type = vim.api.nvim_get_option_value("filetype", { buf = args.buf })
    if file_type == 'neotest-output' and vim.fn.maparg("q", "n") == "" then
      vim.keymap.set("n", "q", "<cmd>close<cr>", {
        desc = "Close window",
        buffer = args.buf,
        silent = true,
        nowait = true,
      })
    end
  end,
})
```

### Additional context

I am not a `neovim` wizard so my auto-commands might not be the best :) But hopefully, something similar can be added to the `neotest` pack.

**Comment by Uzaaft** [comment]
This is a user-level enhancement, not something that can/should be delivered to most astronvim user as part of the pack.

**Comment by pavkam** [comment]
Astronvim has 'q' management for DAP windows built in. Not sure how that's different but it's OK to have user do it as well. Cheers.
