### ISSUE TITLE
Rust support for Termux

### ISSUE THREAD

**Issue by wangxiaoerYah** [AstroNvim/astrocommunity#565]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

Android

### Terminal/GUI

Termux

### Describe the bug

On Termux, use astrocommunity.pack.rust, Prompt rust_analyzer does not support this platform.

### Steps to Reproduce

Install in Termux astrocommunity.pack.rust

### Expected behavior

There is a rust_analyzer available for Android through its package manager on Termux. Is it possible to check whether the system path contains rust_analyzer before installing it, instead of installing it directly? Or set an optional option to check system dependencies.

**Comment by Uzaaft** [comment]
I'm sorry, I don't understand what you want to point out with this issue

**Comment by Uzaaft** [comment]
That's not a question that we can answer. Your best bet is to ask the RA maintainers.
