### ISSUE TITLE
Transparent.nvim incorrect category

### ISSUE THREAD

**Issue by mehalter** [AstroNvim/astrocommunity#567]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Arch linux

### Terminal/GUI

Kitty

### Describe the bug

Transparent.nvim is added to the incorrect category. Not sure who added it or reviewed the PR but it's in the utility category which is not aligned with the categories we have as well as what is in Neovim craft. We should make sure the plugins are getting added to the correct category as described in the contribution guidelines.

Incorrect location: https://github.com/AstroNvim/astrocommunity/tree/main/lua%2Fastrocommunity%2Futility%2Ftransparent-nvim

Neovim Craft: https://neovimcraft.com/plugin/xiyaowong/nvim-transparent

### Steps to Reproduce

N/A

### Expected behavior

transparent.nvim should be in the color category.

**Comment by Uzaaft** [comment]
My bad. Fixing it :)
