### ISSUE TITLE
Add rafi/neoconf-venom.nvim to python pack

### ISSUE THREAD

**Issue by kraxli** [AstroNvim/astrocommunity#569]
### Is your feature related to a problem?

Yes, diagnostic features for python do not respect the activated virtual environment (e.g. by poetry)

### Describe the new feature

Adding https://github.com/rafi/neoconf-venom.nvim to support lsp and dap including diagnostics.

**Comment by Uzaaft** [comment]
I'm not sure what you're doing locally. For me, spawning a shell with poetry before entering nvim ends up with nvim using that environment just fine.

**Comment by Uzaaft** [comment]
Gonna close this one as it doesn't seem like an issue for me.
