### ISSUE TITLE
Can't revert nvim-devdocs previewer_cmd from glow back to default

### ISSUE THREAD

**Issue by oryband** [AstroNvim/astrocommunity#572]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

Terminal

### Describe the bug

Settings the following still uses glow if it is available, even though `previewer_cmd = nil`

```lua
      { import = "astrocommunity.editing-support.nvim-devdocs" },
      { "nvim-devdocs", opts = { previewer_cmd = nil, picker_cmd = false } },
```

### Steps to Reproduce

1. Use the above configuration
2. Open a dev docs window

### Expected behavior

Shouldn't use glow but show markdown code instead.

**Comment by oryband** [comment]
@Uzaaft thanks, i tried it and it works. Looks like an astrocommunity issue. This is how I managed to force it with default plugin:
```lua
    {
      "luckasRanarison/nvim-devdocs",
      dependencies = {
        "nvim-lua/plenary.nvim",
        "nvim-telescope/telescope.nvim",
        "nvim-treesitter/nvim-treesitter",
      },
      keys = {
        { "<leader>d", "<cmd>DevdocsOpenCurrentFloat<CR>", desc = "Find Devdocs for current file", mode = { "n" } },
        { "<leader>D", "<cmd>DevdocsOpenFloat<CR>", desc = "Find Devdocs", mode = { "n" } },
      },
      opts = function(_, opts)
        opts.previewer_cmd = nil
      end,
    },
```
This is how I was able to override it **with** astrocommunity plugin:
```lua
      { import = "astrocommunity.editing-support.nvim-devdocs" },
      { "nvim-devdocs",
         -- THIS DOESN'T WORK
        -- opts = { 
        --   previewer_cmd = nil,
        --   picker_cmd = false,
        --   wrap = true,
        --   ensure_installed = { "python-3.10", "clojure-1.11", "docker", "bash", "markdown", "http" }
        -- },
        -- BUT THIS WORKS
        opts = function(_, opts)
          opts.previewer_cmd = nil
          opts.picker_cmd = false
        end
      },
```

**Comment by Uzaaft** [comment]
Your example isn't using the short-hand.
Try and use the full path, i.e       `"luckasRanarison/nvim-devdocs"` there as well

**Comment by Uzaaft** [comment]
closing until we get a respons.
