### ISSUE TITLE
Can't setup treesj keymaps, interefers with multi cursors plugin.

### ISSUE THREAD

**Issue by oryband** [AstroNvim/astrocommunity#573]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

Terminal

### Describe the bug

The following sets both the default `<leader>m` and my own (`<leader>s`) mappings. Looks like `use_default_keymaps=false` isn't registered. removing the `opts` section should still set it to false  but also doesn't make any difference https://github.com/AstroNvim/astrocommunity/blob/59df499a5730504d1cad22073d9cd4a06ca03e0f/lua/astrocommunity/editing-support/treesj/init.lua#L5

`<leader>m` interferes with multicursors. https://github.com/AstroNvim/astrocommunity/blob/59df499a5730504d1cad22073d9cd4a06ca03e0f/lua/astrocommunity/editing-support/multicursors-nvim/init.lua#L9
```lua
      { import = "astrocommunity.editing-support.treesj" },
      { "treesj", opts = { use_default_keymaps = false }, keys = { { "<leader>s", "<CMD>TSJToggle<CR>", desc = "Toggle Treesitter Join" } } },
```

### Steps to Reproduce

1. Set the above configuration
2. press `<leader>m` or `<leader>s` and see both are executing the toggle mapping.

### Expected behavior

`<leader>m` shouldn't be registered.

**Comment by oryband** [comment]
Hi @Uzaaft . This works:
```lua
  -- add which-key mappings to astronvim
  mappings = {
    n = {
      ["<leader>s"] = { "<CMD>TSJToggle<CR>", desc = "Toggle Treesitter Join" },
    },
  },

-- ...

    -- manually add treesj plugin and disable default keymaps
    {
      'Wansmer/treesj',
      lazy = false,
      dependencies = { 'nvim-treesitter/nvim-treesitter' },
      config = function()
        require('treesj').setup({use_default_keymaps = false})
      end,
    },

```
But this doesn't, even by replacing `opts = {..}` with `opts = function(_, opts) .. end` like i did in https://github.com/AstroNvim/astrocommunity/issues/572#issuecomment-1722847387

**Comment by Uzaaft** [comment]
Like I said, try and use the whole plugin path(github_repo_owner/plugin_name) instead of the shorthand.

**Comment by Uzaaft** [comment]
closing until we get a respons.
