### ISSUE TITLE
Clojure pack is autoformatting files on buffer open

### ISSUE THREAD

**Issue by oryband** [AstroNvim/astrocommunity#574]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

Terminal

### Describe the bug

Opening any clojure .clj file automatically formats it (when the buffer is opened) without saving the buffer. How can I disable it? This is implicitly changing my code.

### Steps to Reproduce

Setup a lein project and create a clojure .clj file with some code that can be formatted eg space between parentheses `(+ 1 1     )`. save it, close nvim, then reopen - the buffer is autoformatted

### Expected behavior

The file should not be modified.

**Comment by Uzaaft** [comment]
There isn't a null_ls formatter, so I think it's the LSP that does this. Your best bet would be to see if the docs/issues/discussions of clojure_lsp talks about this behaviour.
