### ISSUE TITLE
Neo-Tree freezes when netman.nvim (remote-development/netman-nvim) is enabled

### ISSUE THREAD

**Issue by yoshphys** [AstroNvim/astrocommunity#575]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.2, Build type: Release

### Operating system/version

macOS 13.5.2

### Terminal/GUI

iTerm2

### Describe the bug

Neovim freezes after trying to use Neo-tree with netman.nvim enabled.

### Steps to Reproduce

1. Adding a line in `.config/nvim/lua/user/plugins/community.lua`
```lua
  { import = "astrocommunity.remote-development.netman-nvim"},
```
2. Pressing `<Space>+e` or executing the command `:Neotree`

### Expected behavior

Neovim freezes. No command is accepted.

### Additional Context

I put the following line in `.config/nvim/lua/user/plugins/community.lua` a long time ago.
```lua
  { import = "astrocommunity.remote-development.netman-nvim"},
```
I hadn't used Neo-tree for a while, so I wasn't aware netman.nvim conflicts with Neo-tree.
And today I found that Neo-tree freezes with netman-nvim enabled.
There was no change even after update AstroNvim and plugins.
Now the version of AstroNvim is v3.36.9-2-ge76740a.
I am not sure which version of AstroNvim I was using when I first noticed this problem.

After I disabled netman.nvim as folliwing, Neo-tree started to work.
```lua
  { import = "astrocommunity.remote-development.netman-nvim", enable = false},
```
I don't use netman-nvim anymore because I was not able to realize what I wanted with it.
So there's no problem for me to disable it now.

Anyway, I guess we need to specify some special options in `community.lua`, or we should give up using netman-nvim.

**Comment by Uzaaft** [comment]
Do you have: 
<img width="434" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/48220549/708aa4b1-ab5f-44be-b3b2-982584716135">

**Comment by luxus** [comment]
you need docker or podman that is symlinked to docker :D

**Comment by Uzaaft** [comment]
@luxus next time, I'd mark it as won't fix or something similar, when it's lot really an issue with astrocom
