### ISSUE TITLE
Neosolarized theme (suggestion)

### ISSUE THREAD

**Issue by gmmoose20** [AstroNvim/astrocommunity#577]
### Is your feature related to a problem?

It's not a bug actually but a suggestion.. add the colorbuddy repo inside the init.lua of neosolarized.lua since it requires it in order to run the theme. Really liked the theme just had to install the colorbuddy separately though.

### Describe the new feature

Just a suggestion to may be it can just come with it automatically upon installing the theme 😅

### Additional context

sorry for posting under the bug section just delete it thanks.. 😅

**Comment by Uzaaft** [comment]
Where is this mentioned in the docs of the plugins?

**Comment by Uzaaft** [comment]
Next time, instead of creating an issue, we would prefer it if you create a PR. :)
