### ISSUE TITLE
Python pack contains both ruff and isort. Is this necessary

### ISSUE THREAD

**Issue by dpriedel** [AstroNvim/astrocommunity#592]
Since ruff includes isort functionality, is it necessary to also include the isort module in the pack?

This seems redundant.

**Comment by Uzaaft** [comment]
We're discussing changes to the python pack, including removing/splitting ruff into a seperate pack.

**Comment by Uzaaft** [comment]
@dpriedel  #603 should solve this. Could you be so kind and test both versions?

**Comment by dpriedel** [comment]
Hi


I tried both versions and both seemed to work OK for me.


Thanks !

**Comment by HCHogan** [comment]
Hi!
The python-ruff pack works well but it seems to have duplicate diagnostic messages, one from pyright and one from ruff.
Here's the screenshot:
<img width="927" alt="Screenshot 2023-10-19 at 19 41 35" src="https://github.com/AstroNvim/astrocommunity/assets/78535316/8d4ca8c4-dbef-4e9d-a9bf-7cb8c484f750">

**Comment by Uzaaft** [comment]
> Hi! The python-ruff pack works well but it seems to have duplicate diagnostic messages, one from pyright and one from ruff. Here's the screenshot: <img alt="Screenshot 2023-10-19 at 19 41 35" width="927" src="https://user-images.githubusercontent.com/78535316/276601282-8d4ca8c4-dbef-4e9d-a9bf-7cb8c484f750.png">

Ruff-lsp is intended to work alongside another LSP due to it not having go-to stuff. See the docs for this.
