### ISSUE TITLE
Community Indent Blankline

### ISSUE THREAD

**Issue by Dev-Aulotte** [AstroNvim/astrocommunity#596]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

macOS 14.0

### Terminal/GUI

ITerm2

### Describe the bug

The opts did not match the new implementation of the plugin, so an error is trigger.

### Steps to Reproduce

1. Install the plugin from community
2. Reload nvim
3. open a file

### Expected behavior

Failed to run `config` for indent-blankline.nvim

.../share/nvim/lazy/indent-blankline.nvim/lua/ibl/utils.lua:18: 'show_current_context' is not a valid key of ibl.config

# stacktrace:
  - /indent-blankline.nvim/lua/ibl/utils.lua:18 _in_ **validate**
  - /indent-blankline.nvim/lua/ibl/config.lua:111 _in_ **validate_config**
  - /indent-blankline.nvim/lua/ibl/config.lua:271 _in_ **set_config**
  - /indent-blankline.nvim/lua/ibl/init.lua:59 _in_ **setup**
  - lua/astronvim/utils/init.lua:145

**Comment by Uzaaft** [comment]
Feel free to open a PR. :)
