### ISSUE TITLE
nvim-transparent error with nvim-notify

### ISSUE THREAD

**Issue by acarl005** [AstroNvim/astrocommunity#598]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 14.0

### Terminal/GUI

Warp

### Describe the bug

I'm using `astrocommunity.color.nvim-transparent`. I see a warning every time a notification appears.

### Steps to Reproduce

```
{
      "AstroNvim/astrocommunity",
      { import = "astrocommunity.color.nvim-transparent" },
}
```
Then, do something to trigger an `nvim-notify` notification, like `<leader>pa`.

### Expected behavior

That warning should not appear.

### Screenshots

<img width="978" alt="Screenshot 2023-10-07 at 1 24 55 PM" src="https://github.com/AstroNvim/astrocommunity/assets/8334252/3f8945e7-3691-4097-bf3a-4bd7f8ff28ab">

**Comment by Uzaaft** [comment]
You could add the color to the nvim-notify opts, like:
```
opts = {
  -- other stuff
  background_colour = "#000000"
}
```
If that doesn't work, try:
```lua
vim.api.nvim_set_hl(0, 'NotifyBackground', vim.api.nvim_get_hl_by_name('Normal', true))
```

**Comment by acarl005** [comment]
Thanks, setting the background color manually via `background_colour` silences the warning.

**Comment by Uzaaft** [comment]
It could be something we can add into the config. Any thoughts? @owittek I can create the PR

**Comment by owittek** [comment]
sure thing, sounds like a sane default for those who want to use that plugin
