### ISSUE TITLE
How do I disable LTEX messages with Noice.nvim

### ISSUE THREAD

**Issue by TheKamboy** [AstroNvim/astrocommunity#604]
### Checklist

- [x] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Ubuntu WSL

### Terminal/GUI

Alacritty

### Describe the bug

I have searched everywhere to fix this, but nothing I have tried works

### Steps to Reproduce

Use Noice.nvim and LTEX

### Expected behavior

Online Snippets disable LTEX messages

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/89111294/4339b752-5bb3-4f73-8174-4efbe84cb7b2)

**Comment by TheKamboy** [comment]
Where should I put this in my user config that would work

```
vim.diagnostic.config({
     update_in_insert = false
  })
```

This is a snippet I want to use but I can't figure out where to put it

**Comment by TheKamboy** [comment]
I tried putting it into the diagnostics in the config, and it didn't work

**Comment by Uzaaft** [comment]
What is your config?

**Comment by TheKamboy** [comment]
@Uzaaft This isn't a config question now, because I have tries everything and it won't work. It seems more like a bug.

**Comment by Uzaaft** [comment]
It is.
1. you havent provided a config
2. We dont have anything called ltex in this repository(whatever ltex is)

**Comment by TheKamboy** [comment]
Sorry. [Here's the link to my config.](https://github.com/TheKamboy/astronvim_config/tree/main)

LTEX is a lsp for markdown which checks grammar, but it spams `Checking Document` messages when you type.

That's why I'm trying to disable `update_in_insert` for vim diagnostics, but when I try, it doesn't work.

**Comment by TheKamboy** [comment]
@Uzaaft

**Comment by Uzaaft** [comment]
> Sorry. [Here's the link to my config.](https://github.com/TheKamboy/astronvim_config/tree/main?rgh-link-date=2023-10-14T15%3A18%3A37Z)
> 
> LTEX is a lsp for markdown which checks grammar, but it spams `Checking Document` messages when you type.
> 
> That's why I'm trying to disable `update_in_insert` for vim diagnostics, but when I try, it doesn't work.

You just proved my point. LTEX isn't in astrocom, so this is a configuration issue, not a bug in astrocom. :)

**Comment by TheKamboy** [comment]
Ok, cool.

I figured it out anyway.

**Comment by Uzaaft** [comment]
> Ok, cool.
> 
> I figured it out anyway.

👏🏾
