### ISSUE TITLE
cpp pack contains both clangd and clang-format

### ISSUE THREAD

**Issue by dpriedel** [AstroNvim/astrocommunity#612]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Manjaro Linux

### Terminal/GUI

tilix

### Describe the bug

The cpp pack contains both clangd and clang-format.  clangd includes the clang-format functionality [https://clangd.llvm.org/features.html](url) so having both seems unnecessary.

### Steps to Reproduce

1. install cpp pack
2. edit cpp file
3. both clangd and clang-format are enabled.

### Expected behavior

Only clangd is required to have lsp and code formatting

**Comment by Uzaaft** [comment]
Feel free to open a PR. :)

**Comment by dpriedel** [comment]
I haven't done that before but I can give it a try later today

**Comment by dpriedel** [comment]
Thanks!!
I'm afraid I got busy and didn't have time to try to do this.

**Comment by Uzaaft** [comment]
No worries. I fixed it :)
