### ISSUE TITLE
feat(note-taking): add `neorg` keybinds to work with default astronvim keybindings

### ISSUE THREAD

**Issue by Clumsy-Coder** [AstroNvim/astrocommunity#625]
### Is your feature related to a problem?

When loading [neorg](https://github.com/nvim-neorg/neorg) in Astronvim, some of the keybindings are being used by Astronvim default keybindings. Would be nice to add config to remap the neorg keybindings to work with Astronvim

### Describe the new feature

Having the default neorg keybindings remapped to work with astronvim keybindings

### Additional context

Using the config from this repo

https://github.com/AstroNvim/astrocommunity/blob/d4a55203ea818ec8fb31cd3fad6030bd8c67c969/lua/astrocommunity/note-taking/neorg/init.lua#L1-L26

**Comment by Uzaaft** [comment]
Feel free to come up with a proposal :)

**Comment by luxus** [comment]
@Clumsy-Coder are you still using astronvim?
how did you end up binding the keys or can we close this?

**Comment by Clumsy-Coder** [comment]
You can close it. I don't use it anymore
