### ISSUE TITLE
Configure `jdtls` runtime version

### ISSUE THREAD

**Issue by Ralghs** [AstroNvim/astrocommunity#627]
I am trying to use AstroNvim for my Java project. I followed the instructions and added `{ import = "astrocommunity.pack.java" }` to my `.config/nvim/lua/user/init.lua` file. When I open a Java file, `Client 1 quit with exit code 1 and signal 0` pops up on the top right and the jdtls does not seem to be working properly. 

This is the my jdtls log:

```
[START][2023-11-02 11:43:19] LSP logging initiated
[ERROR][2023-11-02 11:43:19] .../vim/lsp/rpc.lua:733	"rpc"	"java"	"stderr"	"Unrecognized option: --add-modules=ALL-SYSTEM\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"
[ERROR][2023-11-02 11:43:24] .../vim/lsp/rpc.lua:733	"rpc"	"java"	"stderr"	"Unrecognized option: --add-modules=ALL-SYSTEM\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"
[ERROR][2023-11-02 11:43:32] .../vim/lsp/rpc.lua:733	"rpc"	"java"	"stderr"	"Unrecognized option: --add-modules=ALL-SYSTEM\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"
[START][2023-11-02 11:44:23] LSP logging initiated
[ERROR][2023-11-02 11:44:23] .../vim/lsp/rpc.lua:733	"rpc"	"java"	"stderr"	"Unrecognized option: --add-modules=ALL-SYSTEM\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"
[ERROR][2023-11-02 11:44:28] .../vim/lsp/rpc.lua:733	"rpc"	"java"	"stderr"	"Unrecognized option: --add-modules=ALL-SYSTEM\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"
[ERROR][2023-11-02 11:47:07] .../vim/lsp/rpc.lua:733	"rpc"	"java"	"stderr"	"Unrecognized option: --add-modules=ALL-SYSTEM\nError: Could not create the Java Virtual Machine.\nError: A fatal exception has occurred. Program will exit.\n"
```
Does anyone know how to solve this problem?

**Comment by Uzaaft** [comment]
1. If you were to open a issue, please provide the right logs.
2. This is not the place to ask for user setup help. Ask in the github

**Comment by mehalter** [comment]
@Uzaaft not sure why this was closed since it is directly asking about a potential bug in an AstroCommunity entry.

Seems to be regarding this line: https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/java/init.lua#L70

**Comment by mehalter** [comment]
Sorry for the confusion here @Ralghs ! You definitely asked this in the correct place and did provide the correct logs with the necessary information!

**Comment by mehalter** [comment]
Out of curiosity, what Java version do you have in your system?

**Comment by Ralghs** [comment]
> Out of curiosity, what Java version do you have in your system?

I have both Java8 and Java17 installed but javac -version prints javac 1.8.0_361. I never use Java 17. If you think this might be the issue I can uninstall Java17 and give neovim another go?

**Comment by mehalter** [comment]
It looks like `jdtls` requires Java 11+. Here is a relevant issue upstream:

https://github.com/mfussenegger/nvim-jdtls/issues/205#issuecomment-1001997421

**Comment by mehalter** [comment]
Yeah java 8 will not be usable since the language server doesn't support it. You'll need to update your java version!

**Comment by Ralghs** [comment]
Ahh, I remember why I have Java17 even though all my projects use Java8. It's probably because jdtls has to start with Java 11+ but can run the Java server with a Java 8 runtime and I was trying to do what this guy did in this issue.
#mfussenegger/nvim-jdtls#44

Is it possible for me to maybe download the https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/java/init.lua 
file and configure it locally?

**Comment by Uzaaft** [comment]
> @Uzaaft not sure why this was closed since it is directly asking about a potential bug in an AstroCommunity entry.
> 
> Seems to be regarding this line: [`main`/lua/astrocommunity/pack/java/init.lua#L70](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/java/init.lua?rgh-link-date=2023-11-06T03%3A59%3A42Z#L70)

Didn't seem that for me when I looked at the issue, it seemed like a user issue(which it appeared to be), so I closed it since that's outside of the scope of astrocom.

**Comment by mehalter** [comment]
Ah I see @Uzaaft , that was pretty poorly communicated as it made it seem like it was an upstream issue in AstroNvim and not on the user side. This does seem like something that should be addressed. Or at least if you found a reason it shouldn't be addressed then to mention that reason.

**Comment by mehalter** [comment]
@Ralghs based on how the `nvim-jdtls` plugin is set up, it is configured through the `opts` table. So you can customize the installation in the normal way that is described in the README on this repo. Just customize the `opts` table for the plugin you are importing after the import is made. Something along the lines of this in your plugins:

```lua
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.java" },
  {
    "mfussenegger/nvim-jdtls",
    opts = {
      settings = {
        java = {
          configuration = {
            runtimes = {
              {
                name = "JavaSE-11",
                path = "/usr/lib/jvm/java-11-openjdk/",
              },
            },
          },
        },
      },
    },
  },
```
