### ISSUE TITLE
nvim-devdocs preview & glow issue with default plugin config

### ISSUE THREAD

**Issue by silentjay** [AstroNvim/astrocommunity#629]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

endevourOS/Arch

### Terminal/GUI

xcfe terminal

### Describe the bug

The preview doesn't work with glow as configured. No idea if this is specific to my system or not. Glow is on the PATH and works fine in the nvim-devdocs post selection window.

Readme states: "Astrocommunity note: [glow](https://github.com/charmbracelet/glow) render will work out of the box if you have it on your PATH"

I don't know if this is the issue in the init.lua:

`previewer_cmd = vim.fn.executable "glow" == 1 and "glow" or nil`

but overriding that with `previewer_cmd = glow` enables glow in the preview window as expected so I believe this an issue with plugin config.

### Steps to Reproduce

.

### Expected behavior

.

**Comment by Uzaaft** [comment]
Have you followed the devdocs guide and set it up correctly?

**Comment by Uzaaft** [comment]
I tried not on both mac and linux. Seems to me to be a user issue.

**Comment by silentjay** [comment]
As I mentioned initially I got it working with extra configuration.  However the readme states 

"Astrocommunity note: [glow][glow-repo] render will work out of the box if you have it on your PATH"

The preview function of devdocs (as currently configured in the init.lua file) doesn't work with glow out the box so i'm just trying to be helpful.

**Comment by Uzaaft** [comment]
And what I'm trying to say is that I tried on two systems, who didn't have glow initially, and I got it working with the plugin spec in astronvim.
Do you have an up to date glow?

**Comment by Uzaaft** [comment]
Friendly reminder @silentjay

**Comment by silentjay** [comment]
Glow up to date and installed direct via pacman not via the astrocommunity plugin. 

I'm closing this as stated in the original comment I had already fixed it by overriding the plugin config.

**Comment by silentjay** [comment]
I've come back to this issue on a fresh astronvim setup. 

Initially using this community plugin with zero config: glow does not work in the telescope picker preview window but does work in the float after selection

![image](https://github.com/user-attachments/assets/1f0f89aa-d687-4661-b48e-36c1c59da976)

Remove the community plugin and install nvim-devdocs direct with the default lazy config 

```  "luckasRanarison/nvim-devdocs",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
    "nvim-treesitter/nvim-treesitter",
  },
  opts = {}```
  
  and glow in the telescope picker preview works as expected as does the selection float
  
  
![image](https://github.com/user-attachments/assets/15707261-7da2-4413-baa1-cf23860e35c6)
