### ISSUE TITLE
error:  Error setting up colorscheme: `nvim-juliana`

### ISSUE THREAD

**Issue by zeromask1337** [AstroNvim/astrocommunity#641]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macos 13.5

### Terminal/GUI

alacritty

### Describe the bug

I get error after installing 'nvim-juliana' theme

```
Highlight group 'NotifyBackground' has no background highlight
Please provide an RGB hex value or highlight group with a background value for 'background_colour' option.
This is the colour that will be used for 100% transparency.

require("notify").setup({
  background_colour = "#000000",
})

Defaulting to #000000
```

### Steps to Reproduce

1. Install nvim-juliana via config file 
```lua
-- ./community.lua
return {
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.colorscheme.nvim-juliana" },
}
```

2. Turn it on in init file
```lua
-- ./init.lua

return {
  -- Set colorscheme to use
  colorscheme = "nvim-juliana",
```

3. Restart vim and get error

### Expected behavior

Working theme

### Additional Context

Looks like original repo got updated, and started conflicting with current config

**Comment by Uzaaft** [comment]
This seems for me to be an user-error. You're using the wrong colorscheme name when setting your colorscheme. Please see the nvim-juliana repo for the right name

**Comment by zeromask1337** [comment]
It is indeed my mistake. Thank you!
