### ISSUE TITLE
Add typst language pack

### ISSUE THREAD

**Issue by aik2mlj** [AstroNvim/astrocommunity#652]
### Describe the new feature

Perhaps someone is willing to provide the configuration for `.typ` file with [typst-lsp](https://github.com/nvarner/typst-lsp). This would be very handy for typst users!

**Comment by Uzaaft** [comment]
You should just install the lsp and it'll work. 
I assume you're a typst user? If not...why not provide the config yourself?

**Comment by Uzaaft** [comment]
Fixed by https://github.com/AstroNvim/astrocommunity/pull/684
