### ISSUE TITLE
tailwind css pack

### ISSUE THREAD

**Issue by luxus** [AstroNvim/astrocommunity#67]
if someone wants to add a css pack .. that would be wonderful :D

i think that's a good example
https://github.com/elijahmanor/youtube-lazyvim-tailwind/blob/main/lua/plugins/tailwind.lua

**Comment by luxus** [comment]
most done by https://github.com/AstroNvim/astrocommunity/pull/88
colorizer is missing

**Comment by taskylizard** [comment]
This can be closed now.
