### ISSUE TITLE
'rainbow-delimiters-nvim' not loaded when opening a file; have to close and re-open. If set to VeryLazy, jdtls breaks when pressing 'Enter' key.

### ISSUE THREAD

**Issue by av1155** [AstroNvim/astrocommunity#672]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

macOS 14.1.2 23B92 arm64

### Terminal/GUI

iTerm2

### Describe the bug

I am experiencing an issue with the 'rainbow-delimiters-nvim' plugin in my Neovim setup. The problem manifests in two distinct scenarios:

1. Rainbow Delimiters Not Loaded on File Opening:
When I open a file in Neovim, the 'rainbow-delimiters-nvim' plugin does not load automatically when left at default configuration, or when set to User AstroFile, which means that I don't get the expected rainbow delimiter highlighting when i first open a file. To get it to work, I must manually close and reopen the file.

2. Jdtls (Java Language Server) Conflict with 'VeryLazy' Configuration on Java files:
If I set the 'rainbow-delimiters-nvim' plugin to load lazily with the 'VeryLazy' event, the brackets are colored immediately and it fixes the "closing and re-opening" bug. However, I encounter issues with the jdtls client (Java Language Server) when I press the 'Enter' key and the 'rainbow-delimiters-nvim' plugin is set to event = "VeryLazy". This results in the jdtls client generating errors related to buffer attachment, with messages like:

[LSP] Client with id 2 not attached to buffer 15
[LSP] Client with id 2 not attached to buffer 21
[LSP] Client with id 2 not attached to buffer 23
[LSP] Client with id 2 not attached to buffer 25
[LSP] Client with id 2 not attached to buffer 29

(Each message above is one press of the 'Enter' key. The number of the buffer starts low and keeps increasing).

### Steps to Reproduce

1. Set 'rainbow-delimiters-nvim' to event = "VeryLazy" on community.lua like such:

    { import = "astrocommunity.editing-support.rainbow-delimiters-nvim" },
    { -- further customize the options set by the community
        "HiPhish/rainbow-delimiters.nvim",
        event = "VeryLazy",
    },
    
2. Use the Java language pack from the community: 

    { import = "astrocommunity.pack.java" },

3. Open a Java file anywhere, you will see that brackets are colored immediately as they should; however, if you go anywhere in the Java file, go to insert mode, and press the 'Enter' key, you will see the error messages (the buffer number will vary):

[LSP] Client with id 2 not attached to buffer 15
[LSP] Client with id 2 not attached to buffer 21
[LSP] Client with id 2 not attached to buffer 23
[LSP] Client with id 2 not attached to buffer 25
[LSP] Client with id 2 not attached to buffer 29
    
4. If 'rainbow-delimiters-nvim' are not set to event = VeryLazy, and the plugin is left as the community default, this issue with jdtls will not happen. However, the brackets will not be colored unless the buffer is closed and re-opened.

### Expected behavior

In summary, the expected behavior is a smooth and error-free experience when working with both the 'rainbow-delimiters-nvim' plugin and the jdtls client in Neovim. The configuration should be such that plugins load when specified to (VeryLazy for rainbow-delimiters, and default for jdtls) without causing conflicts or errors during regular coding tasks.

### Additional Context

I've provided information about the Neovim setup and the jdtls client configuration below:

Language client log: /Users/andreaventi/.local/state/nvim/lsp.log
 Detected filetype:   java
 
 3 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, bufnr: [4])
 	filetypes:       kotlin, sh, python, dockerfile, javascript, typescript, markdown, typescriptreact, javascriptreact, json, jsonc, bash, zsh, ksh, csh, lua, cs, cpp, cuda, proto, java, c, luau
 	autostart:       false
 	root directory:  /Users/andreaventi/Desktop/testingJDTLS
 	cmd:             <function>
 
 Client: jdtls (id: 2, bufnr: [4])
 	filetypes:       java
 	autostart:       false
 	root directory:  /Users/andreaventi/Desktop/testingJDTLS
 	cmd:             java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.protocol=true -Dlog.level=ALL -javaagent:/Users/andreaventi/.local/share/nvim/mason/share/jdtls/lombok.jar -Xms1g --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -jar /Users/andreaventi/.local/share/nvim/mason/share/jdtls/plugins/org.eclipse.equinox.launcher.jar -configuration /Users/andreaventi/.local/share/nvim/mason/share/jdtls/config -data /Users/andreaventi/.local/share/nvim/site/java/workspace-root/testingJDTLS
 
 Client: copilot (id: 3, bufnr: [4])
 	filetypes:       
 	autostart:       false
 	root directory:  /Users/andreaventi/Desktop/testingJDTLS
 	cmd:             node /Users/andreaventi/.local/share/nvim/lazy/copilot.lua/copilot/index.js
 
 Configured servers list: tsserver, lua_ls, kotlin_language_server, eslint, csharp_ls, jsonls, emmet_ls, html, cssls, tailwindcss, clangd, pyright, docker_compose_language_service, dockerls, lemminx, marksman, bashls

This issue impacts my workflow, and I'd appreciate any assistance or guidance to resolve it. Thank you!

**Comment by Uzaaft** [comment]
I'm not experiencing the issue with the community pack. 
It's loading fine for me.
Could you try it on a clean install of astronvim? 
Just the pack without any customization.

**Comment by jay-babu** [comment]
@Uzaaft I also have this bug. Setting the event to VeryLazy fixes it for me. it also fixes it for me in jdtls lol

**Comment by Uzaaft** [comment]
Feel free to open a PR

**Comment by av1155** [comment]
I tried setting it to VeryLazy again, however, it still shows me the 

[LSP] Client with id 2 not attached to buffer 15
[LSP] Client with id 2 not attached to buffer 21
[LSP] Client with id 2 not attached to buffer 23
[LSP] Client with id 2 not attached to buffer 25
[LSP] Client with id 2 not attached to buffer 29

errors.

It also does not show the rainbow delimiters unless I close and re-open the file.

**Comment by luxus** [comment]
should be fixed by: https://github.com/AstroNvim/astrocommunity/pull/707
