### ISSUE TITLE
Unable to clone ```auto-save.nvim```

### ISSUE THREAD

**Issue by ashishbhoi** [AstroNvim/astrocommunity#675]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4 release

### Operating system/version

Ubuntu 23.10

### Terminal/GUI

zsh

### Describe the bug

Failed to clone auto-save.nvim
Error:
```
 ○ auto-save.nvim - InsertEnter - User AstroFile      ■ clone failed
              Cloning into '/home/<user-name>/.local/share/nvim/lazy/auto-save.nvim'...
              fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

### Steps to Reproduce

1. Add 
```lua
{ import = "astrocommunity.editing-support.auto-save-nvim" }
```
 to `plugins/community.lua`
2. Reload `` [space] + p + a ``

### Expected behavior

Plugin failed to sync
![Screenshot_20231208_030855](https://github.com/AstroNvim/astrocommunity/assets/33381078/8839c240-5c35-4e55-9433-d7713cbc5190)

**Comment by Uzaaft** [comment]
3c7cbc790646cd5f83b75e3130f96b868a61bf1f Fixed this.
