### ISSUE TITLE
Failed to source `/usr/share/nvim/runtime/plugin/astronvim.vim`

### ISSUE THREAD

**Issue by EsamLasheen** [AstroNvim/astrocommunity#677]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

last one 

### Operating system/version

arch 

### Terminal/GUI

kitty 

### Describe the bug

Failed to source `/usr/share/nvim/runtime/plugin/astronvim.vim`

### Steps to Reproduce

just install it 

### Expected behavior

work easy but not work 

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/55217611/27c0c071-1cba-46fe-bca4-3543a24fa73e)

**Comment by Uzaaft** [comment]
This is not astronvim, but astrocommunity. Please open the issue in the right place.
