### ISSUE TITLE
lazy/nvim-dap-go/lua/dap-go.lua:21: dap-go dependency error: dap not installed

### ISSUE THREAD

**Issue by tongwz** [AstroNvim/astrocommunity#681]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

win10

### Terminal/GUI

PowerShell

### Describe the bug

![微信截图_20231211141803](https://github.com/AstroNvim/astrocommunity/assets/29188720/fc1ae8d3-b23b-4913-850c-fc99775b22f9)

When I use the go language, it just prompts that the dap module is not avaliable, and the mfusenegger/nvim-dap is not loaded in the lazy.so I don't know how to handle this bug.

### Steps to Reproduce

Entered the go project and received the error message.

### Expected behavior

Do not prompt this error.

### Screenshots

![微信截图_20231211141803](https://github.com/AstroNvim/astrocommunity/assets/29188720/3bb312fe-33e7-48cc-82ca-225c312a8bb4)

### Additional Context

astronvim

**Comment by tongwz** [comment]
The way I introduced the go extension is written.

`{ import = "astrocommunity.pack.go" },`

this is my treesitter.lua content:
![企业微信截图_20231211143005](https://github.com/AstroNvim/astrocommunity/assets/29188720/79e15b83-c06c-4571-b182-2046366fceac)

**Comment by Uzaaft** [comment]
Do you have dvelve installed?

**Comment by tongwz** [comment]
> Do you have dvelve installed?

I have installed delve in the bin under my GOPTAH
![goEnv](https://github.com/AstroNvim/astrocommunity/assets/29188720/b39e8b1c-125d-4121-b8be-7350ba5887e2)
![dlv](https://github.com/AstroNvim/astrocommunity/assets/29188720/5ee4f0e0-e52d-4375-b38c-c1f7710f8f14)

**Comment by Uzaaft** [comment]
Astronvim doesnt support Debugging on Windows and it isnt on by default. https://docs.astronvim.com/recipes/dap/#_top

**Comment by tongwz** [comment]
> Astronvim doesnt support Debugging on Windows and it isnt on by default. https://docs.astronvim.com/recipes/dap/#_top

Thank you for giving me the answer.I have searched many places, but I am not very familiar with English, so I couldn't find this document.

**Comment by Uzaaft** [comment]
You can manually enable dap. See the link. :)
