### ISSUE TITLE
Zig pack cannot load

### ISSUE THREAD

**Issue by aquapi** [AstroNvim/astrocommunity#682]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)
v0.10.0-dev-852+g54be7d6b4

### Operating system/version

Ubuntu 23.04

### Terminal/GUI

GNOME

### Describe the bug

![image](https://github.com/AstroNvim/astrocommunity/assets/87530663/2d630736-7dc2-4786-b173-324ec659258e)

### Steps to Reproduce

Add `astrocommunity.pack.zig` to `community.lua`
```lua
return {
    "AstroNvim/astrocommunity",
    { import = "astrocommunity.pack.zig" },
    { import = "astrocommunity.pack.typescript" },
    { import = "astrocommunity.pack.cpp" },
    { import = "astrocommunity.pack.svelte" },
    { import = "astrocommunity.pack.docker" },
    { import = "astrocommunity.pack.html-css" },
    { import = "astrocommunity.pack.toml" },
    { import = "astrocommunity.pack.json" },
    { import = "astrocommunity.pack.markdown" },
    { import = "astrocommunity.pack.bash" },

    { import = "astrocommunity.colorscheme.nord-nvim" },
} 
```

### Expected behavior

Zig pack should load.

**Comment by Uzaaft** [comment]
Are you using an up to date astrocommunity version?

**Comment by aquapi** [comment]
@Uzaaft That might be an issue. But how can I check for updates?

**Comment by Uzaaft** [comment]
Just update with Lazy
