### ISSUE TITLE
Upgrade to Harpoon 2

### ISSUE THREAD

**Issue by rawnly** [AstroNvim/astrocommunity#685]
### Is your feature related to a problem?

Harpoon 1 has been deprecated. 
https://github.com/ThePrimeagen/harpoon/tree/harpoon2

### Describe the new feature

> "Harpoon 2 is significantly better and allows for MUCH greater control"

### Additional context

https://github.com/ThePrimeagen/harpoon/tree/harpoon2?tab=readme-ov-file#-note-to-legacy-harpoon-1-users

**Comment by Uzaaft** [comment]
Harpoon 2 will be merged into master in due time, so we can just let things be the way they currently are and we'll upgrade automatically. :)

**Comment by Uzaaft** [comment]
You know what, if any of you lads wants to add a PR for harpoon 2, feel free. @rawnly  @KyleKing

**Comment by KyleKing** [comment]
Haha, so I haven't actually used harpoon yet, so I'll defer to someone who is actively using it 😅 

FWIW, this might help: https://github.com/ThePrimeagen/harpoon/pull/422#issuecomment-1872992179

**Comment by Uzaaft** [comment]
Anyone who wants to feel free. I have no interest in adding it since I do not use harpoon.

**Comment by luxus** [comment]
i guess harpoon users are more kickstart.nvim users :D
