### ISSUE TITLE
bug(pack): Docker not works in docker-compose.yml.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/astrocommunity#688]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macos 13.3.1

### Terminal/GUI

kitty

### Describe the bug

I found that the compose-language-service in the bottom right corner is not working properly.

![image](https://github.com/AstroNvim/astrocommunity/assets/51357674/f40d02f9-7e90-4e9d-8ebb-68256c4d05fa)

### Steps to Reproduce

1. Create docker-compose.yml 
2. Check if the compose-language-service in the bottom right corner has started normally.

### Expected behavior

compose-language-service works well

**Comment by Uzaaft** [comment]
See of docker-compose.yaml shows a different result.

**Comment by chaozwn** [comment]
> See of docker-compose.yaml shows a different result.

still not works
<img width="1649" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/51357674/615b6955-52a6-4c70-b7d6-dafebd249f38">

**Comment by Uzaaft** [comment]
Hmm, I honestly don't understand why this is happening. I think this might be due to an issue upstream with lsp-config,

**Comment by Uzaaft** [comment]
Figured it out 🤦🏾‍♂️
