### ISSUE TITLE
LuaSnip error on fresh installation

### ISSUE THREAD

**Issue by psnilesh** [AstroNvim/astrocommunity#693]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOs 13.6.1

### Terminal/GUI

iTerm

### Describe the bug

I'm a new AstroNvim user. I followed the official installation guide and clone the repo into nvim config directory. 
```
git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
```

Now when I open any source file in nvim, I keep getting weird luasnip errors.  Commands like `:LspInstall`, `:TSInstall` throw the same error.

### Steps to Reproduce

Install AstroNvim, and open any source file. 

### Expected behavior

No errors.

### Screenshots

<img width="1769" alt="Screenshot 2023-12-24 at 6 48 44 PM" src="https://github.com/AstroNvim/astrocommunity/assets/12656997/607c5c8d-27d1-4795-b9a1-b28379060ff9">

<img width="1768" alt="Screenshot 2023-12-24 at 7 09 05 PM" src="https://github.com/AstroNvim/astrocommunity/assets/12656997/885b3ebe-5d5f-4218-8865-d9e0f855b3f4">

_No response_

**Comment by Uzaaft** [comment]
This is not the astronvim issue tracker.
