### ISSUE TITLE
Weird bug with vim-matchup and neotree

### ISSUE THREAD

**Issue by CMOISDEAD** [AstroNvim/astrocommunity#697]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Arch linux

### Terminal/GUI

Alacritty 0.13

### Describe the bug

When I add vim-matchup and then open a file it happens that if I have neotree open and I move to the last line some strange numbers are added to the beginning of the file generating errors, however if I don't have neotree open this doesn't happen.

When I remove it from my configuration, this behavior no longer happens.

### Steps to Reproduce

1. agrega vim-matchup desde community
2. abre un archivo y abre neotree
3. muevete al final de la linea con G

### Expected behavior

that these numbers do not appear at the beginning when I decide to move through the file.

### Screenshots

https://github.com/AstroNvim/astrocommunity/assets/51010598/21b44d69-f4c5-4e7c-a983-748d73e3ea7b

### Additional Context

It seems to happen with files that are somewhat long

**Comment by Uzaaft** [comment]
Does this happen if you do that outside of astrocommunity? I.e adds the plugin yourself

**Comment by CMOISDEAD** [comment]
Well I just realized that I had a file where I added an extra configuration to vim-matchup, I confirmed that it is not a bug in the astrocommunity implementation but a bug in the plugin which is related to these options `matchup_matchparen_offscreen method = popup` and `vim.g.matchup_matchparen_deferred = 1`.
