### ISSUE TITLE
Helm pack has incorrect go-template TS parser reference

### ISSUE THREAD

**Issue by lucazz** [AstroNvim/astrocommunity#703]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

macOS 14.2

### Terminal/GUI

alacritty

### Describe the bug

When adding helm pack, nvim-treesitter fails to install `gotmpl`

### Steps to Reproduce

1. Add helm pack: 
```lua
return {
  { import = "astrocommunity.pack.helm" },
}
```
2. Open Neovim

Error message: 
```
nvim-treesitter[gotmpl]: Error during tarball extraction.
```

### Expected behavior

nvim-treesitter installs `gotmpl` parser succesfully

### Screenshots

<img width="689" alt="Screenshot 2024-01-02 at 14 58 51" src="https://github.com/AstroNvim/astrocommunity/assets/6126301/7c350103-873d-4966-959d-c7c641a97b08">

**Comment by Uzaaft** [comment]
This seems like an issue with the tree-sitter repository itself and not an issue with astronvim.

**Comment by Uzaaft** [comment]
Edit: Figured out the error.

**Comment by geoffreyvanwyk** [comment]
> Edit: Figured out the error.

This is a classic.

I have a similar error but for yaml. I wonder what he figured out.

**Comment by Uzaaft** [comment]
See the PR. :) @geoffreyvanwyk
