### ISSUE TITLE
Migrate Null-ls to None LS

### ISSUE THREAD

**Issue by gabrielcaires** [AstroNvim/astrocommunity#705]
### Describe the new feature

Since https://github.com/jose-elias-alvarez/null-ls.nvim is deprecated and there is a fork, I think we should update the autocomplete plugins to use it https://github.com/nvimtools/none-ls.nvim.

**Comment by Uzaaft** [comment]
v4 will use none-ls, so this is not an issue.

**Comment by Uzaaft** [comment]
btw, none-ls doesn't handle autocomplete. :)
