### ISSUE TITLE
`pack.rust` depends on `rust-tools.nvim` which is now deprecated

### ISSUE THREAD

**Issue by rami3l** [AstroNvim/astrocommunity#706]
### Describe the new feature

I'm filing this issue simply as a reminder that [rust-tools.nvim](https://github.com/simrat39/rust-tools.nvim) has been archived by the owner on Jan 3, 2024.

### Additional context

The readme suggests moving to https://github.com/mrcjkb/rustaceanvim, but this will [cause problems](https://github.com/mrcjkb/rustaceanvim#quick-setup) for those who have already configured `rust-analyzer` via `lspconfig`.

**Comment by Uzaaft** [comment]
We'll be moving to ferris.nvim in v4, so this is not an issue. :)
