### ISSUE TITLE
feat(go pack): Workaround needed to skip diagnostic on newly created .go file

### ISSUE THREAD

**Issue by windowsrefund** [AstroNvim/astrocommunity#708]
### Is your feature related to a problem?

1. Install the go pack.
2. Create any new .go file

![error](https://github.com/AstroNvim/astrocommunity/assets/512222/378aba10-b7cd-47f9-bbda-a549319ca3f4)

### Describe the new feature

A work around would be greatly appreciated. Maybe an autocmd? Anything would be better than this and given the state of the linked upstream issue, I don't see them fixing it anytime soon.

### Additional context

https://github.com/golang/go/issues/42154

**Comment by Uzaaft** [comment]
I dont think the pack should do that, since it’s an actual compiler error if Im not wrong.

**Comment by Uzaaft** [comment]
<img width="420" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/48220549/62861e3e-12d0-45f9-9c8d-b1be9000f292">
Yes, seems like this is an actual error produced by code. We shouldn't hide or anything, so this is out of scope for astrocom.
