### ISSUE TITLE
feat(pack): rust swap from rust-tools to rustaceanvim

### ISSUE THREAD

**Issue by 0xricksanchez** [AstroNvim/astrocommunity#709]
### Describe the new feature

`rust-tools` has been sunsetted and `rustaceanvim` is an actively maintained forked of it:

Migration guide: https://github.com/mrcjkb/rustaceanvim/discussions/122

**Comment by Uzaaft** [comment]
Please put in some effort before posting an issue, and see previous issues:.
https://github.com/AstroNvim/astrocommunity/issues/706
