### ISSUE TITLE
Rust pack: Switch to from rust-tools to rustaceanvim

### ISSUE THREAD

**Issue by Oyelowo** [AstroNvim/astrocommunity#712]
### Is your feature related to a problem?

[Rust-tools](https://github.com/simrat39/rust-tools.nvim?tab=readme-ov-file) repo has now been archived

### Describe the new feature

[Rust-tools](https://github.com/simrat39/rust-tools.nvim?tab=readme-ov-file) repo has now been archived and recommends [rustaceanvim](https://github.com/mrcjkb/rustaceanvim). Let's consider switching to the latter

**Comment by Uzaaft** [comment]
Please put some effort and take a look at older issues before creating a new one.

**Comment by Oyelowo** [comment]
@Uzaaft  apologies should have checked first. Appreciate it
