### ISSUE TITLE
Typescript pack: neo-tree setup may override user's event_handlers

### ISSUE THREAD

**Issue by Townk** [AstroNvim/astrocommunity#713]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-367e52c

### Operating system/version

macOS 14.2.1

### Terminal/GUI

kitty

### Describe the bug

On the Typescript pack `init.lua` file, there are several plugins that get extra configuration to better integrate with TypeScript.

One of them is the `neo-tree` plugin, that has the following configuration:

```lua
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = function(_, opts)
      local events = require "neo-tree.events"
      opts.event_handlers = {
        {
          event = events.FILE_MOVED,
          handler = on_file_remove,
        },
        {
          event = events.FILE_RENAMED,
          handler = on_file_remove,
        },
      }
    end,
  },
```

Notice that on the line where [the `event_handlers` is defined](https://github.com/AstroNvim/astrocommunity/blob/58c28a716cf4f1725f29504bba6b91f8748f8710/lua/astrocommunity/pack/typescript/init.lua#L133), there is a simple assignment there:

```lua
      opts.event_handlers = {...}
```

This is a common problem when assuming a deep-merge is assured, which, in this case, is not. By assigning the `opts.event_handlers` to a new table, the previous table, that might have several user-defined handlers there, is lost.

### Steps to Reproduce

On your plugins table, defined a custom handler to the neo-tree plugin BEFORE you add the typescript pack. Then add the typescript pack, and restart NeoVim.

### Expected behavior

All neo-tree custom handlers should be present.

**Comment by Townk** [comment]
After some experimenting, I found that changing that plugin definition to the following snippet resolves the problem:

```lua
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = function(_, opts)
      local events = require "neo-tree.events"
      local handlers = opts.event_handlers or {}
      table.insert(handlers, {
        event = events.FILE_MOVED,
        handler = on_file_remove,
      })
      table.insert(handlers, {
        event = events.FILE_RENAMED,
        handler = on_file_remove,
      })
      opts.event_handlers = handlers
    end,
  },
```

I tried to use the `extend_tbl` function from Astro there to make thing a bit nicer, but that did not work either.

**Comment by mehalter** [comment]
Yeah `extend_tbl` works with dictionary like tables and not well for list like tables. You could use `vim.list_extend` and do something like this:

```lua
  {
    "nvim-neo-tree/neo-tree.nvim",
    opts = function(_, opts)
      local events = require "neo-tree.events"
      if not opts.event_handlers then opts.event_handlers = {} end
      vim.list_extend(opts.event_handlers, {
        { event = events.FILE_MOVED, handler = on_file_remove },
        { event = events.FILE_RENAMED, handler = on_file_remove },
      })
    end,
  },
```
