### ISSUE TITLE
V4 pack(typescript): function on_file_remove not works.

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/astrocommunity#716]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macos 13.3.1

### Terminal/GUI

kitty

### Describe the bug

because on_file_remove use tsserver. but ts-server is disabled.
btw, we lose TSToolsOrganizeImports, TSToolsSortImports, TSToolsRemoveUnusedImports and TSToolsRemoveUnused

### Steps to Reproduce

no

### Expected behavior

no

**Comment by chaozwn** [comment]
Let's take a look at the settings for typescript-tools.nvim, where we can see that tsserver has been disabled.
`
{
    "pmizio/typescript-tools.nvim",
    dependencies = {
      ---@type AstroLSPOpts
      "AstroNvim/astrolsp",
      ---@diagnostic disable: missing-fields
      opts = {
        handlers = { tsserver = false }, -- disable tsserver setup, this plugin does it
        config = {
          ["typescript-tools"] = { -- enable inlay hints by default for `typescript-tools`
            settings = {
              tsserver_file_preferences = {
                includeInlayParameterNameHints = "all",
                includeInlayParameterNameHintsWhenArgumentMatchesName = false,
                includeInlayFunctionParameterTypeHints = true,
                includeInlayVariableTypeHints = true,
                includeInlayVariableTypeHintsWhenTypeMatchesName = false,
                includeInlayPropertyDeclarationTypeHints = true,
                includeInlayFunctionLikeReturnTypeHints = true,
                includeInlayEnumMemberValueHints = true,
              },
            },
          },
        },
      },
    },
`
Therefore, when we open a TypeScript project, there is no tsserver client, which means the method for removing files will not be effective.
<img width="1374" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/51357674/be139347-099e-46f3-90d7-d802a2b34463">

`lua
local utils = require "astrocore"

local function on_file_remove(args)
  local ts_clients = vim.lsp.get_clients { name = "tsserver" }
  for _, ts_client in ipairs(ts_clients) do
    ts_client.request("workspace/executeCommand", {
      command = "_typescript.applyRenameFile",
      arguments = {
        {
          sourceUri = vim.uri_from_fname(args.source),
          targetUri = vim.uri_from_fname(args.destination),
        },
      },
    })
  end
end
`

**Comment by mehalter** [comment]
We could remove this esoteric implementation for file renaming in tsserver and add in a plugin to AstroCommunity for [nvim-lsp-file-operations](https://github.com/antosha417/nvim-lsp-file-operations) which would support much more:

```lua
return {
  "antosha417/nvim-lsp-file-operations",
  lazy = true,
  init = function(plugin) require("astrocore").on_load({ "neo-tree.nvim", "nvim-tree.lua" }, plugin.name) end,
  main = "lsp-file-operations",
  opts = {},
}
```

**Comment by mehalter** [comment]
Done in v4
