### ISSUE TITLE
Harpoon terminal bug

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#721]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.0

### Operating system/version

linux

### Terminal/GUI

kitty

### Describe the bug

<leader><leader>t  give error

### Steps to Reproduce

<leader><leader>t

### Expected behavior

Spawn a new terminal or switch an existing one

### Additional Context

On the second line of init.lua, we got:
local term_string = vim.fn.exists "$TMUX" == 1 and "tmux" or "terminal"

And should be:
local term_string = vim.fn.exists "$TMUX" == 1 and "tmux" or "term"

terminal => term 

Because when I type:
:lua requite("harpoon.term").gotoTerminal(1) => all is working.

**Comment by Uzaaft** [comment]
Feel free to open a PR with a fix @MrMic  :)

**Comment by MrMic** [comment]
OK, I will
