### ISSUE TITLE
adding openingh.nvim (link to github file

### ISSUE THREAD

**Issue by luxus** [AstroNvim/astrocommunity#732]
### Describe the new feature

https://github.com/almo7aya/openingh.nvim

@RayJameson talked about it in discord. i guess we should add it to astrocommunity.

**Comment by RayJameson** [comment]
we already have it https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/git/openingh-nvim

**Comment by RayJameson** [comment]
I created this PR to add mappings to copy url to clipboard
- AstroNvim/astrocommunity#733
