### ISSUE TITLE
Rust Pack: `rust-tools.nvim` has been archived

### ISSUE THREAD

**Issue by 0xAndoroid** [AstroNvim/astrocommunity#735]
### Is your feature related to a problem?

`rust-tools.nvim` has been archived, as mentioned [here](https://github.com/simrat39/rust-tools.nvim).  

### Describe the new feature

Maybe a switch to [mrcjkb/rustaceanvim](https://github.com/mrcjkb/rustaceanvim)

**Comment by Uzaaft** [comment]
@0xAndoroid  Please put some effort into your issue, and check already closed issues beforehand.
