### ISSUE TITLE
Java Language Pack

### ISSUE THREAD

**Issue by sjcobb2022** [AstroNvim/astrocommunity#75]
I think that adding a java language pack (using nvim-jdtls) would be a great addition to the community packages.

The default recommended settings for jdtls should be a good example.

I don't currently have a sample, however the other language packs area already a good example, and nvim-jdtls has a solid base config.

It would also be good to install a valid formatter, as jdtls does not have very good formatting on it's own.

**Comment by sjcobb2022** [comment]
https://github.com/LunarVim/starter.lvim/blob/java-ide/ftplugin/java.lua

Just found the Lunarvim java starter which should be quite easily adapted to the astro format.

**Comment by mehalter** [comment]
@sjcobb2022 this is a great idea! I'm looking forward to see what all sort of packs get contributed to this project! If you find the time to open a PR that would be amazing, in the mean time I also added the "help wanted" label so maybe someone picks it up and makes a PR!

**Comment by sjcobb2022** [comment]
> @sjcobb2022 this is a great idea! I'm looking forward to see what all sort of packs get contributed to this project! If you find the time to open a PR that would be amazing, in the mean time I also added the "help wanted" label so maybe someone picks it up and makes a PR!

I would be happy to start something although not sure how long it will take :))
