### ISSUE TITLE
Add vim-highlighter plugin

### ISSUE THREAD

**Issue by elkarouh** [AstroNvim/astrocommunity#76]
Hi,
Is there an equivalent to this [highlighter plugin](https://github.com/azabiong/vim-highlighter) ?
If not, how can i install a vimscript plugin with astroNvim?
many thanks

**Comment by mehalter** [comment]
the same as a lua plugin, you mostly just probably want to disable lazy loading because legacy vim plugins I have noticed don't lazy load very well.

```lua
{ "azabiong/vim-highlighter", lazy = false }
```

this plugin isn't in here, but it would be a great addition if you want to contribute it!

**Comment by Uzaaft** [comment]
Closed with 691fef14cf2d18200b5067e19253038320b25f85
