### ISSUE TITLE
Octo-nvim

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#760]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Linux Ubuntu 20.04

### Terminal/GUI

kitty

### Describe the bug

Cannot list Pull Request at least.

Error executing vim.schedule lua callback: Vim:E474: Attempt to decode a blank string
stack traceback:
	[C]: in function 'json_decode'
	....local/share/AstroNvim/lazy/octo.nvim/lua/octo/utils.lua:455: in function 'get_pages'
	....local/share/AstroNvim/lazy/octo.nvim/lua/octo/utils.lua:479: in function 'aggregate_pages'
	...m/lazy/octo.nvim/lua/octo/pickers/telescope/provider.lua:295: in function 'cb'
	...ocal/share/AstroNvim/lazy/octo.nvim/lua/octo/gh/init.lua:160: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

### Steps to Reproduce

1. <leader>O
2. then: p
3. then: s

### Expected behavior

List the PR on GitHub

**Comment by Uzaaft** [comment]
@MrMic  Works fine for me. Make sure you've set up the dependencies that the plugin requires

**Comment by MrMic** [comment]
I will ...

**Comment by Uzaaft** [comment]
> I will ...

Preferably before you open an issue next time.

**Comment by MrMic** [comment]
So far it was working as expected ... and the Apps requirements were 
OK. I will look into this anyway.

**Comment by Uzaaft** [comment]
It would help if you also gave us a github repo where you can reproduce the error with.

**Comment by Uzaaft** [comment]
@MrMic  Update?

**Comment by MrMic** [comment]
Yes, all the components using by this plugin work fine:
- GitHub CLI give me all the information expected.  So the issues

**Comment by Uzaaft** [comment]
Do you have a reproducable example with source code you can give me?

**Comment by MrMic** [comment]
Yes, here it is:
git@github.com:MrMic/PR_Test.git

It was just a test repo to educate me with Octo.
And then I discovered it was buggy ...

**Comment by Uzaaft** [comment]
What version of gh do you have?

**Comment by MrMic** [comment]
❯ gh --version
gh version 2.6.0-15-g1a10fd5a (2022-03-16)

**Comment by Uzaaft** [comment]
Works perfectly fine for me here @MrMic 
<img width="1509" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/48220549/1639b9cc-b1a7-4107-9fb2-002cd3879567">

**Comment by Uzaaft** [comment]
> ❯ gh --version gh version 2.6.0-15-g1a10fd5a (2022-03-16)

this is an old version, try and update it. 

I'm on 
```
gh version 2.43.1 (2024-01-31)
```

**Comment by Uzaaft** [comment]
2.6.0 is 2 years old. This is most def the issue.

**Comment by MrMic** [comment]
Yessss!  😁
❯ gh --version                   
gh version 2.44.0 (2024-02-12)
https://github.com/cli/cli/releases/tag/v2.44.0

I noticed when I upgraded my GitHub CLI that **the Snap App was buggy**.
And that is the one that I was using ...
Now all is OK.

Thank you for all!
Rgds,

**Comment by Uzaaft** [comment]
Cheers!
