### ISSUE TITLE
rust analyzer configuration not working using examples from Rust Pack readme

### ISSUE THREAD

**Issue by ewoolsey** [AstroNvim/astrocommunity#766]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Mac 14.2.1

### Terminal/GUI

Iterm2

### Describe the bug

I have this in my init.lua

```lua
  lsp = {
    config = {
      rust_analyzer = {
        settings = {
          -- Add clippy lints for Rust.
          checkOnSave = {
            allFeatures = true,
            command = "clippy",
            extraArgs = { "--no-deps" },
          },
        },
      },
    },
  },
```
Clippy is still not activated and none of these settings seems to be respected

### Steps to Reproduce

Basic setup will reproduce this

### Expected behavior

I expect these settings to work

**Comment by Uzaaft** [comment]
@ewoolsey what version of astro are you using?

**Comment by ewoolsey** [comment]
> @ewoolsey what version of astro are you using?

Found the solution, here's a PR. https://github.com/AstroNvim/astrocommunity/pull/767
Thanks!
