### ISSUE TITLE
Don't know how to setup personal colorscheme

### ISSUE THREAD

**Issue by Brutalino** [AstroNvim/astrocommunity#768]
Hello I'm new to Astronvim and I would like to apply the everforest theme. I followed the steps on the https://docs.astronvim.com/ for copying the user_example on my configuartion. In the community.lua file in my plugins folder (~/.config/nvim/lua/user/plugins). I added the colorscheme everforest and updated the init.lua file in my user folder (~/.config/nvim/lua/user) with the correct colorscheme. But even after running AstreReload it doesn't update the coloscheme. Am I missing something?

I don't know why it's not loading the colors

**Comment by Uzaaft** [comment]
@Brutalino  Wrong repo. You should ask this in the discord.

**Comment by Uzaaft** [comment]
https://docs.astronvim.com/recipes/colorscheme/ Is also helpful
