### ISSUE TITLE
Can you support Objective-c language?

### ISSUE THREAD

**Issue by FrizzleFur** [AstroNvim/astrocommunity#775]
### Is your feature related to a problem?

Yes, I am using Objective-c, while the cpp & swift pack seems not suitable.

### Describe the new feature

support Objective-c language pack

**Comment by Uzaaft** [comment]
@FrizzleFur  If you can give me the LSP, and some suitable Plugins for Objective-C, I can add a pack for it :)

**Comment by mehalter** [comment]
Why is the `cpp` pack not suitable? `clangd` supports objective C fully and also that pack installs the treesitter parser for objective c

**Comment by FrizzleFur** [comment]
> Why is the `cpp` pack not suitable? `clangd` supports objective C fully and also that pack installs the treesitter parser for objective c

well, when I try to coding in oc file, the code reference is not working well.

**Comment by FrizzleFur** [comment]
> @FrizzleFur If you can give me the LSP, and some suitable Plugins for Objective-C, I can add a pack for it :)

I have no idea on that, right now.

**Comment by Uzaaft** [comment]
> > Why is the `cpp` pack not suitable? `clangd` supports objective C fully and also that pack installs the treesitter parser for objective c
> 
> well, when I try to coding in oc file, the code reference is not working well.

As in not working at all?

**Comment by Uzaaft** [comment]
@FrizzleFur  The extensions are .h, .m, .mm, .M

**Comment by FrizzleFur** [comment]
> @FrizzleFur The extensions are .h, .m, .mm, .M

can not infer the UIKit api in .m

**Comment by Uzaaft** [comment]
Can you give me an example project and I´ll take a look @FrizzleFur

**Comment by Uzaaft** [comment]
Just tested, and it works for me. :) Tried a random obj c example with ui kit: https://github.com/xiaofei86/UIKitDynamics

**Comment by Uzaaft** [comment]
Im going to go ahead and close this.
