### ISSUE TITLE
trouble quicklist empty

### ISSUE THREAD

**Issue by louis2610** [AstroNvim/astrocommunity#782]
### Checklist

- [X] Using a stable version of Neovim (i.e. not neovim nightly)
- [X] `:AstroUpdate`
- [X] Restarted AstroNvim

### Operating system/version

macOS 14.1.1

### Terminal/GUI

kitty

### AstroNvim Health

all is ok

### Describe the bug

quicklist and loclist are empty. But lsp_worskpace_diagnostics is not.

### Steps to Reproduce

always

### Expected behavior

quickfix list is not empty.

### Screenshots

![image](https://github.com/AstroNvim/AstroNvim/assets/4217225/f01d3e17-8897-40c3-aa93-b062bd606c97)

**Comment by mehalter** [comment]
Moved to the relevant repository as it's unrelated to AstroNvim. There is also a good chance this is also unrelated to AstroCommunity and should be opened in the plugin repository upstream.

**Comment by louis2610** [comment]
> Moved to the relevant repository as it's unrelated to AstroNvim. There is also a good chance this is also unrelated to AstroCommunity and should be opened in the plugin repository upstream.

has it integrate CodeActionMenu?

**Comment by Uzaaft** [comment]
@louis2610 I get errors and warnings in my Workspace Diagnostics when using the trouble pack, and then running: `<Leader>xX`

**Comment by louis2610** [comment]
> @louis2610 I get errors and warnings in my Workspace Diagnostics when using the trouble pack, and then running: `<Leader>xX`

running : <leader>la can get quickfix list, but <leader>xX can not!

**Comment by mehalter** [comment]
This looks like @louis2610 is confusing the vim `quickfix` list with the code actions. `<Leader>la` will open the code actions from the language server. This is completely unrelated to the `quickfix` list. You can run `:h quickfix` to learn about this special vim mode.
