### ISSUE TITLE
How to use nvim-java in astro

### ISSUE THREAD

**Issue by imkratos** [AstroNvim/astrocommunity#783]
### Is your feature related to a problem?

how to use [nvim-java](https://github.com/nvim-java/nvim-java)

### Describe the new feature

how to use [nvim-java](https://github.com/nvim-java/nvim-java) or java support pakcager ?

### Additional context

[nvim-java](https://github.com/nvim-java/nvim-java) support java is batter

**Comment by Uzaaft** [comment]
You can add it to astrocommunity if you'd like.

**Comment by Uzaaft** [comment]
Currently astrocommunity does not hve that plugin. As for how to set it up with astronvim, I advice you to read the astro docs, or ask in the discord. This is not the right place to ask for astro support. :)

**Comment by imkratos** [comment]
> This is a spec for AstroNvim v3:
> 
> ```lua
> return {
>   "nvim-java/nvim-java",
>   ft = "java",
>   dependencies = {
>     "nvim-java/lua-async-await",
>     "nvim-java/nvim-java-core",
>     "nvim-java/nvim-java-test",
>     "nvim-java/nvim-java-dap",
>     "MunifTanjim/nui.nvim",
>     "neovim/nvim-lspconfig",
>     "mfussenegger/nvim-dap",
>     {
>       "williamboman/mason.nvim",
>       opts = function(_, opts)
>         if not opts.registries then opts.registries = { "github:mason-org/mason-registry" } end
>         table.insert(opts.registries, 1, "github:nvim-java/mason-registry")
>       end,
>     },
>   },
>   init = function()
>     astronvim.lsp.skip_setup = require("astronvim.utils").list_insert_unique(astronvim.lsp.skip_setup, "jdtls")
>   end,
>   config = function()
>     require("java").setup()
>     require("lspconfig").jdtls.setup(require("astronvim.utils.lsp").config "jdtls")
>   end,
> }
> ```
> 
> This is how this will be done in AstroNvim v4 if we want to add this at some point:
> 
> ```lua
> return {
>   "nvim-java/nvim-java",
>   ft = "java",
>   dependencies = {
>     "nvim-java/lua-async-await",
>     "nvim-java/nvim-java-core",
>     "nvim-java/nvim-java-test",
>     "nvim-java/nvim-java-dap",
>     "MunifTanjim/nui.nvim",
>     "neovim/nvim-lspconfig",
>     "mfussenegger/nvim-dap",
>     {
>       "williamboman/mason.nvim",
>       opts = function(_, opts)
>         if not opts.registries then opts.registries = { "github:mason-org/mason-registry" } end
>         table.insert(opts.registries, 1, "github:nvim-java/mason-registry")
>       end,
>     },
>     { "AstroNvim/astrolsp", opts = { handlers = { jdtls = false } } },
>   },
>   config = function()
>     require("java").setup()
>     require("lspconfig").jdtls.setup(require("astrolsp").lsp_opts "jdtls")
>   end,
> }
> ```

thanks bro
