### ISSUE TITLE
Pack Haskell: HLS won't start in Nix environment

### ISSUE THREAD

**Issue by Tyrn** [AstroNvim/astrocommunity#784]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Linux (Manjaro)

### Terminal/GUI

alacritty

### Describe the bug

Works with a GHCup setup.
`:LspInfo`:
```
 Language client log: /home/alexey/.local/state/nvim/lsp.log
 Detected filetype:   haskell
 
 1 client(s) attached to this buffer: 
 
 Client: haskell-tools.nvim (id: 1, bufnr: [1])
 	filetypes:       haskell, lhaskell
 	autostart:       false
 	root directory:  /home/alexey/spaces/haskell/dahastes
 	cmd:             haskell-language-server-wrapper --lsp --logfile /tmp/nvim.alexey/51Xjto/0-haskell-language-server.log
 
 Configured servers list: pyright, taplo, elmls, jsonls, lua_ls, kotlin_language_server, yamlls
```
Doesn't work with a Nix setup
`:LspInfo`:
```
 Language client log: /home/alexey/.local/state/nvim/lsp.log
 Detected filetype:   haskell
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: kotlin_language_server, taplo, elmls, yamlls, jsonls, lua_ls, pyright
```
The test project builds normally, all the necessary packages present:
```
[alexey@gaucho hello]$ type haskell-language-server
haskell-language-server is /nix/store/ycy6k3p91s6w4nvidhm9rb2inmmy342l-haskell-language-server-2.4.0.0/bin/haskell-language-server
[alexey@gaucho hello]$ type haskell-language-server-wrapper
haskell-language-server-wrapper is /nix/store/ycy6k3p91s6w4nvidhm9rb2inmmy342l-haskell-language-server-2.4.0.0/bin/haskell-language-server-wrapper
```

### Steps to Reproduce

1. [Install](https://nix.dev/install-nix.html) Nix package manager.
2. Create a test project from [template-haskell](https://github.com/jonascarpay/template-haskell) (~8GB disk space required):
```
$ git clone https://github.com/jonascarpay/template-haskell example
$ cd example
$ ./wizard.sh
$ nix develop
$ nix build
```
3. Start AstroNvim:
```
$ nvim app/Main.hs
```
4. Check `:LspInfo`

### Expected behavior

HLS should work; `:LspInfo` should look like this:
```
 Language client log: /home/alexey/.local/state/nvim/lsp.log
 Detected filetype:   haskell
 
 1 client(s) attached to this buffer: 
 
 Client: haskell-tools.nvim (id: 1, bufnr: [1])
 	filetypes:       haskell, lhaskell
 	autostart:       false
 	root directory:  /home/alexey/spaces/haskell/dahastes
 	cmd:             haskell-language-server-wrapper --lsp --logfile /tmp/nvim.alexey/DQXPKV/0-haskell-language-server.log
 
 Configured servers list: lua_ls, kotlin_language_server, pyright, jsonls, taplo, elmls, yamlls
```

### Additional Context

The OS is Manjaro (Arch Linux family)

**Comment by Uzaaft** [comment]
I can't test this, since I do not have nix on my os.

**Comment by Tyrn** [comment]
This is [quite possible](https://sandstorm.de/de/blog/post/my-first-steps-with-nix-on-mac-osx-as-homebrew-replacement.html), they say.

**Comment by Uzaaft** [comment]
I’m not going to install nix just to try and debut this, thats insanity😂

**Comment by Uzaaft** [comment]
> I’m not going to install nix just to try and debug this, thats insanity😂

**Comment by Uzaaft** [comment]
Anyways, I tools a look at our spec, we do not setup the LSP for you. This should be posted in the haskell tools repo.
