### ISSUE TITLE
Improved category structure

### ISSUE THREAD

**Issue by rozhelluk** [AstroNvim/astrocommunity#79]
Perhaps it would be better to add a single README.md file listing the plugins and information about them in the category folder where possible?
I can do that and send a pull request.

**Comment by luxus** [comment]
not sure how exactly u wanna do it.. but who will maintain it?

**Comment by mehalter** [comment]
We are also planning on getting a website put together for browsing these things as well. I'm not sure if this restructure would be the best 🤔

**Comment by rozhelluk** [comment]
so let it remain as it is
