### ISSUE TITLE
Coc progression doesn't not properly refresh

### ISSUE THREAD

**Issue by wroyca** [AstroNvim/astrocommunity#790]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev+2507-g3df1211eb

### Operating system/version

Linux fedora 6.7.7-200.fc39.x86_64

### Terminal/GUI

kitty 0.31.0

### Describe the bug

Coc progression doesn't not properly refresh on heirline "statusline". It also duplicate it progression with it own "provided" notification.

Ref: 
https://github.com/neoclide/coc.nvim/wiki/Nvim-notifications-integration
https://github.com/neoclide/coc.nvim/wiki/Statusline-integration

### Steps to Reproduce

1. Install neodev
2. Install coc-lua (CocInstall coc-lua)
3. Configure coc-settings.json with:
```json
"Lua.workspace.checkThirdParty": false,
"Lua.workspace.library": [
  "/usr/lib/nvim",
  "/usr/share/nvim/runtime",
  "/home/**username**/.local/share/nvim/lazy",
  "/home/**username**/.local/share/nvim/lazy/neodev/types/nightly"
]
```

4. Load ~/.config/nvim and watch LSP indexing progression.

### Expected behavior

Coc progression should refresh appropriately on the status line and use the AstroNvim notify plugin.

### Screenshots

![Screenshot from 2024-03-06 14-22-15](https://github.com/AstroNvim/astrocommunity/assets/91024200/3391e31f-3bba-4123-8b40-3d82506545d0)
![image](https://github.com/AstroNvim/astrocommunity/assets/91024200/75b229c8-5c60-4e35-8454-5d67005e76df)

**Comment by mehalter** [comment]
Fixed in latest commit to coc branch
