### ISSUE TITLE
Haskell Pack, HLS: Error executing vim.schedule lua callback: UnhandledPromiseRejection

### ISSUE THREAD

**Issue by Tyrn** [AstroNvim/astrocommunity#800]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Linux (Manjaro)

### Terminal/GUI

alacritty

### Describe the bug

Annoying error message:
```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
RPC[Error] code_name = unknown, code = -32803, message = "codeRange: Rule Failed: GetCodeRange"
Press ENTER or type command to continue
```

### Steps to Reproduce

1. Create a sample piece of code:
```
cmp :: String -> String -> Ordering
cmp xx y =
  if xx /= [] && y /=  []
        then compare xx y
        else EQ
```
2. Move to the `if` line, where should be a code action suggestion "Use null ... Why not: not (null y)"
3. `<Leader>la`, then choose "Apply all hints" (or any other suggestion) from the popup.

Then you can see the error message (the code action itself works fine). Actually, the message will persist on Undo and Paste, randomly.

*NB* A similar [issue](https://github.com/nvim-lua/lsp-status.nvim/issues/9). I can only tell that the [Haskell Pack](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/haskell/init.lua) seems to contain the required `on_attach` initialization.

### Expected behavior

No error message.

**Comment by Uzaaft** [comment]
I don't have Haskell installed, so marking this as help wanted for now.

**Comment by mehalter** [comment]
Looks like Haskell Language Server probably has bugs. Here are multiple issues that refer to this error message. Sadly there isn't anything to do on our end:

https://github.com/haskell/haskell-language-server/issues/4078

https://github.com/haskell/haskell-language-server/issues/4034
