### ISSUE TITLE
[Rust pack] rustacean.vim produces an error on large files

### ISSUE THREAD

**Issue by 0xAndoroid** [AstroNvim/astrocommunity#802]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2601+gb7779c514-Homebrew

### Operating system/version

macOS 14.2.1

### Terminal/GUI

iTrem2

### Describe the bug

Whenever I open a large rust file (>2000 lines) following error is produced:
```
Error executing vim.schedule lua callback: ...ovim/HEAD-b7779c5/share/nvim/runtime/lua/vim/_system.lua:241: EMFILE: too many open files
stack traceback:
	[C]: in function 'error'
	...ovim/HEAD-b7779c5/share/nvim/runtime/lua/vim/_system.lua:241: in function 'spawn'
	...ovim/HEAD-b7779c5/share/nvim/runtime/lua/vim/_system.lua:332: in function 'system'
	...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/dap.lua:191: in function 'add_dynamic_library_paths'
	...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/dap.lua:232: in function 'handle_configured_options'
	...al/share/nvim/lazy/rustaceanvim/lua/rustaceanvim/dap.lua:256: in function 'start'
	...y/rustaceanvim/lua/rustaceanvim/commands/debuggables.lua:119: in function 'callback'
	...y/rustaceanvim/lua/rustaceanvim/commands/debuggables.lua:138: in function 'handler'
	...m/HEAD-b7779c5/share/nvim/runtime/lua/vim/lsp/client.lua:680: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
  
No such error is shown if I open a smaller file first, and then open the same big file in one project.

### Steps to Reproduce

1. Install rust pack
2. Open big rust file (>2000 lines)

### Expected behavior

No errors

**Comment by Uzaaft** [comment]
If you think rustacean is causing the issue, why are you raising it here?
