### ISSUE TITLE
[colorscheme sonokai] Winbar has black color

### ISSUE THREAD

**Issue by 0xAndoroid** [AstroNvim/astrocommunity#803]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-2601+gb7779c514-Homebrew

### Operating system/version

macOS 14.2.1

### Terminal/GUI

iTerm2

### Describe the bug

After upgrade to 0.10.0 winbar is black in sonokai

### Steps to Reproduce

Install sonokai on nvim 0.10.0

### Expected behavior

Color should match tabline

### Screenshots

<img width="1512" alt="Screenshot 2024-03-15 at 19 43 33" src="https://github.com/AstroNvim/astrocommunity/assets/42178850/7418fade-3fd4-4bb5-8148-a0598d4a112d">

**Comment by 0xAndoroid** [comment]
Can be solved by adding following in highlights of astroui.lua opts
```
winbar = { bg = "#3D4455" },
```
Use bg3 from sonokai readme.

**Comment by mehalter** [comment]
This is completely unrelated to AstroCommunity at the community pack. This should be reported upstream where the colorscheme is maintained
