### ISSUE TITLE
Vue Pack's LSP became ineffective after Volar was updated to version 2

### ISSUE THREAD

**Issue by zhouyeeeee** [AstroNvim/astrocommunity#807]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 release

### Operating system/version

Windows11 24H2 2085.1

### Terminal/GUI

Tabby

### Describe the bug

After updating vue-language-server (Volar) from v1.8.27 to v2.0.7 via Mason, the LSP in Vue files stopped working.

### Steps to Reproduce

1. Update vue-language-server (volar) to version 2.0.7 using Mason.
2. Open any Vue file.
3. nside the <script> section, type "ref". Note the absence of LSP code completion suggestions.

### Expected behavior

v1.8.27
![image](https://github.com/AstroNvim/astrocommunity/assets/62367824/c7db4470-7752-4b13-ab0a-8f0e61b0f5c3)
v2.0.7
![image](https://github.com/AstroNvim/astrocommunity/assets/62367824/502580e7-3021-4550-a9a2-702b459e1fc6)

**Comment by Uzaaft** [comment]
This is an issue outside of our pack. Google returns quite a lot of threads and posts about this issue.
