### ISSUE TITLE
In Rust, inlay hints not work in v4 

### ISSUE THREAD

**Issue by lucklyisgood** [AstroNvim/astrocommunity#824]
i use `astrocommunity.pack.rust` and set AstroNvim/astrolsp `inlay_hints is true`, but it not work.
see my config [astronvim config](https://github.com/lucklyisgood/astrov4_nvim_config).

<img width="330" alt="image" src="https://github.com/AstroNvim/astrocommunity/assets/30568622/48076f6b-7ddb-4133-8d4e-caec4fd32f84">

---

it can work in v3.

**Comment by lucklyisgood** [comment]
it can work in v3.

**Comment by Uzaaft** [comment]
If you have neovim 0.10, you can toggle inlay_hints with `<Leader>uh`

**Comment by GustavoJCL** [comment]
if you use the stable release of neovim, i think you should use a plugin for this, i use lvimuser/lsp-inlayhints.nvim

**Comment by latenitecoding** [comment]
Part of the reason for this is that the rust pack is out of date. It is uses rust-tools, which is deprecated because the owner is no longer maintaining it. It should be using https://github.com/mrcjkb/rustaceanvim instead.

**Comment by lucklyisgood** [comment]
thanks, I used to use nvim 0.9.5, but I just tried downloading prelease v0.10, and it works.

**Comment by PhilVince96** [comment]
> If you have neovim 0.10, you can toggle inlay_hints with `<Leader>uh`

Is there no other solution to the problem than installing an unstable version of Neovim? I have the same issue and what's odd, it worked first try after installing pack.rust and then didn't work anymore, then logging that rust-analyzer was not installed. Now it is installed and the inlay hints are not shown. 🫠

**Comment by Uzaaft** [comment]
You can try out one of the inlay-hints plugins that are out there.
