### ISSUE TITLE
lsp_lines.nvim no longer disables diagnostic virtual text

### ISSUE THREAD

**Issue by ddiazghub** [AstroNvim/astrocommunity#825]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 release

### Operating system/version

macOS 14.2.1

### Terminal/GUI

kitty

### Describe the bug

Hello, I just wanted to report a very minor bug I noticed since v4 released. For some reason lsp_lines astrocommunity package no longer disables virtual text diagnostics automatically.

I solved it by adding the following line to polish.lua, however it might still be something that you want to look at.

![image](https://github.com/AstroNvim/astrocommunity/assets/75232825/56c03580-7143-4acf-b859-b5001c8679b9)

### Steps to Reproduce

1.  Add the lsp_lines plugin through community.lua:
![image](https://github.com/AstroNvim/astrocommunity/assets/75232825/370346c8-6a3b-462f-aa56-4c6163b9e0c1)
2. Restart neovim.
3.  Induce  an error in your code, virtual text will be enabled and diagnostics will be duplicated.
![image](https://github.com/AstroNvim/astrocommunity/assets/75232825/2aa930ab-1c19-4828-87bd-68b38a27a636)

### Expected behavior

Virtual text diagnostics shouldn't be visible, this is the same code after applying the aforementioned fix:
![image](https://github.com/AstroNvim/astrocommunity/assets/75232825/dd2998b5-162d-4ce7-a36b-9fe98a388766)

**Comment by luxus** [comment]
thanks for reporting
