### ISSUE TITLE
color/vim-highlighter clobbers keymaps

### ISSUE THREAD

**Issue by Ryex** [AstroNvim/astrocommunity#832]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Win 11

### Terminal/GUI

wezterm

### Describe the bug

Keymaps get clobbered on loading the community package

### Steps to Reproduce

 add `{ import = "astrocommunity.color.vim-highlighter" },` to your community plugins

### Expected behavior

Kepmaps from all other plugins remain in place.

### Additional Context

Problem appears to be the usage of the list table for the normal mode mappings?

**Comment by mehalter** [comment]
This is resolved: https://github.com/AstroNvim/astrocommunity/commit/425fe071e796ce9872846713cbcb2ba7d05e96e8
