### ISSUE TITLE
Highlights are overriding

### ISSUE THREAD

**Issue by snikoletopoulos** [AstroNvim/astrocommunity#833]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 release

### Operating system/version

macOS 14.4

### Terminal/GUI

WezTerm

### Describe the bug

When enabling NVChad telescope theme from AstroNvim Community and having custom unrelated highlights in astroui, the telescope highlights are overriden. Only when i remove my highlights is the theme applied

### Steps to Reproduce

1. Add NVChad telescope theme to community
2. Add custom highlights to init different from the telescope, ex. Cmp

### Expected behavior

The highlights should merge and both configs are applied

**Comment by snikoletopoulos** [comment]
Yes thank you.
It would be nicer if we didn't have to do all this.
I'll continue discussion in the AstroCommunity repo.

**Comment by mehalter** [comment]
Yeah, limitations of full flexibility means sometimes there is extra syntax

**Comment by snikoletopoulos** [comment]
@mehalter  I tried the code you showed me and it worked. But there is an error with the types and I get the following error. Should I open an issue in the astroui repo?

![image](https://github.com/AstroNvim/astrocommunity/assets/78855607/b281f2e1-0f83-4a42-89ee-10f9265123b2)
 
Also can you re-open the issue now that it is in the astrocommunity repo?

**Comment by mehalter** [comment]
No this isn't a problem with AstroUI or anything, this is just an issue of you having the wrong type annotation in your config. Check the docs here: https://docs.astronvim.com/configuration/lua_completion/
