### ISSUE TITLE
Installation of Ansible community pack fails

### ISSUE THREAD

**Issue by geoffreyvanwyk** [AstroNvim/astrocommunity#838]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 release

### Operating system/version

Windows 10 WSL2 Ubuntu 22.04

### Terminal/GUI

Windows Terminal

### Describe the bug

Using AstroNvim 4, I activated the `community.lua` file that added the line for the Ansible pack to it. I closed nvim, then reopened it to load an Ansible file. Nvim then tried to install the Yaml treesitter parser, but reported this error:

> nvim-treesitter[yaml]: Error during tarball extraction.
> tar: Skipping to next header
> 
> gzip: stdin: invalid compressed data--format violated
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now

### Steps to Reproduce

1. Install AstroNvim 4.
2. Activate the `~/.config/nvim/lua/community.lua` file by deleting the top `if` statement.
3. Add the line `{ import = "astrocommunity.pack.ansible" },` below the line `"AstroNvim/astrocommunity"`.
4. Close then reopen nvim.
5. Open a Ansible file in nvim.

### Expected behavior

All the packages and plugins specified by the Ansible pack should be installed and working as expected.

**Comment by Uzaaft** [comment]
`:TSInstall yaml` works as expected here. The pack works fine at my end.
What's the version of gzip, and tar?

**Comment by geoffreyvanwyk** [comment]
`gzip 1.10`
`tar (GNU tar) 1.34`

**Comment by geoffreyvanwyk** [comment]
Using `TSInstall yaml` also worked for me. Not sure what went wrong. Closing for now. Thanks @Uzaaft
