### ISSUE TITLE
neotest-vitest dependency not installing correctly

### ISSUE THREAD

**Issue by PatMulligan** [AstroNvim/astrocommunity#844]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Ubuntu 22.04

### Terminal/GUI

bash

### Describe the bug

When installing neotest and customizing for the adapter neotest-vitest (included as a dependency), neotest-vitest does not install and produces an error because it cannot be found

### Steps to Reproduce

1. include `{ import = "astrocommunity.test.neotest" },` in `community.lua`

2. extend the configuration with `.config/nvim/lua/plugins/neotest.lua` and add the following:
```
return {
  {
    "nvim-neotest/neotest",
    dependencies = {
      "marilari88/neotest-vitest",
    },
    opts = {
      adapters = {
        require "neotest-vitest",
      },
    },
  },
}
```

3. Restart nvim and receive the following error (the dependency does not get installed):
```
/home/me/.config/nvim/lua/plugins/neotest.lua:9: module 'neotest-vitest' not found:
  no field package.preload['neotest-vitest']
  no file './neotest-vitest.lua'
  no file '/usr/local/share/lua/5.1/neotest-vitest.lua'
  no file '/usr/local/share/lua/5.1/neotest-vitest/init.lua'
  no file '/usr/local/lib/lua/5.1/neotest-vitest.lua'
  no file '/usr/local/lib/lua/5.1/neotest-vitest/init.lua'
  no file './neotest-vitest.so'
  no file '/usr/local/lib/lua/5.1/neotest-vitest.so'

# stacktrace:
-- ~/.config/nvim/lua/plugins/neotest.lua:9
-- ~/.config/nvim/lua/lazy_setup.lua:1
-- ~/.config/nvim/init.lua:18
```

### Expected behavior

Ability to run vitest tests inside neovim with live test results

**Comment by Uzaaft** [comment]
neotest-vitest is not a part of astrocom, so this isn't a bug with us. Closing this issue since it's not a astrocommunity provided dependency, but I'll try and help.

**Comment by Uzaaft** [comment]
@PatMulligan Your config is wrong.
This is the correct config:
```lua
return {
    "nvim-neotest/neotest",
    dependencies = {
      "marilari88/neotest-vitest",
    },
    opts = function(_, opts)
      if not opts.adapters then opts.adapters = {} end
      table.insert(opts.adapters, require "neotest-vitest"(require("astrocore").plugin_opts "neotest-vitest"))
    end,
  }
```

**Comment by PatMulligan** [comment]
ah I'm getting some results now!! 🙌 Thank you @Uzaaft !! I still feel so lost when I try to do stuff with lua... I'm going to carve out some time to learn it and hopefully be able to debug this stuff better on my end and help out too. 

Apologies for posting in the wrong area, thanks so much for still helping me out. I spent the entire day yesterday banging my head against the wall. Certainly a way to learn, but always nice to see results too 😆

Appreciate you guys 🙏 This project is great inspiration. So clean 🧼
