### ISSUE TITLE
Typo/ambiguity in colorscheme name (fluoromachine)

### ISSUE THREAD

**Issue by Davidoc26** [AstroNvim/astrocommunity#846]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5 release

### Operating system/version

Linux 6.6

### Terminal/GUI

gnome-terminal

### Describe the bug

In fact, there is a typo in the colorscheme name in this repo, which, if you are not careful, will lead to the failure to load this colorscheme (even if the name of the colorscheme was written correctly in the config).

Correct name is **fluoro**machine.nvim (as it is written by the author himself: maxmx03/fluoromachine.nvim).
But now in the repository it's called **fluor**machine.nvim (#390). 

### Steps to Reproduce

Add   `{ import = "astrocommunity.colorscheme.fluoromachine-nvim" }` to your community plugins (assuming that colorscheme name is correct).

To make it work, you need to specify the wrong name(in terms of the colorscheme name): 
`{ import = "astrocommunity.colorscheme.fluormachine-nvim" }`

### Expected behavior

This should work with the correct colorscheme name:
`{ import = "astrocommunity.colorscheme.fluoromachine-nvim" }`

**Comment by Uzaaft** [comment]
Fixed in #848
