### ISSUE TITLE
Typst: typst-preview integration

### ISSUE THREAD

**Issue by Tyrn** [AstroNvim/astrocommunity#849]
### Is your feature related to a problem?

With long texts it's essential to be capable of finding the results of editing.

### Describe the new feature

Integration of [typst-preview](https://github.com/Enter-tainer/typst-preview). It seems to be possible since it has a command line interface, besides being VSCode plugin.

**Comment by Uzaaft** [comment]
@Tyrn  That's not within the scope of astrocommunity

**Comment by Uzaaft** [comment]
If there is a neovim plugin created, we can add it :)

**Comment by Tyrn** [comment]
https://github.com/chomosuke/typst-preview.nvim

**Comment by Uzaaft** [comment]
@Tyrn Feel free to add it, or create a new issue with a feature request. :)
