### ISSUE TITLE
Add a copilot-lua and copilot-cmp plugin pack 

### ISSUE THREAD

**Issue by luxus** [AstroNvim/astrocommunity#87]

**Comment by mehalter** [comment]
This wasn't intended. That should be a different plugin for sure probably a pack since it adds multiple plugins. But having one that adds copilot and reconfigures CMP bindings to play nicely is something some people want
 Adding copilot and adding them to CMP completion is different

**Comment by luxus** [comment]
> Adding copilot and adding them to CMP completion is different

its about a plugin that uses cmp

**Comment by Uzaaft** [comment]
Doesn't copilot-cpm add copilot completions to CMP?

**Comment by Uzaaft** [comment]
Or is this a tracking issue for making the keybindings work better with each other? If so, then the issue tittle is a shitty one.

**Comment by luxus** [comment]
i thought that copilot-cmp does that.. 
but i got told that copilot-cmp only behave well with cmp but not actually use the cmp menu..

**Comment by luxus** [comment]
looks like not much interest.. i will close it for now, people can make a new issue or commenting here and we can reopen it.
