### ISSUE TITLE
Ollama tab auto-complete 

### ISSUE THREAD

**Issue by Assurokilwr** [AstroNvim/astrocommunity#872]
### Describe the new feature

Just a simple tab auto-complete for ollama, because i can't see any in completion(all of them are chat only or copilotish)

**Comment by Uzaaft** [comment]
Feel free to add it @Assurokilwr  :)

**Comment by Uzaaft** [comment]
@Assurokilwr Is there a plugin for this?

**Comment by Assurokilwr** [comment]
Yes, i found it today, it is very simple and fast plus it has 17k stars⭐ 
https://github.com/TabbyML/tabby?tab=readme-ov-file
This is the installation 
https://tabby.tabbyml.com/docs/extensions/installation/vim

**Comment by Assurokilwr** [comment]
@Uzaaft Yes, i found it today, it is very simple and fast plus it has 17k stars⭐ 
https://github.com/TabbyML/tabby?tab=readme-ov-file
This is the installation 
https://tabby.tabbyml.com/docs/extensions/installation/vim

**Comment by Uzaaft** [comment]
Feel free to add it. :)

**Comment by Assurokilwr** [comment]
@Uzaaft i don't know how to do that, since i hadn't coded lua or understand neovim

**Comment by Uzaaft** [comment]
No worries, we'll just wait until someone create a PR.
