### ISSUE TITLE
Cloak is loaded after the sensitive content was shown on screen

### ISSUE THREAD

**Issue by Fryuni** [AstroNvim/astrocommunity#884]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4

### Terminal/GUI

iTerm

### Describe the bug

Using cloak as configured in this repo will load the plugin on `User AstroFile`. That event fires _after_ the content of the first file has already being shown on screen.

### Steps to Reproduce

1. Configure AstroNvim using the following community config:
   ```lua
   { "AstroNvim/astrocommunity" },
   { import = "astrocommunity.editing-support.cloak-nvim" },
   ```
2. Create a `.env` file with some variables and value
3. Close nvim
4. Run `nvim .env` to edit the env file immediately

### Expected behavior

The file should be shown initially already with the sensitive content cloaked.

### Additional Context

What happens:
1. The content of the env file, without any cloaking, is immediately shown on the screen.
2. Then, the `User AstroFile` event fires.
3. The cloak extension is loaded
4. Only then, the values of the env file get hidden

The raw content is shown for less than a second, but even a single frame would already be problematic for screen sharing and streaming.

I think the correct event for cloak should be `BufReadPre` and `BufNewFile` (that is what I'm using locally and it fixes the issue), but I'm not well versed on nvim and AstroNvim events, so there might be something more appropriate.

**Comment by luxus** [comment]
i can confirm the issue and that `event = { "BufReadPre", "BufNewFile" },` would fix it.

**Comment by luxus** [comment]
@Fryuni its merged in `main`
