### ISSUE TITLE
Ansible 

### ISSUE THREAD

**Issue by GregDuhamel** [AstroNvim/astrocommunity#894]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Fedora 40

### Terminal/GUI

Yakuake

### Describe the bug

While ansible-language-server seems to be installed correctly
```
[INFO  jeu. 18 avril 2024 19:08:55] ...e/nvim/lazy/mason.nvim/lua/mason-core/installer/init.lua:245: Installation succeeded for Package(name=ansible-language-server)
```
while i try to open ansible files, LSP crash with following error : 

```
[ERROR][2024-04-18 19:16:04] .../vim/lsp/rpc.lua:734	"rpc"	"/home/username/.local/share/nvim/mason/bin/ansible-language-server"	"stderr"	"node:internal/modules/cjs/loader:1146
  throw err;
  ^

Error: Cannot find module './ansibleLanguageService'
Require stack:
- /home/username/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/server.js
- /home/username/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/bin/ansible-language-server
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/username/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/server.js:5:34)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/username/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/server.js',
    '/home/username/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/bin/ansible-language-server'
  ]
}

Node.js v20.12.0
"
```
This happen on a fresh AstroNvim install with only ansible community pack.
Can someone please reproduce ? As it was working perfectly few days ago, it may be a local issue or the latest release of this LSP language (then it may be more upstream).

### Steps to Reproduce

1. Install Ansible Community pack
2. Open an Ansible file
3. Crash should happen immediately, LSP refuse to launch.

### Expected behavior

LSP launch.

**Comment by mehalter** [comment]
Thanks for reporting! Sadly this is a bug in the ansible language server. It is fully reproducible outside of neovim with just `npm install ansible-language-server` and then trying to use it. It looks like they are in the middle of doing a re-organization of the repository and something is going on. This should be reported upstream to the original repository: https://github.com/ansible/vscode-ansible/issues

**Comment by mehalter** [comment]
https://github.com/ansible/vscode-ansible/issues/1134#issuecomment-2065116189

dropped a comment here to see if a maintainer can help

**Comment by GregDuhamel** [comment]
Thanks a lot @mehalter. 
This issue was opened upstream : https://github.com/ansible/vscode-ansible/issues/1266
In the meantime, mason-registry was updated to reflect the wrong version : https://github.com/mason-org/mason-registry/pull/5447
