### ISSUE TITLE
[golsp] Invalid settings: prsing settings "semanticTokens"

### ISSUE THREAD

**Issue by wert2all** [AstroNvim/astrocommunity#897]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

openSUSE Tumbleweed & arch

### Terminal/GUI

alacritty

### Describe the bug

golsp issue  after open go-file

### Steps to Reproduce

1. install  "astrocommunity.pack.go"
2. create golang file
3. open file

nvim will raise an issue Invalid settings: prsing settings "semanticTokens"

### Expected behavior

no errors

### Screenshots

![20240419_18h42m16s_grim](https://github.com/AstroNvim/astrocommunity/assets/5821246/c189565e-5bae-4c0c-9fa3-07df944e9a02)

**Comment by Std-Enigma** [comment]
@wert2all Do you happen to have a .vscode folder in your project?

**Comment by wert2all** [comment]
> @wert2all Do you happen to have a .vscode folder in your project?

Omg! YEs, there is .vscode folder in progect.

**Comment by wert2all** [comment]
I delete vscode folder and issue was gone. But, this is not a solving of issue.

**Comment by wert2all** [comment]
Thanks!
