### ISSUE TITLE
Lazy warning for noice.nvim

### ISSUE THREAD

**Issue by tobias-haenel** [AstroNvim/astrocommunity#902]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch Linux

### Terminal/GUI

kitty

### Describe the bug

Including noice.nvim results in an error message from lazy.nvim:
Lua module not fonud for config of nvim. Please use a `config()` function instead.
This seems to be because of a missing name line in the catppuccin integration config
```lua
  {
    "catppuccin/nvim",
    name = "catpuccin", -- << THIS LINE IS MISSING
    optional = true,
    ---@type CatppuccinOptions
    opts = { integrations = { noice = true } },
  },
``` 
Other community plugins with catppuccin integrations might have this issue as well

### Steps to Reproduce

```lua
return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.utility.noice-nvim" },
  -- import/override with your plugins folder
}
```

### Expected behavior

No error message

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/6195791/a28c780a-82ba-421d-b095-9fd63e0e575f)

**Comment by Uzaaft** [comment]
Feel free to open a PR with a fix. :)

**Comment by luxus** [comment]
https://github.com/AstroNvim/astrocommunity/blob/0c21abbf771e8a9960d79e75568bc17369219e5c/lua/astrocommunity/colorscheme/catppuccin/init.lua#L4
the line is here.. where it should be.. 
you have to load catppuccin in your community.lua
` { import = "astrocommunity.colorscheme.catppuccin", enabled = true },`

**Comment by tobias-haenel** [comment]
Can I also use the noice.nvim community plugin wihout importing catppuccin inside ```community.lua```? I am currently importing catppuccin as a non community plugin (with ```name = "catppuccin" ``` inside ```plugins/catppuccin.lua```) and only importing noice.nvim inside ```community.lua``` 
```lua
{ import = "astrocommunity.utility.noice-nvim" }
```

Is this an underlying issue on how lazy.nvim merges the name field when multiple LazySpecs are provided for one plugin?

**Comment by tobias-haenel** [comment]
Importing catppuccin inside `community.lua` produces the same error. Lazy will create two different plugins, one with the name "catppuccin" and one with the name "nvim" from the repository ("catppuccin/nvim"). I think specifying the same name is important for Lazys plugin spec merging procedure.

**Comment by tobias-haenel** [comment]
The issue was on my side. I had an error in my plugin config. @luxus comment was correct
