### ISSUE TITLE
Typst Pack: TypstPreview isn't available

### ISSUE THREAD

**Issue by Tyrn** [AstroNvim/astrocommunity#909]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Linux (Manjaro)

### Terminal/GUI

alacritty

### Describe the bug

Neither `:TypstPreview` nor `:TypstPreviewToggle` is available. The only available command is `:TypstWatch` which starts the PDF viewer (Okular, in my case).

My `community.lua`:
```
return {
	-- Add the community repository of plugin specifications
	"AstroNvim/astrocommunity",
	-- example of imporing a plugin, comment out to use it or add your own
	-- available plugins can be found at https://github.com/AstroNvim/astrocommunity
	-- { import = "astrocommunity.colorscheme.catppuccin" },
	{ import = "astrocommunity.pack.lua" },
	{ import = "astrocommunity.pack.rust" },
	{ import = "astrocommunity.pack.python" },
	{ import = "astrocommunity.pack.kotlin" },
	{ import = "astrocommunity.pack.json" },
	{ import = "astrocommunity.pack.elm" },
	{ import = "astrocommunity.pack.nix" },
	{ import = "astrocommunity.pack.haskell" },
	{ import = "astrocommunity.pack.typst" },
}
```

### Steps to Reproduce

Start AstroNvim with any *.typ file

### Expected behavior

`:TypstPreview` and `:TypstPreviewToggle` should be available.

**Comment by Std-Enigma** [comment]
The plugin has to dowoad the necessary binaries to work before any other command in order to work.
The reason this is happening is probably because that the build process have failed 
For example you quiting nvim when they are downloading

**Comment by Std-Enigma** [comment]
The plugin has to dowoad the necessary binaries to work before any other command in order to work.
The reason this is happening is probably because that the build process have failed 
For example you quiting nvim when they are downloading
I'll add the ability for you to manually run the build command

**Comment by Std-Enigma** [comment]
#913  adds the TypstPreviewUpdate command run it and wait for it download then try using the preview again

**Comment by Tyrn** [comment]
I can see the [change](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/typst/init.lua#L18). Unfortunately, the only available command is still `:TypstWatch`. Do I have to update something manually?

**Comment by Uzaaft** [comment]
You need to update the plugins Yes.

**Comment by Tyrn** [comment]
> You need to update the plugins Yes.

I'm really sorry. I've never had to do it before. What do I have to do?

**Comment by Std-Enigma** [comment]
Run the commans Lazy sync

**Comment by Tyrn** [comment]
> Run the command Lazy sync or Lazy update

Thanks! It turned out, I'll have to update to AstroNvim 4.0 first :)

**Comment by Tyrn** [comment]
I've my AstroNvim updated to 4.0 successfully. `:TypstPreview` command is available. Unfortunately, I have only the gray canvas in my default Google Chrome browser (`http://127.0.0.1:35415/`).

Actually, there's some very brief messy activity on the canvas before the grayness sets in. I'd prefer a different (non-default) browser for preview, BTW.

**Comment by Uzaaft** [comment]
Why a non-default browser?

**Comment by Uzaaft** [comment]
If you want that, feel free to add it into your own config. :)

**Comment by Tyrn** [comment]
Using your default browser with a tiling window manager for a very special purpose is inconvenient. Something like a separate app is needed, as a matter of fact.

What do you mean, add it into your own config?

**Comment by Tyrn** [comment]
> Doing it in your own config would be more reasonable

Clearly so. Unfortunately, I've no idea how to go about it :)

**Comment by Uzaaft** [comment]
> > Doing it in your own config would be more reasonable
> 
> Clearly so. Unfortunately, I've no idea how to go about it :)

By reading the docs:
https://github.com/chomosuke/typst-preview.nvim
Hint: open_cmd

**Comment by Std-Enigma** [comment]
```lua
require 'typst-preview'.setup {
  -- Custom format string to open the output link provided with %s
  -- Example: open_cmd = 'firefox %s -P typst-preview --class typst-preview'
  open_cmd = nil,
}
```

this is what you are looking for it is part of the plugin spec if you are familiar with how customize a lazy plugin spec then you should be able to achieve what you want

**Comment by Tyrn** [comment]
Thanks! And back to the title:  I don't have any preview, just the gray canvas. I've never seen any preview so far.
