### ISSUE TITLE
clang-format installation

### ISSUE THREAD

**Issue by Learner-Geek-Perfectionist** [AstroNvim/astrocommunity#918]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1 release

### Operating system/version

WSL2 ubuntu

### Terminal/GUI

windows terminal

### Describe the bug

It does not work. 

C/C++ Language Pack

This plugin pack does the following:

Adds cpp c objc cuda proto Treesitter parsers
Adds clangd language server
Adds clang-format formatter
Adds [clangd_extensions.nvim](https://github.com/p00f/clangd_extensions.nvim) for language specific tooling
Adds [cmake-tools.nvim](https://github.com/Civitasv/cmake-tools.nvim) for building and debugging

### Steps to Reproduce

adding this code segment  in community.lua can not install clang-format formatter

  { import = "astrocommunity.pack.cpp" }, 

### Expected behavior

Adds clang-format formatter

**Comment by Uzaaft** [comment]
The c/cpp map doesn't include the format. Clangd has its own formatter

**Comment by Uzaaft** [comment]
Make sure you're updated to the newest version of everything. :)
