### ISSUE TITLE
venn-nvim recently added is not working!

### ISSUE THREAD

**Issue by MrMic** [AstroNvim/astrocommunity#920]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Linux Ubuntu 22.04

### Terminal/GUI

xfce-terminal

### Describe the bug

Bug at initial initialization:
`
Failed to run `config` for hydra.nvim

...share/AstroNvim4/lazy/lazy.nvim/lua/lazy/core/loader.lua:373: attempt to call field 'setup' (a nil value)

# stacktrace:
  - .config/AstroNvim4/lua/lazy_setup.lua:1
  - .config/AstroNvim4/init.lua:18
`

### Steps to Reproduce

Happen at startup

### Expected behavior

no notification diaplayed

**Comment by Uzaaft** [comment]
What plugins are you using? Only venn or venn and hydra

**Comment by MrMic** [comment]
I use the "venn-nvim"  package provided in the note-taking 
directory. It seems to use both: venn and hydra as written 
in the init.lua file.

**Comment by mehalter** [comment]
@MrMic I can't replicate. Please provide more information regarding this to help replicate the issue. More details on what community packs you have added, maybe share your configuration, some clear steps, etc. I added both `note-taking.venn-nvim` and `keybinding.hydra-nvim` and do not get any issue

**Comment by mehalter** [comment]
Here is a minimal `repro.lua` file that tests this:

```lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
	{ "AstroNvim/AstroNvim", import = "astronvim.plugins" },
	"AstroNvim/astrocommunity",
	{ import = "astrocommunity.note-taking.venn-nvim" },
	{ import = "astrocommunity.keybinding.hydra-nvim" },

	-- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})
```

Steps:

1. `mkdir test_venn` - make a new directory
2. `cd test_venn` - go into the directory
3. Put the contents above into `repro.lua`
4. `nvim -u repro.lua` - startup example configuration and let the installation finish
5. `:q` - quit editor
6. `nvim` - start a new session fully loaded
7. `<Leader>v` - press binding and see pop up of entering diagram mode

Clean up: delete `test_venn` directory

**Comment by MrMic** [comment]
I have fixed it.
I have added the "keybinding/hydra-nvim" package in my config.
All seems working as expected from now on... But nothing mentions that 
this package is a pre-requisite for venn-nvim package to work ...

Thanks all for giving me the hints for fixing this.
Rgds,

**Comment by Uzaaft** [comment]
> I have fixed it. I have added the "keybinding/hydra-nvim" package in my config. All seems working as expected from now on... But nothing mentions that this package is a pre-requisite for venn-nvim package to work ...
> 
> Thanks all for giving me the hints for fixing this. Rgds,

Its not a pre-requisite, it's an optional package.

**Comment by MrMic** [comment]
Without it, it is not working as mentioned above...
Anyway, it works now.

**Comment by Uzaaft** [comment]
@MrMic  The plugin works perfectly fine for me without the hydra plugin. This seems like a user error more than a bug with the pack.
