### ISSUE TITLE
astrocommunity.completion.copilot-lua-cmp is invalid

### ISSUE THREAD

**Issue by zmy20220416** [AstroNvim/astrocommunity#929]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

windows 11

### Terminal/GUI

neovide

### Describe the bug

I followed the documentation to add astrocommunity.completion.copilot-lua-cmp to community.lua and then restarted neovide, but copilot cannot be used

### Steps to Reproduce

1.  open AstroNvim config file
2. open community.lua
3. add astrocommunity.completion.copilot-lua-cmp to community.lua
4. restart nvim

### Expected behavior

no

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/123053563/078dcc82-7f2c-483b-8619-f2d6995f9b0b)

**Comment by Uzaaft** [comment]
See the first Line in the screenshot you sent…
