### ISSUE TITLE
Dart package showing "Plugin mason-tool-installer.nvim not found"

### ISSUE THREAD

**Issue by snh1999** [AstroNvim/astrocommunity#930]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Manjaro Linux

### Terminal/GUI

Gnome terminal

### Describe the bug

Adding the `dart` pack showing "Plugin mason-tool-installer.nvim not found" (see screenshot) after I press `<leader> f f` (or any other telescope shortcut)

### Steps to Reproduce

1. add ` { import = "astrocommunity.pack.dart" }` in `lua/community.lua`
2. Let necessary installs to happen
3. use `<leader> f f` and that notification (see screenshot) appears. ( `<leader> f w` showed same result too)

### Expected behavior

Other packs not causing the same issue, I peeked the code of `rust` pack - the same  "WhoIsSethDaniel/mason-tool-installer.nvim" is used in other packs as well and that is not creating any prompt. 

The notification appear only the first time after I open nvim and use  `<leader> f f`. 

and once I remove the pack, the notification goes away.

Pardon me if I am missing something obvious here,

### Screenshots

![Screenshot from 2024-04-30 16-21-08](https://github.com/AstroNvim/astrocommunity/assets/46876336/fecffef9-26a4-45e5-a2ca-bacb58066019)

### Additional Context

I tried reinstalling in a separate location, it didn't help. It is not that big of a deal, but it is kind of annoying. for now I just added flutter-tools manually.

**Comment by Std-Enigma** [comment]
It should be fixed now update your package #932

**Comment by snh1999** [comment]
It is solved now, thanks a lot
