### ISSUE TITLE
Support spring-boot

### ISSUE THREAD

**Issue by imkratos** [AstroNvim/astrocommunity#943]
### Is your feature related to a problem?

https://github.com/JavaHello/spring-boot.nvim can support ?

### Describe the new feature

https://github.com/JavaHello/spring-boot.nvim is support java spring boot 
how can i into astrovim community

**Comment by Uzaaft** [comment]
Take a look at an existing pack in astronvim community.

**Comment by imkratos** [comment]
> Take a look at an existing pack in astronvim community.

where is it ?  pack.lang.java ? i don't know. which one ? tks

**Comment by Uzaaft** [comment]
Just pick a random pack.  :)

**Comment by Uzaaft** [comment]
We shouldn't use the plugin provided here, we should use nvim-java/nvim-java

**Comment by Juniar-Rakhman** [comment]
@imkratos isn't the [existing java pack](https://github.com/AstroNvim/astrocommunity/tree/main/lua/astrocommunity/pack/java) works with spring-boot project already? What additional feature does https://github.com/JavaHello/spring-boot.nvim offer?

**Comment by imkratos** [comment]
@Juniar-Rakhman  maybe i should to read document, i didn't see help doc. tks bro.

**Comment by nithin-mk** [comment]
@Juniar-Rakhman Actually, [spring-boot.nvim](https://github.com/JavaHello/spring-boot.nvim) is a nice-to-have NeoVim plugin. It replicates the functionality of the [Spring Boot Tools](https://marketplace.visualstudio.com/items?itemName=vmware.vscode-spring-boot) extension available with VS Code. It provides the [STS4](https://github.com/spring-projects/sts4/) language server which runs along with JDTLS and provides symbols and search functionality for REST Endpoints, Spring Beans, etc. It also provides Intellisense for application.properties & application.yml files. PFA my screenshots from VS Code with that extension.

![Screenshot 2024-06-21 142531](https://github.com/AstroNvim/astrocommunity/assets/41291950/b7407a70-b47e-41ea-a562-8be0d72566e1)
![Screenshot 2024-06-21 142935](https://github.com/AstroNvim/astrocommunity/assets/41291950/ec7e88b0-1954-42d0-ac18-5a04bd01797f)

PS: The [lsp-java](https://github.com/emacs-lsp/lsp-java?tab=readme-ov-file#spring-boot-support-experimental) plugin available in Doom Emacs has been providing this functionality for quite sometime now. It would be nice for AstroNvim to support it too! 😊

**Comment by Uzaaft** [comment]
We shouldn't use spring-boot when nvim-java will do the job + replace what we already have.

**Comment by nithin-mk** [comment]
@Uzaaft 
1. The nvim-java plugin does not support the Spring-Boot specific functionality which I mentioned in my previous comment. There is an open issue regarding the same: https://github.com/nvim-java/nvim-java/issues/37
2. Besides, nvim-java is not included as a part of AstroCommunity anyway. It's not present in https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/pack/java/init.lua

**Comment by Uzaaft** [comment]
Read the whole convo. @nithin-mk

**Comment by nithin-mk** [comment]
@Uzaaft  I did read the whole convo and have been experimenting with multiple editors as of now. What are you implying? :-)
