### ISSUE TITLE
How to display whichkey in vscode after using vscode community plug-in

### ISSUE THREAD

**Issue by rjs520** [AstroNvim/astrocommunity#968]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.95

### Operating system/version

Windows11

### Terminal/GUI

Windows terminal

### Describe the bug

How to display which-key panel in vscode

### Steps to Reproduce

How to display which-key panel in vscode

### Expected behavior

How to display which-key panel in vscode

### Screenshots

![image](https://github.com/AstroNvim/astrocommunity/assets/87847751/b172ed30-9b9c-40e6-a5a2-2034abae6346)

**Comment by Std-Enigma** [comment]
I don't think it's possible

**Comment by rjs520** [comment]
> possible

How can I block whichkey so that I can use the which-key plugin in vscode to customize the key bindings I want?

**Comment by Uzaaft** [comment]
This is not a bug.

**Comment by Uzaaft** [comment]
@rjs520 You can disable it by doing this: 
```lua
return {
    "folke/which-key",
    enabled = false
}
```
