### ISSUE TITLE
Error when installing js-debug-adapter in Typescript pack

### ISSUE THREAD

**Issue by jose-badbitlabs** [AstroNvim/astrocommunity#97]
Getting the following error when installing the `js-debug-adapter` plugin in the Typescript pack: 

`Cannot write Node exec wrapper for path "out/src/vsDebugServer.js" as it doesn't exist.`

Using Node v19.8.1 and npm 9.5.1.

**Comment by mehalter** [comment]
Looks like there was probably a change in how `js-debug-adapter` installation works and is broken currently in Mason. This should be opened as an issue on Mason: https://github.com/williamboman/mason.nvim
