### ISSUE TITLE
Add this plugin `leetcode.nvim`

### ISSUE THREAD

**Issue by Mieluoxxx** [AstroNvim/astrocommunity#971]
### Describe the new feature

<img width="508" alt="截屏2024-05-18 00 35 37" src="https://github.com/AstroNvim/astrocommunity/assets/92699499/5131677f-c83a-4ec4-a788-d9e079ccbeac">

https://github.com/kawre/leetcode.nvim.git

**Comment by Uzaaft** [comment]
That's a great addition! Feel free to open a PR 😄

**Comment by Uzaaft** [comment]
Opened a PR with this since nobody did.

**Comment by mehalter** [comment]
Reopened since PR isn't merged yet. @Uzaaft it's much better practice to just add the text to the PR to link the issue and close it automatically when it's merged rather than closing it as "completed" when it's not actually completed yet
