### ISSUE TITLE
[Dart Pack] Cannot go to definition 

### ISSUE THREAD

**Issue by Richie-Z** [AstroNvim/astrocommunity#979]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

macOS 14.4.1

### Terminal/GUI

alacritty

### Describe the bug

After I've update my Neovim to v.0.10.0 i cannot go to definition on everything(function, class, widget, variable, etc). When doing that it will throw `telescope.builtin.lsp_* server does not support definationProvider`. I don't know this was a problem related to telescope x dartlsp or the integration between astronvim with the latest neovim.

### Steps to Reproduce

1. Open any dart/flutter file
2. Click gd

### Expected behavior

Jump to definition

### Screenshots

<img width="1470" alt="Screenshot 2024-05-21 at 08 59 19" src="https://github.com/AstroNvim/astrocommunity/assets/48403322/ba8924c5-7b6e-484b-87ee-2e46b530a37a">

**Comment by Uzaaft** [comment]
I believe this is a bug in telescope and not astrocommunity

**Comment by Richie-Z** [comment]
> I believe this is a bug in telescope and not astrocommunity

Yep, this bug belongs to telescope: https://github.com/mfussenegger/nvim-jdtls/issues/589#issue-2004253932
