### ISSUE TITLE
[Typescript pack] prettierd formatting give weird result with tsx files

### ISSUE THREAD

**Issue by anispwyn** [AstroNvim/astrocommunity#993]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

EndeavourOS rolling x86_64 (Linux 6.9.1-zen1-2-zen)

### Terminal/GUI

kitty

### Describe the bug

whatever i try to format tsx files, the formatter(prettierd) give weird result which doesnt happen with prettier cli or biome cli

### Steps to Reproduce

1. open to any tsx files that havent been formatted
2. type :Format
3. result

### Expected behavior

prettierd should give the same result as prettier/biome

### Screenshots

https://asciinema.org/a/XJJtP0MXdRS8lQgAOqFKRhzuu

**Comment by Uzaaft** [comment]
Prettierd should not give the same result as biome😂.

can you give us an example file and the resulting formatted file

**Comment by anispwyn** [comment]
i thought biome is just faster prettier
well here's the original file
https://files.anisp.xyz/u/jL6JqS.js

formatted file
https://files.anisp.xyz/u/bHv0hb.js

**Comment by Uzaaft** [comment]
Make sure you've updated all the plugins. And remove tsserver.

**Comment by Uzaaft** [comment]
This seems to me a user error -> user hasn't updated deps.

**Comment by Uzaaft** [comment]
> i thought biome is just faster prettier well here's the original file https://files.anisp.xyz/u/jL6JqS.js
> 
> formatted file https://files.anisp.xyz/u/bHv0hb.js
> 
> (the file extension should be jsx/tsx but my file uploader automatically change that for some reason)

No, biome has other defaults. Read their docs.

**Comment by anispwyn** [comment]
seems to be working now, thanks
