### ISSUE TITLE
C/C++ Language Pack on linux/arm64

### ISSUE THREAD

**Issue by joshheyse** [AstroNvim/astrocommunity#994]
### Is your feature related to a problem?

Using the C/C++ Language Pack on a linux arm64 system fails.  This is because Mason fails to download an arm64 clangd binary from github.  

### Describe the new feature

Clangd is supported on linux arm64. It can be installed from a distro package manager or installed from source.  In this case clangd should jsut be added to the servers section and omitted from the ensure_installed in the C/C++ Language Pack init script

lsp/servers.lua
```
return {
  "clangd"
 }
```

**Comment by mehalter** [comment]
Resolves with #997
